// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadAmountOfSubstance() {
        // Loading AmountOfSubstance
        var AmountOfSubstanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Mole
        AmountOfSubstanceUnits.TryAdd("Mole", new Unit(
            SingularName: "Mole",
            PluralName: "Moles",
            Abbreviations: ["mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // FemtoMole
        AmountOfSubstanceUnits.TryAdd("FemtoMole", new Unit(
            SingularName: "FemtoMole",
            PluralName: "FemtoMoles",
            Abbreviations: ["fmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-15,
            FromUnitToBase: static val => (val) * 1E-15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoMole
        AmountOfSubstanceUnits.TryAdd("PicoMole", new Unit(
            SingularName: "PicoMole",
            PluralName: "PicoMoles",
            Abbreviations: ["pmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoMole
        AmountOfSubstanceUnits.TryAdd("NanoMole", new Unit(
            SingularName: "NanoMole",
            PluralName: "NanoMoles",
            Abbreviations: ["nmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroMole
        AmountOfSubstanceUnits.TryAdd("MicroMole", new Unit(
            SingularName: "MicroMole",
            PluralName: "MicroMoles",
            Abbreviations: ["µmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliMole
        AmountOfSubstanceUnits.TryAdd("MilliMole", new Unit(
            SingularName: "MilliMole",
            PluralName: "MilliMoles",
            Abbreviations: ["mmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiMole
        AmountOfSubstanceUnits.TryAdd("CentiMole", new Unit(
            SingularName: "CentiMole",
            PluralName: "CentiMoles",
            Abbreviations: ["cmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciMole
        AmountOfSubstanceUnits.TryAdd("DeciMole", new Unit(
            SingularName: "DeciMole",
            PluralName: "DeciMoles",
            Abbreviations: ["dmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMole
        AmountOfSubstanceUnits.TryAdd("KiloMole", new Unit(
            SingularName: "KiloMole",
            PluralName: "KiloMoles",
            Abbreviations: ["kmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaMole
        AmountOfSubstanceUnits.TryAdd("MegaMole", new Unit(
            SingularName: "MegaMole",
            PluralName: "MegaMoles",
            Abbreviations: ["Mmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundMole
        AmountOfSubstanceUnits.TryAdd("PoundMole", new Unit(
            SingularName: "PoundMole",
            PluralName: "PoundMoles",
            Abbreviations: ["lbmol"],
            Factor: 453.59237,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoPoundMole
        AmountOfSubstanceUnits.TryAdd("NanoPoundMole", new Unit(
            SingularName: "NanoPoundMole",
            PluralName: "NanoPoundMoles",
            Abbreviations: ["nlbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 1E-09,
            FromUnitToBase: static val => (val * 453.59237) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroPoundMole
        AmountOfSubstanceUnits.TryAdd("MicroPoundMole", new Unit(
            SingularName: "MicroPoundMole",
            PluralName: "MicroPoundMoles",
            Abbreviations: ["µlbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 1E-06,
            FromUnitToBase: static val => (val * 453.59237) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliPoundMole
        AmountOfSubstanceUnits.TryAdd("MilliPoundMole", new Unit(
            SingularName: "MilliPoundMole",
            PluralName: "MilliPoundMoles",
            Abbreviations: ["mlbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 0.001,
            FromUnitToBase: static val => (val * 453.59237) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiPoundMole
        AmountOfSubstanceUnits.TryAdd("CentiPoundMole", new Unit(
            SingularName: "CentiPoundMole",
            PluralName: "CentiPoundMoles",
            Abbreviations: ["clbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 0.01,
            FromUnitToBase: static val => (val * 453.59237) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciPoundMole
        AmountOfSubstanceUnits.TryAdd("DeciPoundMole", new Unit(
            SingularName: "DeciPoundMole",
            PluralName: "DeciPoundMoles",
            Abbreviations: ["dlbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 0.1,
            FromUnitToBase: static val => (val * 453.59237) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundMole
        AmountOfSubstanceUnits.TryAdd("KiloPoundMole", new Unit(
            SingularName: "KiloPoundMole",
            PluralName: "KiloPoundMoles",
            Abbreviations: ["klbmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) / 1000,
            FromUnitToBase: static val => (val * 453.59237) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "AmountOfSubstance",
            "Mole",
            "Mole is the amount of substance containing Avagadro's Number (6.02 x 10 ^ 23) of real particles such as molecules,atoms, ions or radicals.",
            AmountOfSubstanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["N"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("AmountOfSubstance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
