// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadAmplitudeRatio() {
        // Loading AmplitudeRatio
        var AmplitudeRatioUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // DecibelVolt
        AmplitudeRatioUnits.TryAdd("DecibelVolt", new Unit(
            SingularName: "DecibelVolt",
            PluralName: "DecibelVolts",
            Abbreviations: ["dBV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecibelMicrovolt
        AmplitudeRatioUnits.TryAdd("DecibelMicrovolt", new Unit(
            SingularName: "DecibelMicrovolt",
            PluralName: "DecibelMicrovolts",
            Abbreviations: ["dBµV"],
            Factor: 1,
            Offset: -120,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecibelMillivolt
        AmplitudeRatioUnits.TryAdd("DecibelMillivolt", new Unit(
            SingularName: "DecibelMillivolt",
            PluralName: "DecibelMillivolts",
            Abbreviations: ["dBmV"],
            Factor: 1,
            Offset: -60,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecibelUnloaded
        AmplitudeRatioUnits.TryAdd("DecibelUnloaded", new Unit(
            SingularName: "DecibelUnloaded",
            PluralName: "DecibelsUnloaded",
            Abbreviations: ["dBu"],
            Factor: 1,
            Offset: -2.218487499,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "AmplitudeRatio",
            "DecibelVolt",
            "The strength of a signal expressed in decibels (dB) relative to one volt RMS.",
            AmplitudeRatioUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            true,
            2
        );
        _quantities.Add("AmplitudeRatio", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
