// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadAreaDensity() {
        // Loading AreaDensity
        var AreaDensityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // KilogramPerSquareMeter
        AreaDensityUnits.TryAdd("KilogramPerSquareMeter", new Unit(
            SingularName: "KilogramPerSquareMeter",
            PluralName: "KilogramsPerSquareMeter",
            Abbreviations: ["kg/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerSquareMeter
        AreaDensityUnits.TryAdd("GramPerSquareMeter", new Unit(
            SingularName: "GramPerSquareMeter",
            PluralName: "GramsPerSquareMeter",
            Abbreviations: ["g/m²", "gsm"],
            Factor: 0.001,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Grammage",
            ObsoleteText: ""
        ));
        // MilligramPerSquareMeter
        AreaDensityUnits.TryAdd("MilligramPerSquareMeter", new Unit(
            SingularName: "MilligramPerSquareMeter",
            PluralName: "MilligramsPerSquareMeter",
            Abbreviations: ["mg/m²"],
            Factor: 1E-06,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "AreaDensity",
            "KilogramPerSquareMeter",
            "The area density of a two-dimensional object is calculated as the mass per unit area. For paper this is also called grammage.",
            AreaDensityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("AreaDensity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
