// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadArea() {
        // Loading Area
        var AreaUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // SquareKilometer
        AreaUnits.TryAdd("SquareKilometer", new Unit(
            SingularName: "SquareKilometer",
            PluralName: "SquareKilometers",
            Abbreviations: ["km²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e6,
            FromUnitToBase: static val => val * 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMeter
        AreaUnits.TryAdd("SquareMeter", new Unit(
            SingularName: "SquareMeter",
            PluralName: "SquareMeters",
            Abbreviations: ["m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareDecimeter
        AreaUnits.TryAdd("SquareDecimeter", new Unit(
            SingularName: "SquareDecimeter",
            PluralName: "SquareDecimeters",
            Abbreviations: ["dm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-2,
            FromUnitToBase: static val => val * 1e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareCentimeter
        AreaUnits.TryAdd("SquareCentimeter", new Unit(
            SingularName: "SquareCentimeter",
            PluralName: "SquareCentimeters",
            Abbreviations: ["cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-4,
            FromUnitToBase: static val => val * 1e-4,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMillimeter
        AreaUnits.TryAdd("SquareMillimeter", new Unit(
            SingularName: "SquareMillimeter",
            PluralName: "SquareMillimeters",
            Abbreviations: ["mm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-6,
            FromUnitToBase: static val => val * 1e-6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMicrometer
        AreaUnits.TryAdd("SquareMicrometer", new Unit(
            SingularName: "SquareMicrometer",
            PluralName: "SquareMicrometers",
            Abbreviations: ["µm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-12,
            FromUnitToBase: static val => val * 1e-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMile
        AreaUnits.TryAdd("SquareMile", new Unit(
            SingularName: "SquareMile",
            PluralName: "SquareMiles",
            Abbreviations: ["mi²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1609.344 / 1609.344,
            FromUnitToBase: static val => val * 1609.344 * 1609.344,
            Remarks: "https://en.wikipedia.org/wiki/Mile",
            ObsoleteText: ""
        ));
        // SquareYard
        AreaUnits.TryAdd("SquareYard", new Unit(
            SingularName: "SquareYard",
            PluralName: "SquareYards",
            Abbreviations: ["yd²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 0.9144 / 0.9144,
            FromUnitToBase: static val => val * 0.9144 * 0.9144,
            Remarks: "https://en.wikipedia.org/wiki/Yard",
            ObsoleteText: ""
        ));
        // SquareFoot
        AreaUnits.TryAdd("SquareFoot", new Unit(
            SingularName: "SquareFoot",
            PluralName: "SquareFeet",
            Abbreviations: ["ft²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.290304e-2,
            FromUnitToBase: static val => val * 9.290304e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UsSurveySquareFoot
        AreaUnits.TryAdd("UsSurveySquareFoot", new Unit(
            SingularName: "UsSurveySquareFoot",
            PluralName: "UsSurveySquareFeet",
            Abbreviations: ["ft² (US)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1200.0 / 3937.0) / (1200.0 / 3937.0),
            FromUnitToBase: static val => val * (1200.0 / 3937.0) * (1200.0 / 3937.0),
            Remarks: "https://en.wikipedia.org/wiki/Foot_(unit)",
            ObsoleteText: ""
        ));
        // SquareInch
        AreaUnits.TryAdd("SquareInch", new Unit(
            SingularName: "SquareInch",
            PluralName: "SquareInches",
            Abbreviations: ["in²"],
            Factor: 0.00064516,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Acre
        AreaUnits.TryAdd("Acre", new Unit(
            SingularName: "Acre",
            PluralName: "Acres",
            Abbreviations: ["ac"],
            Factor: 4046.8564224,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Acre",
            ObsoleteText: ""
        ));
        // Hectare
        AreaUnits.TryAdd("Hectare", new Unit(
            SingularName: "Hectare",
            PluralName: "Hectares",
            Abbreviations: ["ha"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e4,
            FromUnitToBase: static val => val * 1e4,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareNauticalMile
        AreaUnits.TryAdd("SquareNauticalMile", new Unit(
            SingularName: "SquareNauticalMile",
            PluralName: "SquareNauticalMiles",
            Abbreviations: ["nmi²"],
            Factor: 3429904,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Area",
            "SquareMeter",
            "Area is a quantity that expresses the extent of a two-dimensional surface or shape, or planar lamina, in the plane. Area can be understood as the amount of material with a given thickness that would be necessary to fashion a model of the shape, or the amount of paint necessary to cover the surface with a single coat.[1] It is the two-dimensional analog of the length of a curve (a one-dimensional concept) or the volume of a solid (a three-dimensional concept).",
            AreaUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("Area", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
