// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadBrakeSpecificFuelConsumption() {
        // Loading BrakeSpecificFuelConsumption
        var BrakeSpecificFuelConsumptionUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // GramPerKiloWattHour
        BrakeSpecificFuelConsumptionUnits.TryAdd("GramPerKiloWattHour", new Unit(
            SingularName: "GramPerKiloWattHour",
            PluralName: "GramsPerKiloWattHour",
            Abbreviations: ["g/kWh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 3.6e9,
            FromUnitToBase: static val => val / 3.6e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramPerJoule
        BrakeSpecificFuelConsumptionUnits.TryAdd("KilogramPerJoule", new Unit(
            SingularName: "KilogramPerJoule",
            PluralName: "KilogramsPerJoule",
            Abbreviations: ["kg/J"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerMechanicalHorsepowerHour
        BrakeSpecificFuelConsumptionUnits.TryAdd("PoundPerMechanicalHorsepowerHour", new Unit(
            SingularName: "PoundPerMechanicalHorsepowerHour",
            PluralName: "PoundsPerMechanicalHorsepowerHour",
            Abbreviations: ["lb/hph"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 3600 / (0.45359237 / (76.0402249 * 9.80665)),
            FromUnitToBase: static val => val * (0.45359237 / (76.0402249 * 9.80665))/3600,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "BrakeSpecificFuelConsumption",
            "KilogramPerJoule",
            "Brake specific fuel consumption (BSFC) is a measure of the fuel efficiency of any prime mover that burns fuel and produces rotational, or shaft, power. It is typically used for comparing the efficiency of internal combustion engines with a shaft output.",
            BrakeSpecificFuelConsumptionUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["T"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("BrakeSpecificFuelConsumption", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
