// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadCompressibility() {
        // Loading Compressibility
        var CompressibilityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // InversePascal
        CompressibilityUnits.TryAdd("InversePascal", new Unit(
            SingularName: "InversePascal",
            PluralName: "InversePascals",
            Abbreviations: ["Pa⁻¹", "1/Pa"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseKilopascal
        CompressibilityUnits.TryAdd("InverseKilopascal", new Unit(
            SingularName: "InverseKilopascal",
            PluralName: "InverseKilopascals",
            Abbreviations: ["kPa⁻¹", "1/kPa"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e3,
            FromUnitToBase: static val => val * 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMegapascal
        CompressibilityUnits.TryAdd("InverseMegapascal", new Unit(
            SingularName: "InverseMegapascal",
            PluralName: "InverseMegapascals",
            Abbreviations: ["MPa⁻¹", "1/MPa"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e6,
            FromUnitToBase: static val => val * 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseAtmosphere
        CompressibilityUnits.TryAdd("InverseAtmosphere", new Unit(
            SingularName: "InverseAtmosphere",
            PluralName: "InverseAtmospheres",
            Abbreviations: ["atm⁻¹", "1/atm"],
            Factor: 101325,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMillibar
        CompressibilityUnits.TryAdd("InverseMillibar", new Unit(
            SingularName: "InverseMillibar",
            PluralName: "InverseMillibars",
            Abbreviations: ["mbar⁻¹", "1/mbar"],
            Factor: 100,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseBar
        CompressibilityUnits.TryAdd("InverseBar", new Unit(
            SingularName: "InverseBar",
            PluralName: "InverseBars",
            Abbreviations: ["bar⁻¹", "1/bar"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5,
            FromUnitToBase: static val => val * 1e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InversePoundForcePerSquareInch
        CompressibilityUnits.TryAdd("InversePoundForcePerSquareInch", new Unit(
            SingularName: "InversePoundForcePerSquareInch",
            PluralName: "InversePoundsForcePerSquareInch",
            Abbreviations: ["psi⁻¹", "1/psi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6.894757293168361e3,
            FromUnitToBase: static val => val * 6.894757293168361e3,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Compressibility",
            "InversePascal",
            "",
            CompressibilityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = -1, ["T"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("Compressibility", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
