// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricConductance() {
        // Loading ElectricConductance
        var ElectricConductanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Siemens
        ElectricConductanceUnits.TryAdd("Siemens", new Unit(
            SingularName: "Siemens",
            PluralName: "Siemens",
            Abbreviations: ["S"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoSiemens
        ElectricConductanceUnits.TryAdd("NanoSiemens", new Unit(
            SingularName: "NanoSiemens",
            PluralName: "NanoSiemens",
            Abbreviations: ["nS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroSiemens
        ElectricConductanceUnits.TryAdd("MicroSiemens", new Unit(
            SingularName: "MicroSiemens",
            PluralName: "MicroSiemens",
            Abbreviations: ["µS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliSiemens
        ElectricConductanceUnits.TryAdd("MilliSiemens", new Unit(
            SingularName: "MilliSiemens",
            PluralName: "MilliSiemens",
            Abbreviations: ["mS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloSiemens
        ElectricConductanceUnits.TryAdd("KiloSiemens", new Unit(
            SingularName: "KiloSiemens",
            PluralName: "KiloSiemens",
            Abbreviations: ["kS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaSiemens
        ElectricConductanceUnits.TryAdd("MegaSiemens", new Unit(
            SingularName: "MegaSiemens",
            PluralName: "MegaSiemens",
            Abbreviations: ["MS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaSiemens
        ElectricConductanceUnits.TryAdd("GigaSiemens", new Unit(
            SingularName: "GigaSiemens",
            PluralName: "GigaSiemens",
            Abbreviations: ["GS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraSiemens
        ElectricConductanceUnits.TryAdd("TeraSiemens", new Unit(
            SingularName: "TeraSiemens",
            PluralName: "TeraSiemens",
            Abbreviations: ["TS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Mho
        ElectricConductanceUnits.TryAdd("Mho", new Unit(
            SingularName: "Mho",
            PluralName: "Mhos",
            Abbreviations: ["℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoMho
        ElectricConductanceUnits.TryAdd("NanoMho", new Unit(
            SingularName: "NanoMho",
            PluralName: "NanoMhos",
            Abbreviations: ["n℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroMho
        ElectricConductanceUnits.TryAdd("MicroMho", new Unit(
            SingularName: "MicroMho",
            PluralName: "MicroMhos",
            Abbreviations: ["µ℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliMho
        ElectricConductanceUnits.TryAdd("MilliMho", new Unit(
            SingularName: "MilliMho",
            PluralName: "MilliMhos",
            Abbreviations: ["m℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMho
        ElectricConductanceUnits.TryAdd("KiloMho", new Unit(
            SingularName: "KiloMho",
            PluralName: "KiloMhos",
            Abbreviations: ["k℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaMho
        ElectricConductanceUnits.TryAdd("MegaMho", new Unit(
            SingularName: "MegaMho",
            PluralName: "MegaMhos",
            Abbreviations: ["M℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaMho
        ElectricConductanceUnits.TryAdd("GigaMho", new Unit(
            SingularName: "GigaMho",
            PluralName: "GigaMhos",
            Abbreviations: ["G℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraMho
        ElectricConductanceUnits.TryAdd("TeraMho", new Unit(
            SingularName: "TeraMho",
            PluralName: "TeraMhos",
            Abbreviations: ["T℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricConductance",
            "Siemens",
            "The electrical conductance of an object is a measure of the ease with which an electric current passes. Along with susceptance, it is one of two elements of admittance. Its reciprocal quantity is electrical resistance.",
            ElectricConductanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = -1, ["T"] = 3, ["I"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricConductance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
