// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricPotential() {
        // Loading ElectricPotential
        var ElectricPotentialUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Volt
        ElectricPotentialUnits.TryAdd("Volt", new Unit(
            SingularName: "Volt",
            PluralName: "Volts",
            Abbreviations: ["V"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoVolt
        ElectricPotentialUnits.TryAdd("NanoVolt", new Unit(
            SingularName: "NanoVolt",
            PluralName: "NanoVolts",
            Abbreviations: ["nV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroVolt
        ElectricPotentialUnits.TryAdd("MicroVolt", new Unit(
            SingularName: "MicroVolt",
            PluralName: "MicroVolts",
            Abbreviations: ["µV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliVolt
        ElectricPotentialUnits.TryAdd("MilliVolt", new Unit(
            SingularName: "MilliVolt",
            PluralName: "MilliVolts",
            Abbreviations: ["mV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloVolt
        ElectricPotentialUnits.TryAdd("KiloVolt", new Unit(
            SingularName: "KiloVolt",
            PluralName: "KiloVolts",
            Abbreviations: ["kV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaVolt
        ElectricPotentialUnits.TryAdd("MegaVolt", new Unit(
            SingularName: "MegaVolt",
            PluralName: "MegaVolts",
            Abbreviations: ["MV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricPotential",
            "Volt",
            "In classical electromagnetism, the electric potential (a scalar quantity denoted by Φ, ΦE or V and also called the electric field potential or the electrostatic potential) at a point is the amount of electric potential energy that a unitary point charge would have when located at that point.",
            ElectricPotentialUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -3, ["I"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricPotential", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
