// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricSusceptance() {
        // Loading ElectricSusceptance
        var ElectricSusceptanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Siemens
        ElectricSusceptanceUnits.TryAdd("Siemens", new Unit(
            SingularName: "Siemens",
            PluralName: "Siemens",
            Abbreviations: ["S"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoSiemens
        ElectricSusceptanceUnits.TryAdd("NanoSiemens", new Unit(
            SingularName: "NanoSiemens",
            PluralName: "NanoSiemens",
            Abbreviations: ["nS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroSiemens
        ElectricSusceptanceUnits.TryAdd("MicroSiemens", new Unit(
            SingularName: "MicroSiemens",
            PluralName: "MicroSiemens",
            Abbreviations: ["µS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliSiemens
        ElectricSusceptanceUnits.TryAdd("MilliSiemens", new Unit(
            SingularName: "MilliSiemens",
            PluralName: "MilliSiemens",
            Abbreviations: ["mS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloSiemens
        ElectricSusceptanceUnits.TryAdd("KiloSiemens", new Unit(
            SingularName: "KiloSiemens",
            PluralName: "KiloSiemens",
            Abbreviations: ["kS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaSiemens
        ElectricSusceptanceUnits.TryAdd("MegaSiemens", new Unit(
            SingularName: "MegaSiemens",
            PluralName: "MegaSiemens",
            Abbreviations: ["MS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaSiemens
        ElectricSusceptanceUnits.TryAdd("GigaSiemens", new Unit(
            SingularName: "GigaSiemens",
            PluralName: "GigaSiemens",
            Abbreviations: ["GS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraSiemens
        ElectricSusceptanceUnits.TryAdd("TeraSiemens", new Unit(
            SingularName: "TeraSiemens",
            PluralName: "TeraSiemens",
            Abbreviations: ["TS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Mho
        ElectricSusceptanceUnits.TryAdd("Mho", new Unit(
            SingularName: "Mho",
            PluralName: "Mhos",
            Abbreviations: ["℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoMho
        ElectricSusceptanceUnits.TryAdd("NanoMho", new Unit(
            SingularName: "NanoMho",
            PluralName: "NanoMhos",
            Abbreviations: ["n℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroMho
        ElectricSusceptanceUnits.TryAdd("MicroMho", new Unit(
            SingularName: "MicroMho",
            PluralName: "MicroMhos",
            Abbreviations: ["µ℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliMho
        ElectricSusceptanceUnits.TryAdd("MilliMho", new Unit(
            SingularName: "MilliMho",
            PluralName: "MilliMhos",
            Abbreviations: ["m℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMho
        ElectricSusceptanceUnits.TryAdd("KiloMho", new Unit(
            SingularName: "KiloMho",
            PluralName: "KiloMhos",
            Abbreviations: ["k℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaMho
        ElectricSusceptanceUnits.TryAdd("MegaMho", new Unit(
            SingularName: "MegaMho",
            PluralName: "MegaMhos",
            Abbreviations: ["M℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaMho
        ElectricSusceptanceUnits.TryAdd("GigaMho", new Unit(
            SingularName: "GigaMho",
            PluralName: "GigaMhos",
            Abbreviations: ["G℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraMho
        ElectricSusceptanceUnits.TryAdd("TeraMho", new Unit(
            SingularName: "TeraMho",
            PluralName: "TeraMhos",
            Abbreviations: ["T℧"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricSusceptance",
            "Siemens",
            "Electrical susceptance is the imaginary part of admittance, where the real part is conductance.",
            ElectricSusceptanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = -1, ["T"] = 3, ["I"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricSusceptance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
