// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricCharge() {
        // Loading ElectricCharge
        var ElectricChargeUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Coulomb
        ElectricChargeUnits.TryAdd("Coulomb", new Unit(
            SingularName: "Coulomb",
            PluralName: "Coulombs",
            Abbreviations: ["C"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoCoulomb
        ElectricChargeUnits.TryAdd("PicoCoulomb", new Unit(
            SingularName: "PicoCoulomb",
            PluralName: "PicoCoulombs",
            Abbreviations: ["pC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoCoulomb
        ElectricChargeUnits.TryAdd("NanoCoulomb", new Unit(
            SingularName: "NanoCoulomb",
            PluralName: "NanoCoulombs",
            Abbreviations: ["nC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroCoulomb
        ElectricChargeUnits.TryAdd("MicroCoulomb", new Unit(
            SingularName: "MicroCoulomb",
            PluralName: "MicroCoulombs",
            Abbreviations: ["µC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliCoulomb
        ElectricChargeUnits.TryAdd("MilliCoulomb", new Unit(
            SingularName: "MilliCoulomb",
            PluralName: "MilliCoulombs",
            Abbreviations: ["mC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCoulomb
        ElectricChargeUnits.TryAdd("KiloCoulomb", new Unit(
            SingularName: "KiloCoulomb",
            PluralName: "KiloCoulombs",
            Abbreviations: ["kC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaCoulomb
        ElectricChargeUnits.TryAdd("MegaCoulomb", new Unit(
            SingularName: "MegaCoulomb",
            PluralName: "MegaCoulombs",
            Abbreviations: ["MC"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AmpereHour
        ElectricChargeUnits.TryAdd("AmpereHour", new Unit(
            SingularName: "AmpereHour",
            PluralName: "AmpereHours",
            Abbreviations: ["A-h", "Ah"],
            Factor: 3600,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliAmpereHour
        ElectricChargeUnits.TryAdd("MilliAmpereHour", new Unit(
            SingularName: "MilliAmpereHour",
            PluralName: "MilliAmpereHours",
            Abbreviations: ["mA-h", "mAh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600) / 0.001,
            FromUnitToBase: static val => (val * 3600) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloAmpereHour
        ElectricChargeUnits.TryAdd("KiloAmpereHour", new Unit(
            SingularName: "KiloAmpereHour",
            PluralName: "KiloAmpereHours",
            Abbreviations: ["kA-h", "kAh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600) / 1000,
            FromUnitToBase: static val => (val * 3600) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaAmpereHour
        ElectricChargeUnits.TryAdd("MegaAmpereHour", new Unit(
            SingularName: "MegaAmpereHour",
            PluralName: "MegaAmpereHours",
            Abbreviations: ["MA-h", "MAh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600) / 1000000,
            FromUnitToBase: static val => (val * 3600) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricCharge",
            "Coulomb",
            "Electric charge is the physical property of matter that causes it to experience a force when placed in an electromagnetic field.",
            ElectricChargeUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = 1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricCharge", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
