// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricCurrentGradient() {
        // Loading ElectricCurrentGradient
        var ElectricCurrentGradientUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // AmperePerSecond
        ElectricCurrentGradientUnits.TryAdd("AmperePerSecond", new Unit(
            SingularName: "AmperePerSecond",
            PluralName: "AmperesPerSecond",
            Abbreviations: ["A/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliAmperePerSecond
        ElectricCurrentGradientUnits.TryAdd("MilliAmperePerSecond", new Unit(
            SingularName: "MilliAmperePerSecond",
            PluralName: "MilliAmperesPerSecond",
            Abbreviations: ["mA/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AmperePerMinute
        ElectricCurrentGradientUnits.TryAdd("AmperePerMinute", new Unit(
            SingularName: "AmperePerMinute",
            PluralName: "AmperesPerMinute",
            Abbreviations: ["A/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliAmperePerMinute
        ElectricCurrentGradientUnits.TryAdd("MilliAmperePerMinute", new Unit(
            SingularName: "MilliAmperePerMinute",
            PluralName: "MilliAmperesPerMinute",
            Abbreviations: ["mA/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60) / 0.001,
            FromUnitToBase: static val => (val / 60) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AmperePerMillisecond
        ElectricCurrentGradientUnits.TryAdd("AmperePerMillisecond", new Unit(
            SingularName: "AmperePerMillisecond",
            PluralName: "AmperesPerMillisecond",
            Abbreviations: ["A/ms"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1E3,
            FromUnitToBase: static val => val * 1E3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AmperePerMicrosecond
        ElectricCurrentGradientUnits.TryAdd("AmperePerMicrosecond", new Unit(
            SingularName: "AmperePerMicrosecond",
            PluralName: "AmperesPerMicrosecond",
            Abbreviations: ["A/μs"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1E6,
            FromUnitToBase: static val => val * 1E6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AmperePerNanosecond
        ElectricCurrentGradientUnits.TryAdd("AmperePerNanosecond", new Unit(
            SingularName: "AmperePerNanosecond",
            PluralName: "AmperesPerNanosecond",
            Abbreviations: ["A/ns"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1E9,
            FromUnitToBase: static val => val * 1E9,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricCurrentGradient",
            "AmperePerSecond",
            "In electromagnetism, the current gradient describes how the current changes in time.",
            ElectricCurrentGradientUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = -1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricCurrentGradient", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
