// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricInductance() {
        // Loading ElectricInductance
        var ElectricInductanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Henry
        ElectricInductanceUnits.TryAdd("Henry", new Unit(
            SingularName: "Henry",
            PluralName: "Henries",
            Abbreviations: ["H"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoHenry
        ElectricInductanceUnits.TryAdd("PicoHenry", new Unit(
            SingularName: "PicoHenry",
            PluralName: "PicoHenries",
            Abbreviations: ["pH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoHenry
        ElectricInductanceUnits.TryAdd("NanoHenry", new Unit(
            SingularName: "NanoHenry",
            PluralName: "NanoHenries",
            Abbreviations: ["nH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroHenry
        ElectricInductanceUnits.TryAdd("MicroHenry", new Unit(
            SingularName: "MicroHenry",
            PluralName: "MicroHenries",
            Abbreviations: ["µH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliHenry
        ElectricInductanceUnits.TryAdd("MilliHenry", new Unit(
            SingularName: "MilliHenry",
            PluralName: "MilliHenries",
            Abbreviations: ["mH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricInductance",
            "Henry",
            "Inductance is a property of an electrical conductor which opposes a change in current.",
            ElectricInductanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -2, ["I"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricInductance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
