// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricConductivity() {
        // Loading ElectricConductivity
        var ElectricConductivityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // SiemensPerMeter
        ElectricConductivityUnits.TryAdd("SiemensPerMeter", new Unit(
            SingularName: "SiemensPerMeter",
            PluralName: "SiemensPerMeter",
            Abbreviations: ["S/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SiemensPerInch
        ElectricConductivityUnits.TryAdd("SiemensPerInch", new Unit(
            SingularName: "SiemensPerInch",
            PluralName: "SiemensPerInch",
            Abbreviations: ["S/in"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-2,
            FromUnitToBase: static val => val / 2.54e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SiemensPerFoot
        ElectricConductivityUnits.TryAdd("SiemensPerFoot", new Unit(
            SingularName: "SiemensPerFoot",
            PluralName: "SiemensPerFoot",
            Abbreviations: ["S/ft"],
            Factor: 3.280839895013123,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SiemensPerCentimeter
        ElectricConductivityUnits.TryAdd("SiemensPerCentimeter", new Unit(
            SingularName: "SiemensPerCentimeter",
            PluralName: "SiemensPerCentimeter",
            Abbreviations: ["S/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e2,
            FromUnitToBase: static val => val * 1e2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroSiemensPerCentimeter
        ElectricConductivityUnits.TryAdd("MicroSiemensPerCentimeter", new Unit(
            SingularName: "MicroSiemensPerCentimeter",
            PluralName: "MicroSiemensPerCentimeter",
            Abbreviations: ["µS/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 1E-06,
            FromUnitToBase: static val => (val * 1e2) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliSiemensPerCentimeter
        ElectricConductivityUnits.TryAdd("MilliSiemensPerCentimeter", new Unit(
            SingularName: "MilliSiemensPerCentimeter",
            PluralName: "MilliSiemensPerCentimeter",
            Abbreviations: ["mS/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 0.001,
            FromUnitToBase: static val => (val * 1e2) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricConductivity",
            "SiemensPerMeter",
            "Electrical conductivity or specific conductance is the reciprocal of electrical resistivity, and measures a material's ability to conduct an electric current.",
            ElectricConductivityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -3, ["M"] = -1, ["T"] = 3, ["I"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricConductivity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
