// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricPotentialAc() {
        // Loading ElectricPotentialAc
        var ElectricPotentialAcUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // VoltAc
        ElectricPotentialAcUnits.TryAdd("VoltAc", new Unit(
            SingularName: "VoltAc",
            PluralName: "VoltsAc",
            Abbreviations: ["Vac"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroVoltAc
        ElectricPotentialAcUnits.TryAdd("MicroVoltAc", new Unit(
            SingularName: "MicroVoltAc",
            PluralName: "MicroVoltsAc",
            Abbreviations: ["µVac"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliVoltAc
        ElectricPotentialAcUnits.TryAdd("MilliVoltAc", new Unit(
            SingularName: "MilliVoltAc",
            PluralName: "MilliVoltsAc",
            Abbreviations: ["mVac"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloVoltAc
        ElectricPotentialAcUnits.TryAdd("KiloVoltAc", new Unit(
            SingularName: "KiloVoltAc",
            PluralName: "KiloVoltsAc",
            Abbreviations: ["kVac"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaVoltAc
        ElectricPotentialAcUnits.TryAdd("MegaVoltAc", new Unit(
            SingularName: "MegaVoltAc",
            PluralName: "MegaVoltsAc",
            Abbreviations: ["MVac"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricPotentialAc",
            "VoltAc",
            "The Electric Potential of a system known to use Alternating Current.",
            ElectricPotentialAcUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("ElectricPotentialAc", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
