// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricChargeDensity() {
        // Loading ElectricChargeDensity
        var ElectricChargeDensityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CoulombPerCubicMeter
        ElectricChargeDensityUnits.TryAdd("CoulombPerCubicMeter", new Unit(
            SingularName: "CoulombPerCubicMeter",
            PluralName: "CoulombsPerCubicMeter",
            Abbreviations: ["C/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricChargeDensity",
            "CoulombPerCubicMeter",
            "In electromagnetism, charge density is a measure of the amount of electric charge per volume.",
            ElectricChargeDensityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -3, ["T"] = 1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricChargeDensity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
