// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricSurfaceChargeDensity() {
        // Loading ElectricSurfaceChargeDensity
        var ElectricSurfaceChargeDensityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CoulombPerSquareMeter
        ElectricSurfaceChargeDensityUnits.TryAdd("CoulombPerSquareMeter", new Unit(
            SingularName: "CoulombPerSquareMeter",
            PluralName: "CoulombsPerSquareMeter",
            Abbreviations: ["C/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CoulombPerSquareCentimeter
        ElectricSurfaceChargeDensityUnits.TryAdd("CoulombPerSquareCentimeter", new Unit(
            SingularName: "CoulombPerSquareCentimeter",
            PluralName: "CoulombsPerSquareCentimeter",
            Abbreviations: ["C/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.0e4,
            FromUnitToBase: static val => val * 1.0e4,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CoulombPerSquareInch
        ElectricSurfaceChargeDensityUnits.TryAdd("CoulombPerSquareInch", new Unit(
            SingularName: "CoulombPerSquareInch",
            PluralName: "CoulombsPerSquareInch",
            Abbreviations: ["C/in²"],
            Factor: 1550.0031000062002,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricSurfaceChargeDensity",
            "CoulombPerSquareMeter",
            "In electromagnetism, surface charge density is a measure of the amount of electric charge per surface area.",
            ElectricSurfaceChargeDensityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["T"] = 1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricSurfaceChargeDensity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
