// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricImpedance() {
        // Loading ElectricImpedance
        var ElectricImpedanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Ohm
        ElectricImpedanceUnits.TryAdd("Ohm", new Unit(
            SingularName: "Ohm",
            PluralName: "Ohms",
            Abbreviations: ["Ω"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoOhm
        ElectricImpedanceUnits.TryAdd("NanoOhm", new Unit(
            SingularName: "NanoOhm",
            PluralName: "NanoOhms",
            Abbreviations: ["nΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroOhm
        ElectricImpedanceUnits.TryAdd("MicroOhm", new Unit(
            SingularName: "MicroOhm",
            PluralName: "MicroOhms",
            Abbreviations: ["µΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliOhm
        ElectricImpedanceUnits.TryAdd("MilliOhm", new Unit(
            SingularName: "MilliOhm",
            PluralName: "MilliOhms",
            Abbreviations: ["mΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloOhm
        ElectricImpedanceUnits.TryAdd("KiloOhm", new Unit(
            SingularName: "KiloOhm",
            PluralName: "KiloOhms",
            Abbreviations: ["kΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaOhm
        ElectricImpedanceUnits.TryAdd("MegaOhm", new Unit(
            SingularName: "MegaOhm",
            PluralName: "MegaOhms",
            Abbreviations: ["MΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaOhm
        ElectricImpedanceUnits.TryAdd("GigaOhm", new Unit(
            SingularName: "GigaOhm",
            PluralName: "GigaOhms",
            Abbreviations: ["GΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraOhm
        ElectricImpedanceUnits.TryAdd("TeraOhm", new Unit(
            SingularName: "TeraOhm",
            PluralName: "TeraOhms",
            Abbreviations: ["TΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricImpedance",
            "Ohm",
            "Electric impedance is the opposition to alternating current presented by the combined effect of resistance and reactance in a circuit. It is defined as the inverse of admittance. The SI unit of impedance is the ohm (symbol Ω).",
            ElectricImpedanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -3, ["I"] = -2 },
            "Impedance is a complex number, which is not currently supported by UnitsNet. Please use either ElectricResistance or ElectricReactance instead.",
            false,
            1
        );
        _quantities.Add("ElectricImpedance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
