// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricCapacitance() {
        // Loading ElectricCapacitance
        var ElectricCapacitanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Farad
        ElectricCapacitanceUnits.TryAdd("Farad", new Unit(
            SingularName: "Farad",
            PluralName: "Farads",
            Abbreviations: ["F"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoFarad
        ElectricCapacitanceUnits.TryAdd("PicoFarad", new Unit(
            SingularName: "PicoFarad",
            PluralName: "PicoFarads",
            Abbreviations: ["pF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoFarad
        ElectricCapacitanceUnits.TryAdd("NanoFarad", new Unit(
            SingularName: "NanoFarad",
            PluralName: "NanoFarads",
            Abbreviations: ["nF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroFarad
        ElectricCapacitanceUnits.TryAdd("MicroFarad", new Unit(
            SingularName: "MicroFarad",
            PluralName: "MicroFarads",
            Abbreviations: ["µF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliFarad
        ElectricCapacitanceUnits.TryAdd("MilliFarad", new Unit(
            SingularName: "MilliFarad",
            PluralName: "MilliFarads",
            Abbreviations: ["mF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloFarad
        ElectricCapacitanceUnits.TryAdd("KiloFarad", new Unit(
            SingularName: "KiloFarad",
            PluralName: "KiloFarads",
            Abbreviations: ["kF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaFarad
        ElectricCapacitanceUnits.TryAdd("MegaFarad", new Unit(
            SingularName: "MegaFarad",
            PluralName: "MegaFarads",
            Abbreviations: ["MF"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricCapacitance",
            "Farad",
            "Capacitance is the capacity of a material object or device to store electric charge.",
            ElectricCapacitanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = -1, ["T"] = 4, ["I"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricCapacitance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
