// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadElectricResistance() {
        // Loading ElectricResistance
        var ElectricResistanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Ohm
        ElectricResistanceUnits.TryAdd("Ohm", new Unit(
            SingularName: "Ohm",
            PluralName: "Ohms",
            Abbreviations: ["Ω"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoOhm
        ElectricResistanceUnits.TryAdd("NanoOhm", new Unit(
            SingularName: "NanoOhm",
            PluralName: "NanoOhms",
            Abbreviations: ["nΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroOhm
        ElectricResistanceUnits.TryAdd("MicroOhm", new Unit(
            SingularName: "MicroOhm",
            PluralName: "MicroOhms",
            Abbreviations: ["µΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliOhm
        ElectricResistanceUnits.TryAdd("MilliOhm", new Unit(
            SingularName: "MilliOhm",
            PluralName: "MilliOhms",
            Abbreviations: ["mΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloOhm
        ElectricResistanceUnits.TryAdd("KiloOhm", new Unit(
            SingularName: "KiloOhm",
            PluralName: "KiloOhms",
            Abbreviations: ["kΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaOhm
        ElectricResistanceUnits.TryAdd("MegaOhm", new Unit(
            SingularName: "MegaOhm",
            PluralName: "MegaOhms",
            Abbreviations: ["MΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaOhm
        ElectricResistanceUnits.TryAdd("GigaOhm", new Unit(
            SingularName: "GigaOhm",
            PluralName: "GigaOhms",
            Abbreviations: ["GΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraOhm
        ElectricResistanceUnits.TryAdd("TeraOhm", new Unit(
            SingularName: "TeraOhm",
            PluralName: "TeraOhms",
            Abbreviations: ["TΩ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ElectricResistance",
            "Ohm",
            "The electrical resistance of an object is a measure of its opposition to the flow of electric current. Along with reactance, it is one of two elements of impedance. Its reciprocal quantity is electrical conductance.",
            ElectricResistanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -3, ["I"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("ElectricResistance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
