// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadEnergyDensity() {
        // Loading EnergyDensity
        var EnergyDensityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // JoulePerCubicMeter
        EnergyDensityUnits.TryAdd("JoulePerCubicMeter", new Unit(
            SingularName: "JoulePerCubicMeter",
            PluralName: "JoulesPerCubicMeter",
            Abbreviations: ["J/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerCubicMeter
        EnergyDensityUnits.TryAdd("KiloJoulePerCubicMeter", new Unit(
            SingularName: "KiloJoulePerCubicMeter",
            PluralName: "KiloJoulesPerCubicMeter",
            Abbreviations: ["kJ/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerCubicMeter
        EnergyDensityUnits.TryAdd("MegaJoulePerCubicMeter", new Unit(
            SingularName: "MegaJoulePerCubicMeter",
            PluralName: "MegaJoulesPerCubicMeter",
            Abbreviations: ["MJ/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaJoulePerCubicMeter
        EnergyDensityUnits.TryAdd("GigaJoulePerCubicMeter", new Unit(
            SingularName: "GigaJoulePerCubicMeter",
            PluralName: "GigaJoulesPerCubicMeter",
            Abbreviations: ["GJ/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraJoulePerCubicMeter
        EnergyDensityUnits.TryAdd("TeraJoulePerCubicMeter", new Unit(
            SingularName: "TeraJoulePerCubicMeter",
            PluralName: "TeraJoulesPerCubicMeter",
            Abbreviations: ["TJ/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaJoulePerCubicMeter
        EnergyDensityUnits.TryAdd("PetaJoulePerCubicMeter", new Unit(
            SingularName: "PetaJoulePerCubicMeter",
            PluralName: "PetaJoulesPerCubicMeter",
            Abbreviations: ["PJ/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000000,
            FromUnitToBase: static val => (val) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("WattHourPerCubicMeter", new Unit(
            SingularName: "WattHourPerCubicMeter",
            PluralName: "WattHoursPerCubicMeter",
            Abbreviations: ["Wh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 3.6e+3,
            FromUnitToBase: static val => val * 3.6e+3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("KiloWattHourPerCubicMeter", new Unit(
            SingularName: "KiloWattHourPerCubicMeter",
            PluralName: "KiloWattHoursPerCubicMeter",
            Abbreviations: ["kWh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e+3) / 1000,
            FromUnitToBase: static val => (val * 3.6e+3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("MegaWattHourPerCubicMeter", new Unit(
            SingularName: "MegaWattHourPerCubicMeter",
            PluralName: "MegaWattHoursPerCubicMeter",
            Abbreviations: ["MWh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e+3) / 1000000,
            FromUnitToBase: static val => (val * 3.6e+3) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("GigaWattHourPerCubicMeter", new Unit(
            SingularName: "GigaWattHourPerCubicMeter",
            PluralName: "GigaWattHoursPerCubicMeter",
            Abbreviations: ["GWh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e+3) / 1000000000,
            FromUnitToBase: static val => (val * 3.6e+3) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("TeraWattHourPerCubicMeter", new Unit(
            SingularName: "TeraWattHourPerCubicMeter",
            PluralName: "TeraWattHoursPerCubicMeter",
            Abbreviations: ["TWh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e+3) / 1000000000000,
            FromUnitToBase: static val => (val * 3.6e+3) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaWattHourPerCubicMeter
        EnergyDensityUnits.TryAdd("PetaWattHourPerCubicMeter", new Unit(
            SingularName: "PetaWattHourPerCubicMeter",
            PluralName: "PetaWattHoursPerCubicMeter",
            Abbreviations: ["PWh/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e+3) / 1000000000000000,
            FromUnitToBase: static val => (val * 3.6e+3) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "EnergyDensity",
            "JoulePerCubicMeter",
            "",
            EnergyDensityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["L"] = -1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("EnergyDensity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
