// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadEnergy() {
        // Loading Energy
        var EnergyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Joule
        EnergyUnits.TryAdd("Joule", new Unit(
            SingularName: "Joule",
            PluralName: "Joules",
            Abbreviations: ["J"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoJoule
        EnergyUnits.TryAdd("NanoJoule", new Unit(
            SingularName: "NanoJoule",
            PluralName: "NanoJoules",
            Abbreviations: ["nJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroJoule
        EnergyUnits.TryAdd("MicroJoule", new Unit(
            SingularName: "MicroJoule",
            PluralName: "MicroJoules",
            Abbreviations: ["µJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliJoule
        EnergyUnits.TryAdd("MilliJoule", new Unit(
            SingularName: "MilliJoule",
            PluralName: "MilliJoules",
            Abbreviations: ["mJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoule
        EnergyUnits.TryAdd("KiloJoule", new Unit(
            SingularName: "KiloJoule",
            PluralName: "KiloJoules",
            Abbreviations: ["kJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoule
        EnergyUnits.TryAdd("MegaJoule", new Unit(
            SingularName: "MegaJoule",
            PluralName: "MegaJoules",
            Abbreviations: ["MJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaJoule
        EnergyUnits.TryAdd("GigaJoule", new Unit(
            SingularName: "GigaJoule",
            PluralName: "GigaJoules",
            Abbreviations: ["GJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraJoule
        EnergyUnits.TryAdd("TeraJoule", new Unit(
            SingularName: "TeraJoule",
            PluralName: "TeraJoules",
            Abbreviations: ["TJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaJoule
        EnergyUnits.TryAdd("PetaJoule", new Unit(
            SingularName: "PetaJoule",
            PluralName: "PetaJoules",
            Abbreviations: ["PJ"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000000,
            FromUnitToBase: static val => (val) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Calorie
        EnergyUnits.TryAdd("Calorie", new Unit(
            SingularName: "Calorie",
            PluralName: "Calories",
            Abbreviations: ["cal"],
            Factor: 4.184,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCalorie
        EnergyUnits.TryAdd("KiloCalorie", new Unit(
            SingularName: "KiloCalorie",
            PluralName: "KiloCalories",
            Abbreviations: ["kcal"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.184) / 1000,
            FromUnitToBase: static val => (val * 4.184) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaCalorie
        EnergyUnits.TryAdd("MegaCalorie", new Unit(
            SingularName: "MegaCalorie",
            PluralName: "MegaCalories",
            Abbreviations: ["Mcal"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.184) / 1000000,
            FromUnitToBase: static val => (val * 4.184) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BritishThermalUnit
        EnergyUnits.TryAdd("BritishThermalUnit", new Unit(
            SingularName: "BritishThermalUnit",
            PluralName: "BritishThermalUnits",
            Abbreviations: ["BTU"],
            Factor: 1055.05585262,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloBritishThermalUnit
        EnergyUnits.TryAdd("KiloBritishThermalUnit", new Unit(
            SingularName: "KiloBritishThermalUnit",
            PluralName: "KiloBritishThermalUnits",
            Abbreviations: ["kBTU"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1055.05585262) / 1000,
            FromUnitToBase: static val => (val * 1055.05585262) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaBritishThermalUnit
        EnergyUnits.TryAdd("MegaBritishThermalUnit", new Unit(
            SingularName: "MegaBritishThermalUnit",
            PluralName: "MegaBritishThermalUnits",
            Abbreviations: ["MBTU"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1055.05585262) / 1000000,
            FromUnitToBase: static val => (val * 1055.05585262) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaBritishThermalUnit
        EnergyUnits.TryAdd("GigaBritishThermalUnit", new Unit(
            SingularName: "GigaBritishThermalUnit",
            PluralName: "GigaBritishThermalUnits",
            Abbreviations: ["GBTU"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1055.05585262) / 1000000000,
            FromUnitToBase: static val => (val * 1055.05585262) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ElectronVolt
        EnergyUnits.TryAdd("ElectronVolt", new Unit(
            SingularName: "ElectronVolt",
            PluralName: "ElectronVolts",
            Abbreviations: ["eV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.602176634e-19,
            FromUnitToBase: static val => val * 1.602176634e-19,
            Remarks: "https://en.wikipedia.org/wiki/Electronvolt",
            ObsoleteText: ""
        ));
        // KiloElectronVolt
        EnergyUnits.TryAdd("KiloElectronVolt", new Unit(
            SingularName: "KiloElectronVolt",
            PluralName: "KiloElectronVolts",
            Abbreviations: ["keV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.602176634e-19) / 1000,
            FromUnitToBase: static val => (val * 1.602176634e-19) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaElectronVolt
        EnergyUnits.TryAdd("MegaElectronVolt", new Unit(
            SingularName: "MegaElectronVolt",
            PluralName: "MegaElectronVolts",
            Abbreviations: ["MeV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.602176634e-19) / 1000000,
            FromUnitToBase: static val => (val * 1.602176634e-19) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaElectronVolt
        EnergyUnits.TryAdd("GigaElectronVolt", new Unit(
            SingularName: "GigaElectronVolt",
            PluralName: "GigaElectronVolts",
            Abbreviations: ["GeV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.602176634e-19) / 1000000000,
            FromUnitToBase: static val => (val * 1.602176634e-19) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraElectronVolt
        EnergyUnits.TryAdd("TeraElectronVolt", new Unit(
            SingularName: "TeraElectronVolt",
            PluralName: "TeraElectronVolts",
            Abbreviations: ["TeV"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.602176634e-19) / 1000000000000,
            FromUnitToBase: static val => (val * 1.602176634e-19) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // FootPound
        EnergyUnits.TryAdd("FootPound", new Unit(
            SingularName: "FootPound",
            PluralName: "FootPounds",
            Abbreviations: ["ft·lb"],
            Factor: 1.3558179483314003,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Pound-foot_(torque)",
            ObsoleteText: ""
        ));
        // Erg
        EnergyUnits.TryAdd("Erg", new Unit(
            SingularName: "Erg",
            PluralName: "Ergs",
            Abbreviations: ["erg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-7,
            FromUnitToBase: static val => val * 1e-7,
            Remarks: "https://en.wikipedia.org/wiki/Erg",
            ObsoleteText: ""
        ));
        // WattHour
        EnergyUnits.TryAdd("WattHour", new Unit(
            SingularName: "WattHour",
            PluralName: "WattHours",
            Abbreviations: ["Wh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 3600d,
            FromUnitToBase: static val => val * 3600d,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattHour
        EnergyUnits.TryAdd("KiloWattHour", new Unit(
            SingularName: "KiloWattHour",
            PluralName: "KiloWattHours",
            Abbreviations: ["kWh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600d) / 1000,
            FromUnitToBase: static val => (val * 3600d) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattHour
        EnergyUnits.TryAdd("MegaWattHour", new Unit(
            SingularName: "MegaWattHour",
            PluralName: "MegaWattHours",
            Abbreviations: ["MWh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600d) / 1000000,
            FromUnitToBase: static val => (val * 3600d) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattHour
        EnergyUnits.TryAdd("GigaWattHour", new Unit(
            SingularName: "GigaWattHour",
            PluralName: "GigaWattHours",
            Abbreviations: ["GWh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600d) / 1000000000,
            FromUnitToBase: static val => (val * 3600d) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattHour
        EnergyUnits.TryAdd("TeraWattHour", new Unit(
            SingularName: "TeraWattHour",
            PluralName: "TeraWattHours",
            Abbreviations: ["TWh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3600d) / 1000000000000,
            FromUnitToBase: static val => (val * 3600d) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattDay
        EnergyUnits.TryAdd("WattDay", new Unit(
            SingularName: "WattDay",
            PluralName: "WattDays",
            Abbreviations: ["Wd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (24 * 3600d),
            FromUnitToBase: static val => val * 24 * 3600d,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattDay
        EnergyUnits.TryAdd("KiloWattDay", new Unit(
            SingularName: "KiloWattDay",
            PluralName: "KiloWattDays",
            Abbreviations: ["kWd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3600d)) / 1000,
            FromUnitToBase: static val => (val * 24 * 3600d) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattDay
        EnergyUnits.TryAdd("MegaWattDay", new Unit(
            SingularName: "MegaWattDay",
            PluralName: "MegaWattDays",
            Abbreviations: ["MWd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3600d)) / 1000000,
            FromUnitToBase: static val => (val * 24 * 3600d) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattDay
        EnergyUnits.TryAdd("GigaWattDay", new Unit(
            SingularName: "GigaWattDay",
            PluralName: "GigaWattDays",
            Abbreviations: ["GWd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3600d)) / 1000000000,
            FromUnitToBase: static val => (val * 24 * 3600d) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattDay
        EnergyUnits.TryAdd("TeraWattDay", new Unit(
            SingularName: "TeraWattDay",
            PluralName: "TeraWattDays",
            Abbreviations: ["TWd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3600d)) / 1000000000000,
            FromUnitToBase: static val => (val * 24 * 3600d) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ThermEc
        EnergyUnits.TryAdd("ThermEc", new Unit(
            SingularName: "ThermEc",
            PluralName: "ThermsEc",
            Abbreviations: ["th (E.C.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.05505585262e8,
            FromUnitToBase: static val => val * 1.05505585262e8,
            Remarks: "https://en.wikipedia.org/wiki/Therm",
            ObsoleteText: ""
        ));
        // DecaThermEc
        EnergyUnits.TryAdd("DecaThermEc", new Unit(
            SingularName: "DecaThermEc",
            PluralName: "DecaThermsEc",
            Abbreviations: ["Dth (E.C.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.05505585262e8) / 10,
            FromUnitToBase: static val => (val * 1.05505585262e8) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ThermUs
        EnergyUnits.TryAdd("ThermUs", new Unit(
            SingularName: "ThermUs",
            PluralName: "ThermsUs",
            Abbreviations: ["th (U.S.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.054804e8,
            FromUnitToBase: static val => val * 1.054804e8,
            Remarks: "https://en.wikipedia.org/wiki/Therm",
            ObsoleteText: ""
        ));
        // DecaThermUs
        EnergyUnits.TryAdd("DecaThermUs", new Unit(
            SingularName: "DecaThermUs",
            PluralName: "DecaThermsUs",
            Abbreviations: ["Dth (U.S.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.054804e8) / 10,
            FromUnitToBase: static val => (val * 1.054804e8) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ThermImperial
        EnergyUnits.TryAdd("ThermImperial", new Unit(
            SingularName: "ThermImperial",
            PluralName: "ThermsImperial",
            Abbreviations: ["th (imp.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.05505585257348e8,
            FromUnitToBase: static val => val * 1.05505585257348e8,
            Remarks: "https://en.wikipedia.org/wiki/Therm",
            ObsoleteText: ""
        ));
        // DecaThermImperial
        EnergyUnits.TryAdd("DecaThermImperial", new Unit(
            SingularName: "DecaThermImperial",
            PluralName: "DecaThermsImperial",
            Abbreviations: ["Dth (imp.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1.05505585257348e8) / 10,
            FromUnitToBase: static val => (val * 1.05505585257348e8) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HorsepowerHour
        EnergyUnits.TryAdd("HorsepowerHour", new Unit(
            SingularName: "HorsepowerHour",
            PluralName: "HorsepowerHours",
            Abbreviations: ["hp·h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (76.0402249 * 9.80665 * 3600),
            FromUnitToBase: static val => val * 76.0402249 * 9.80665 * 3600,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower-hour",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Energy",
            "Joule",
            "The joule, symbol J, is a derived unit of energy, work, or amount of heat in the International System of Units. It is equal to the energy transferred (or work done) when applying a force of one newton through a distance of one metre (1 newton metre or N·m), or in passing an electric current of one ampere through a resistance of one ohm for one second. Many other units of energy are included. Please do not confuse this definition of the calorie with the one colloquially used by the food industry, the large calorie, which is equivalent to 1 kcal. Thermochemical definition of the calorie is used. For BTU, the IT definition is used.",
            EnergyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("Energy", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
