// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadEntropy() {
        // Loading Entropy
        var EntropyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // JoulePerKelvin
        EntropyUnits.TryAdd("JoulePerKelvin", new Unit(
            SingularName: "JoulePerKelvin",
            PluralName: "JoulesPerKelvin",
            Abbreviations: ["J/K"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerKelvin
        EntropyUnits.TryAdd("KiloJoulePerKelvin", new Unit(
            SingularName: "KiloJoulePerKelvin",
            PluralName: "KiloJoulesPerKelvin",
            Abbreviations: ["kJ/K"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerKelvin
        EntropyUnits.TryAdd("MegaJoulePerKelvin", new Unit(
            SingularName: "MegaJoulePerKelvin",
            PluralName: "MegaJoulesPerKelvin",
            Abbreviations: ["MJ/K"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CaloriePerKelvin
        EntropyUnits.TryAdd("CaloriePerKelvin", new Unit(
            SingularName: "CaloriePerKelvin",
            PluralName: "CaloriesPerKelvin",
            Abbreviations: ["cal/K"],
            Factor: 4.184,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCaloriePerKelvin
        EntropyUnits.TryAdd("KiloCaloriePerKelvin", new Unit(
            SingularName: "KiloCaloriePerKelvin",
            PluralName: "KiloCaloriesPerKelvin",
            Abbreviations: ["kcal/K"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.184) / 1000,
            FromUnitToBase: static val => (val * 4.184) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // JoulePerDegreeCelsius
        EntropyUnits.TryAdd("JoulePerDegreeCelsius", new Unit(
            SingularName: "JoulePerDegreeCelsius",
            PluralName: "JoulesPerDegreeCelsius",
            Abbreviations: ["J/°C"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerDegreeCelsius
        EntropyUnits.TryAdd("KiloJoulePerDegreeCelsius", new Unit(
            SingularName: "KiloJoulePerDegreeCelsius",
            PluralName: "KiloJoulesPerDegreeCelsius",
            Abbreviations: ["kJ/°C"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Entropy",
            "JoulePerKelvin",
            "Entropy is an important concept in the branch of science known as thermodynamics. The idea of \"irreversibility\" is central to the understanding of entropy.  It is often said that entropy is an expression of the disorder, or randomness of a system, or of our lack of information about it. Entropy is an extensive property. It has the dimension of energy divided by temperature, which has a unit of joules per kelvin (J/K) in the International System of Units",
            EntropyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -2, ["Θ"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("Entropy", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
