// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadFluidResistance() {
        // Loading FluidResistance
        var FluidResistanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // PascalSecondPerLiter
        FluidResistanceUnits.TryAdd("PascalSecondPerLiter", new Unit(
            SingularName: "PascalSecondPerLiter",
            PluralName: "PascalSecondsPerLiter",
            Abbreviations: ["Pa·s/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e3,
            FromUnitToBase: static val => val * 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalMinutePerLiter
        FluidResistanceUnits.TryAdd("PascalMinutePerLiter", new Unit(
            SingularName: "PascalMinutePerLiter",
            PluralName: "PascalMinutesPerLiter",
            Abbreviations: ["Pa·min/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6e4,
            FromUnitToBase: static val => val * 6e4,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalSecondPerMilliliter
        FluidResistanceUnits.TryAdd("PascalSecondPerMilliliter", new Unit(
            SingularName: "PascalSecondPerMilliliter",
            PluralName: "PascalSecondsPerMilliliter",
            Abbreviations: ["Pa·s/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e6,
            FromUnitToBase: static val => val * 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalMinutePerMilliliter
        FluidResistanceUnits.TryAdd("PascalMinutePerMilliliter", new Unit(
            SingularName: "PascalMinutePerMilliliter",
            PluralName: "PascalMinutesPerMilliliter",
            Abbreviations: ["Pa·min/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6e7,
            FromUnitToBase: static val => val * 6e7,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalSecondPerCubicMeter
        FluidResistanceUnits.TryAdd("PascalSecondPerCubicMeter", new Unit(
            SingularName: "PascalSecondPerCubicMeter",
            PluralName: "PascalSecondsPerCubicMeter",
            Abbreviations: ["Pa·s/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPascalSecondPerCubicMeter
        FluidResistanceUnits.TryAdd("MegaPascalSecondPerCubicMeter", new Unit(
            SingularName: "MegaPascalSecondPerCubicMeter",
            PluralName: "MegaPascalSecondsPerCubicMeter",
            Abbreviations: ["MPa·s/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalMinutePerCubicMeter
        FluidResistanceUnits.TryAdd("PascalMinutePerCubicMeter", new Unit(
            SingularName: "PascalMinutePerCubicMeter",
            PluralName: "PascalMinutesPerCubicMeter",
            Abbreviations: ["Pa·min/m³"],
            Factor: 60,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalSecondPerCubicCentimeter
        FluidResistanceUnits.TryAdd("PascalSecondPerCubicCentimeter", new Unit(
            SingularName: "PascalSecondPerCubicCentimeter",
            PluralName: "PascalSecondsPerCubicCentimeter",
            Abbreviations: ["Pa·s/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e6,
            FromUnitToBase: static val => val * 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalMinutePerCubicCentimeter
        FluidResistanceUnits.TryAdd("PascalMinutePerCubicCentimeter", new Unit(
            SingularName: "PascalMinutePerCubicCentimeter",
            PluralName: "PascalMinutesPerCubicCentimeter",
            Abbreviations: ["Pa·min/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6e7,
            FromUnitToBase: static val => val * 6e7,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DyneSecondPerCentimeterToTheFifth
        FluidResistanceUnits.TryAdd("DyneSecondPerCentimeterToTheFifth", new Unit(
            SingularName: "DyneSecondPerCentimeterToTheFifth",
            PluralName: "DyneSecondsPerCentimeterToTheFifth",
            Abbreviations: ["dyn·s/cm⁵", "dyn·s·cm⁻⁵"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5,
            FromUnitToBase: static val => val * 1e5,
            Remarks: "https://en.wikipedia.org/wiki/Vascular_resistance",
            ObsoleteText: ""
        ));
        // MillimeterMercurySecondPerLiter
        FluidResistanceUnits.TryAdd("MillimeterMercurySecondPerLiter", new Unit(
            SingularName: "MillimeterMercurySecondPerLiter",
            PluralName: "MillimeterMercurySecondsPerLiter",
            Abbreviations: ["mmHg·s/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.33322368e5,
            FromUnitToBase: static val => val * 1.33322368e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercuryMinutePerLiter
        FluidResistanceUnits.TryAdd("MillimeterMercuryMinutePerLiter", new Unit(
            SingularName: "MillimeterMercuryMinutePerLiter",
            PluralName: "MillimeterMercuryMinutesPerLiter",
            Abbreviations: ["mmHg·min/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.99934208e6,
            FromUnitToBase: static val => val * 7.99934208e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercurySecondPerMilliliter
        FluidResistanceUnits.TryAdd("MillimeterMercurySecondPerMilliliter", new Unit(
            SingularName: "MillimeterMercurySecondPerMilliliter",
            PluralName: "MillimeterMercurySecondsPerMilliliter",
            Abbreviations: ["mmHg·s/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.33322368e8,
            FromUnitToBase: static val => val * 1.33322368e8,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercuryMinutePerMilliliter
        FluidResistanceUnits.TryAdd("MillimeterMercuryMinutePerMilliliter", new Unit(
            SingularName: "MillimeterMercuryMinutePerMilliliter",
            PluralName: "MillimeterMercuryMinutesPerMilliliter",
            Abbreviations: ["mmHg·min/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.99934208e9,
            FromUnitToBase: static val => val * 7.99934208e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercurySecondPerCubicCentimeter
        FluidResistanceUnits.TryAdd("MillimeterMercurySecondPerCubicCentimeter", new Unit(
            SingularName: "MillimeterMercurySecondPerCubicCentimeter",
            PluralName: "MillimeterMercurySecondsPerCubicCentimeter",
            Abbreviations: ["mmHg·s/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1.33322368e8,
            FromUnitToBase: static val => val * 1.33322368e8,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercuryMinutePerCubicCentimeter
        FluidResistanceUnits.TryAdd("MillimeterMercuryMinutePerCubicCentimeter", new Unit(
            SingularName: "MillimeterMercuryMinutePerCubicCentimeter",
            PluralName: "MillimeterMercuryMinutesPerCubicCentimeter",
            Abbreviations: ["mmHg·min/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.99934208e9,
            FromUnitToBase: static val => val * 7.99934208e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercurySecondPerCubicMeter
        FluidResistanceUnits.TryAdd("MillimeterMercurySecondPerCubicMeter", new Unit(
            SingularName: "MillimeterMercurySecondPerCubicMeter",
            PluralName: "MillimeterMercurySecondsPerCubicMeter",
            Abbreviations: ["mmHg·s/m³"],
            Factor: 133.322368,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterMercuryMinutePerCubicMeter
        FluidResistanceUnits.TryAdd("MillimeterMercuryMinutePerCubicMeter", new Unit(
            SingularName: "MillimeterMercuryMinutePerCubicMeter",
            PluralName: "MillimeterMercuryMinutesPerCubicMeter",
            Abbreviations: ["mmHg·min/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.99934208e3,
            FromUnitToBase: static val => val * 7.99934208e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WoodUnit
        FluidResistanceUnits.TryAdd("WoodUnit", new Unit(
            SingularName: "WoodUnit",
            PluralName: "WoodUnits",
            Abbreviations: ["WU", "HRU"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.99934208e6,
            FromUnitToBase: static val => val * 7.99934208e6,
            Remarks: "https://en.wikipedia.org/wiki/Vascular_resistance",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "FluidResistance",
            "PascalSecondPerCubicMeter",
            "Fluid Resistance is a force acting opposite to the relative motion of any object moving with respect to a surrounding fluid. Fluid Resistance is sometimes referred to as drag or fluid friction.",
            FluidResistanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["L"] = -4, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("FluidResistance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
