// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadForcePerLength() {
        // Loading ForcePerLength
        var ForcePerLengthUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // NewtonPerMeter
        ForcePerLengthUnits.TryAdd("NewtonPerMeter", new Unit(
            SingularName: "NewtonPerMeter",
            PluralName: "NewtonsPerMeter",
            Abbreviations: ["N/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoNewtonPerMeter
        ForcePerLengthUnits.TryAdd("NanoNewtonPerMeter", new Unit(
            SingularName: "NanoNewtonPerMeter",
            PluralName: "NanoNewtonsPerMeter",
            Abbreviations: ["nN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroNewtonPerMeter
        ForcePerLengthUnits.TryAdd("MicroNewtonPerMeter", new Unit(
            SingularName: "MicroNewtonPerMeter",
            PluralName: "MicroNewtonsPerMeter",
            Abbreviations: ["µN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliNewtonPerMeter
        ForcePerLengthUnits.TryAdd("MilliNewtonPerMeter", new Unit(
            SingularName: "MilliNewtonPerMeter",
            PluralName: "MilliNewtonsPerMeter",
            Abbreviations: ["mN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiNewtonPerMeter
        ForcePerLengthUnits.TryAdd("CentiNewtonPerMeter", new Unit(
            SingularName: "CentiNewtonPerMeter",
            PluralName: "CentiNewtonsPerMeter",
            Abbreviations: ["cN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciNewtonPerMeter
        ForcePerLengthUnits.TryAdd("DeciNewtonPerMeter", new Unit(
            SingularName: "DeciNewtonPerMeter",
            PluralName: "DeciNewtonsPerMeter",
            Abbreviations: ["dN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaNewtonPerMeter
        ForcePerLengthUnits.TryAdd("DecaNewtonPerMeter", new Unit(
            SingularName: "DecaNewtonPerMeter",
            PluralName: "DecaNewtonsPerMeter",
            Abbreviations: ["daN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 10,
            FromUnitToBase: static val => (val) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerMeter
        ForcePerLengthUnits.TryAdd("KiloNewtonPerMeter", new Unit(
            SingularName: "KiloNewtonPerMeter",
            PluralName: "KiloNewtonsPerMeter",
            Abbreviations: ["kN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonPerMeter
        ForcePerLengthUnits.TryAdd("MegaNewtonPerMeter", new Unit(
            SingularName: "MegaNewtonPerMeter",
            PluralName: "MegaNewtonsPerMeter",
            Abbreviations: ["MN/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("NewtonPerCentimeter", new Unit(
            SingularName: "NewtonPerCentimeter",
            PluralName: "NewtonsPerCentimeter",
            Abbreviations: ["N/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e2,
            FromUnitToBase: static val => val * 1e2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("NanoNewtonPerCentimeter", new Unit(
            SingularName: "NanoNewtonPerCentimeter",
            PluralName: "NanoNewtonsPerCentimeter",
            Abbreviations: ["nN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 1E-09,
            FromUnitToBase: static val => (val * 1e2) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("MicroNewtonPerCentimeter", new Unit(
            SingularName: "MicroNewtonPerCentimeter",
            PluralName: "MicroNewtonsPerCentimeter",
            Abbreviations: ["µN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 1E-06,
            FromUnitToBase: static val => (val * 1e2) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("MilliNewtonPerCentimeter", new Unit(
            SingularName: "MilliNewtonPerCentimeter",
            PluralName: "MilliNewtonsPerCentimeter",
            Abbreviations: ["mN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 0.001,
            FromUnitToBase: static val => (val * 1e2) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("CentiNewtonPerCentimeter", new Unit(
            SingularName: "CentiNewtonPerCentimeter",
            PluralName: "CentiNewtonsPerCentimeter",
            Abbreviations: ["cN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 0.01,
            FromUnitToBase: static val => (val * 1e2) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("DeciNewtonPerCentimeter", new Unit(
            SingularName: "DeciNewtonPerCentimeter",
            PluralName: "DeciNewtonsPerCentimeter",
            Abbreviations: ["dN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 0.1,
            FromUnitToBase: static val => (val * 1e2) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("DecaNewtonPerCentimeter", new Unit(
            SingularName: "DecaNewtonPerCentimeter",
            PluralName: "DecaNewtonsPerCentimeter",
            Abbreviations: ["daN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 10,
            FromUnitToBase: static val => (val * 1e2) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("KiloNewtonPerCentimeter", new Unit(
            SingularName: "KiloNewtonPerCentimeter",
            PluralName: "KiloNewtonsPerCentimeter",
            Abbreviations: ["kN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 1000,
            FromUnitToBase: static val => (val * 1e2) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonPerCentimeter
        ForcePerLengthUnits.TryAdd("MegaNewtonPerCentimeter", new Unit(
            SingularName: "MegaNewtonPerCentimeter",
            PluralName: "MegaNewtonsPerCentimeter",
            Abbreviations: ["MN/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e2) / 1000000,
            FromUnitToBase: static val => (val * 1e2) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("NewtonPerMillimeter", new Unit(
            SingularName: "NewtonPerMillimeter",
            PluralName: "NewtonsPerMillimeter",
            Abbreviations: ["N/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e3,
            FromUnitToBase: static val => val * 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("NanoNewtonPerMillimeter", new Unit(
            SingularName: "NanoNewtonPerMillimeter",
            PluralName: "NanoNewtonsPerMillimeter",
            Abbreviations: ["nN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 1E-09,
            FromUnitToBase: static val => (val * 1e3) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("MicroNewtonPerMillimeter", new Unit(
            SingularName: "MicroNewtonPerMillimeter",
            PluralName: "MicroNewtonsPerMillimeter",
            Abbreviations: ["µN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 1E-06,
            FromUnitToBase: static val => (val * 1e3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("MilliNewtonPerMillimeter", new Unit(
            SingularName: "MilliNewtonPerMillimeter",
            PluralName: "MilliNewtonsPerMillimeter",
            Abbreviations: ["mN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 0.001,
            FromUnitToBase: static val => (val * 1e3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("CentiNewtonPerMillimeter", new Unit(
            SingularName: "CentiNewtonPerMillimeter",
            PluralName: "CentiNewtonsPerMillimeter",
            Abbreviations: ["cN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 0.01,
            FromUnitToBase: static val => (val * 1e3) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("DeciNewtonPerMillimeter", new Unit(
            SingularName: "DeciNewtonPerMillimeter",
            PluralName: "DeciNewtonsPerMillimeter",
            Abbreviations: ["dN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 0.1,
            FromUnitToBase: static val => (val * 1e3) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("DecaNewtonPerMillimeter", new Unit(
            SingularName: "DecaNewtonPerMillimeter",
            PluralName: "DecaNewtonsPerMillimeter",
            Abbreviations: ["daN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 10,
            FromUnitToBase: static val => (val * 1e3) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("KiloNewtonPerMillimeter", new Unit(
            SingularName: "KiloNewtonPerMillimeter",
            PluralName: "KiloNewtonsPerMillimeter",
            Abbreviations: ["kN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 1000,
            FromUnitToBase: static val => (val * 1e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonPerMillimeter
        ForcePerLengthUnits.TryAdd("MegaNewtonPerMillimeter", new Unit(
            SingularName: "MegaNewtonPerMillimeter",
            PluralName: "MegaNewtonsPerMillimeter",
            Abbreviations: ["MN/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e3) / 1000000,
            FromUnitToBase: static val => (val * 1e3) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerMeter
        ForcePerLengthUnits.TryAdd("KilogramForcePerMeter", new Unit(
            SingularName: "KilogramForcePerMeter",
            PluralName: "KilogramsForcePerMeter",
            Abbreviations: ["kgf/m"],
            Factor: 9.80665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerCentimeter
        ForcePerLengthUnits.TryAdd("KilogramForcePerCentimeter", new Unit(
            SingularName: "KilogramForcePerCentimeter",
            PluralName: "KilogramsForcePerCentimeter",
            Abbreviations: ["kgf/cm"],
            Factor: 980.665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerMillimeter
        ForcePerLengthUnits.TryAdd("KilogramForcePerMillimeter", new Unit(
            SingularName: "KilogramForcePerMillimeter",
            PluralName: "KilogramsForcePerMillimeter",
            Abbreviations: ["kgf/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e3,
            FromUnitToBase: static val => val * 9.80665e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerMeter
        ForcePerLengthUnits.TryAdd("TonneForcePerMeter", new Unit(
            SingularName: "TonneForcePerMeter",
            PluralName: "TonnesForcePerMeter",
            Abbreviations: ["tf/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e3,
            FromUnitToBase: static val => val * 9.80665e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerCentimeter
        ForcePerLengthUnits.TryAdd("TonneForcePerCentimeter", new Unit(
            SingularName: "TonneForcePerCentimeter",
            PluralName: "TonnesForcePerCentimeter",
            Abbreviations: ["tf/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e5,
            FromUnitToBase: static val => val * 9.80665e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerMillimeter
        ForcePerLengthUnits.TryAdd("TonneForcePerMillimeter", new Unit(
            SingularName: "TonneForcePerMillimeter",
            PluralName: "TonnesForcePerMillimeter",
            Abbreviations: ["tf/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e6,
            FromUnitToBase: static val => val * 9.80665e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerFoot
        ForcePerLengthUnits.TryAdd("PoundForcePerFoot", new Unit(
            SingularName: "PoundForcePerFoot",
            PluralName: "PoundsForcePerFoot",
            Abbreviations: ["lbf/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.3048 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 0.3048,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerInch
        ForcePerLengthUnits.TryAdd("PoundForcePerInch", new Unit(
            SingularName: "PoundForcePerInch",
            PluralName: "PoundsForcePerInch",
            Abbreviations: ["lbf/in"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-2 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 2.54e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerYard
        ForcePerLengthUnits.TryAdd("PoundForcePerYard", new Unit(
            SingularName: "PoundForcePerYard",
            PluralName: "PoundsForcePerYard",
            Abbreviations: ["lbf/yd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.9144 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 0.9144,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilopoundForcePerFoot
        ForcePerLengthUnits.TryAdd("KilopoundForcePerFoot", new Unit(
            SingularName: "KilopoundForcePerFoot",
            PluralName: "KilopoundsForcePerFoot",
            Abbreviations: ["kipf/ft", "kip/ft", "k/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.3048e-3 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 0.3048e-3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilopoundForcePerInch
        ForcePerLengthUnits.TryAdd("KilopoundForcePerInch", new Unit(
            SingularName: "KilopoundForcePerInch",
            PluralName: "KilopoundsForcePerInch",
            Abbreviations: ["kipf/in", "kip/in", "k/in"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-5 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 2.54e-5,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ForcePerLength",
            "NewtonPerMeter",
            "The magnitude of force per unit length.",
            ForcePerLengthUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("ForcePerLength", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
