// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadForce() {
        // Loading Force
        var ForceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Dyn
        ForceUnits.TryAdd("Dyn", new Unit(
            SingularName: "Dyn",
            PluralName: "Dyne",
            Abbreviations: ["dyn"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e5,
            FromUnitToBase: static val => val / 1e5,
            Remarks: "https://en.wikipedia.org/wiki/Dyne#Definition",
            ObsoleteText: ""
        ));
        // KilogramForce
        ForceUnits.TryAdd("KilogramForce", new Unit(
            SingularName: "KilogramForce",
            PluralName: "KilogramsForce",
            Abbreviations: ["kgf"],
            Factor: 9.80665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Kilogram-force",
            ObsoleteText: ""
        ));
        // TonneForce
        ForceUnits.TryAdd("TonneForce", new Unit(
            SingularName: "TonneForce",
            PluralName: "TonnesForce",
            Abbreviations: ["tf", "Ton"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (9.80665 * 1000),
            FromUnitToBase: static val => val * (9.80665 * 1000),
            Remarks: "https://en.wikipedia.org/wiki/Kilogram-force#Related_units",
            ObsoleteText: ""
        ));
        // Newton
        ForceUnits.TryAdd("Newton", new Unit(
            SingularName: "Newton",
            PluralName: "Newtons",
            Abbreviations: ["N"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Newton_(unit)",
            ObsoleteText: ""
        ));
        // MicroNewton
        ForceUnits.TryAdd("MicroNewton", new Unit(
            SingularName: "MicroNewton",
            PluralName: "MicroNewtons",
            Abbreviations: ["µN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliNewton
        ForceUnits.TryAdd("MilliNewton", new Unit(
            SingularName: "MilliNewton",
            PluralName: "MilliNewtons",
            Abbreviations: ["mN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaNewton
        ForceUnits.TryAdd("DecaNewton", new Unit(
            SingularName: "DecaNewton",
            PluralName: "DecaNewtons",
            Abbreviations: ["daN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 10,
            FromUnitToBase: static val => (val) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewton
        ForceUnits.TryAdd("KiloNewton", new Unit(
            SingularName: "KiloNewton",
            PluralName: "KiloNewtons",
            Abbreviations: ["kN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewton
        ForceUnits.TryAdd("MegaNewton", new Unit(
            SingularName: "MegaNewton",
            PluralName: "MegaNewtons",
            Abbreviations: ["MN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Kilopond
        ForceUnits.TryAdd("Kilopond", new Unit(
            SingularName: "Kilopond",
            PluralName: "Kiloponds",
            Abbreviations: ["kp"],
            Factor: 9.80665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Kilogram-force",
            ObsoleteText: ""
        ));
        // Poundal
        ForceUnits.TryAdd("Poundal", new Unit(
            SingularName: "Poundal",
            PluralName: "Poundals",
            Abbreviations: ["pdl"],
            Factor: 0.138254954376,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Poundal",
            ObsoleteText: ""
        ));
        // PoundForce
        ForceUnits.TryAdd("PoundForce", new Unit(
            SingularName: "PoundForce",
            PluralName: "PoundsForce",
            Abbreviations: ["lbf"],
            Factor: 4.4482216152605,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Pound_(force)#Definitions",
            ObsoleteText: ""
        ));
        // KiloPoundForce
        ForceUnits.TryAdd("KiloPoundForce", new Unit(
            SingularName: "KiloPoundForce",
            PluralName: "KiloPoundsForce",
            Abbreviations: ["kipf", "kip", "k"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.4482216152605) / 1000,
            FromUnitToBase: static val => (val * 4.4482216152605) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OunceForce
        ForceUnits.TryAdd("OunceForce", new Unit(
            SingularName: "OunceForce",
            PluralName: "OunceForce",
            Abbreviations: ["ozf"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (4.4482216152605 / 16),
            FromUnitToBase: static val => val * (4.4482216152605 / 16),
            Remarks: "https://en.wikipedia.org/wiki/Ounce#Ounce-force",
            ObsoleteText: ""
        ));
        // ShortTonForce
        ForceUnits.TryAdd("ShortTonForce", new Unit(
            SingularName: "ShortTonForce",
            PluralName: "ShortTonsForce",
            Abbreviations: ["tf (short)", "t (US)f", "short tons-force"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (4.4482216152605 * 2000),
            FromUnitToBase: static val => val * (4.4482216152605 * 2000),
            Remarks: "https://en.wikipedia.org/wiki/Ton-force#Short_ton-force",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Force",
            "Newton",
            "In physics, a force is any influence that causes an object to undergo a certain change, either concerning its movement, direction, or geometrical construction. In other words, a force can cause an object with mass to change its velocity (which includes to begin moving from a state of rest), i.e., to accelerate, or a flexible object to deform, or both. Force can also be described by intuitive concepts such as a push or a pull. A force has both magnitude and direction, making it a vector quantity. It is measured in the SI unit of newtons and represented by the symbol F.",
            ForceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("Force", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
