// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadFrequency() {
        // Loading Frequency
        var FrequencyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Hertz
        FrequencyUnits.TryAdd("Hertz", new Unit(
            SingularName: "Hertz",
            PluralName: "Hertz",
            Abbreviations: ["Hz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroHertz
        FrequencyUnits.TryAdd("MicroHertz", new Unit(
            SingularName: "MicroHertz",
            PluralName: "MicroHertz",
            Abbreviations: ["µHz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliHertz
        FrequencyUnits.TryAdd("MilliHertz", new Unit(
            SingularName: "MilliHertz",
            PluralName: "MilliHertz",
            Abbreviations: ["mHz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloHertz
        FrequencyUnits.TryAdd("KiloHertz", new Unit(
            SingularName: "KiloHertz",
            PluralName: "KiloHertz",
            Abbreviations: ["kHz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaHertz
        FrequencyUnits.TryAdd("MegaHertz", new Unit(
            SingularName: "MegaHertz",
            PluralName: "MegaHertz",
            Abbreviations: ["MHz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaHertz
        FrequencyUnits.TryAdd("GigaHertz", new Unit(
            SingularName: "GigaHertz",
            PluralName: "GigaHertz",
            Abbreviations: ["GHz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraHertz
        FrequencyUnits.TryAdd("TeraHertz", new Unit(
            SingularName: "TeraHertz",
            PluralName: "TeraHertz",
            Abbreviations: ["THz"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // RadianPerSecond
        FrequencyUnits.TryAdd("RadianPerSecond", new Unit(
            SingularName: "RadianPerSecond",
            PluralName: "RadiansPerSecond",
            Abbreviations: ["rad/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (2 * Math.PI),
            FromUnitToBase: static val => val / (2 * Math.PI),
            Remarks: "https://en.wikipedia.org/wiki/Angular_frequency",
            ObsoleteText: ""
        ));
        // CyclePerMinute
        FrequencyUnits.TryAdd("CyclePerMinute", new Unit(
            SingularName: "CyclePerMinute",
            PluralName: "CyclesPerMinute",
            Abbreviations: ["cpm"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CyclePerHour
        FrequencyUnits.TryAdd("CyclePerHour", new Unit(
            SingularName: "CyclePerHour",
            PluralName: "CyclesPerHour",
            Abbreviations: ["cph"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BeatPerMinute
        FrequencyUnits.TryAdd("BeatPerMinute", new Unit(
            SingularName: "BeatPerMinute",
            PluralName: "BeatsPerMinute",
            Abbreviations: ["bpm"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PerSecond
        FrequencyUnits.TryAdd("PerSecond", new Unit(
            SingularName: "PerSecond",
            PluralName: "PerSecond",
            Abbreviations: ["s⁻¹"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Frequency",
            "Hertz",
            "The number of occurrences of a repeating event per unit time.",
            FrequencyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("Frequency", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
