// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadFuelEfficiency() {
        // Loading FuelEfficiency
        var FuelEfficiencyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // LiterPer100Kilometers
        FuelEfficiencyUnits.TryAdd("LiterPer100Kilometers", new Unit(
            SingularName: "LiterPer100Kilometers",
            PluralName: "LitersPer100Kilometers",
            Abbreviations: ["l/100km"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => 100 / val,
            FromUnitToBase: static val => 100 / val,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilePerUsGallon
        FuelEfficiencyUnits.TryAdd("MilePerUsGallon", new Unit(
            SingularName: "MilePerUsGallon",
            PluralName: "MilesPerUsGallon",
            Abbreviations: ["mpg (U.S.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 3.785411784 / 1.609344,
            FromUnitToBase: static val => val * 1.609344 / 3.785411784,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilePerUkGallon
        FuelEfficiencyUnits.TryAdd("MilePerUkGallon", new Unit(
            SingularName: "MilePerUkGallon",
            PluralName: "MilesPerUkGallon",
            Abbreviations: ["mpg (imp.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 4.54609 / 1.609344,
            FromUnitToBase: static val => val * 1.609344 / 4.54609,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilometerPerLiter
        FuelEfficiencyUnits.TryAdd("KilometerPerLiter", new Unit(
            SingularName: "KilometerPerLiter",
            PluralName: "KilometersPerLiter",
            Abbreviations: ["km/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "FuelEfficiency",
            "KilometerPerLiter",
            "In the context of transport, fuel economy is the energy efficiency of a particular vehicle, given as a ratio of distance traveled per unit of fuel consumed. In most countries, using the metric system, fuel economy is stated as \"fuel consumption\" in liters per 100 kilometers (L/100 km) or kilometers per liter (km/L or kmpl). In countries using non-metric system, fuel economy is expressed in miles per gallon (mpg) (imperial galon or US galon).",
            FuelEfficiencyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("FuelEfficiency", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
