// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadHardness() {
        // Loading Hardness
        var HardnessUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // BHN
        HardnessUnits.TryAdd("BHN", new Unit(
            SingularName: "BHN",
            PluralName: "BHN",
            Abbreviations: ["BHN"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Hardness",
            "BHN",
            "",
            HardnessUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("Hardness", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
