// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadInformation() {
        // Loading Information
        var InformationUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Byte
        InformationUnits.TryAdd("Byte", new Unit(
            SingularName: "Byte",
            PluralName: "Bytes",
            Abbreviations: ["B"],
            Factor: 8,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloByte
        InformationUnits.TryAdd("KiloByte", new Unit(
            SingularName: "KiloByte",
            PluralName: "KiloBytes",
            Abbreviations: ["kB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000,
            FromUnitToBase: static val => (val * 8) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaByte
        InformationUnits.TryAdd("MegaByte", new Unit(
            SingularName: "MegaByte",
            PluralName: "MegaBytes",
            Abbreviations: ["MB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000,
            FromUnitToBase: static val => (val * 8) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaByte
        InformationUnits.TryAdd("GigaByte", new Unit(
            SingularName: "GigaByte",
            PluralName: "GigaBytes",
            Abbreviations: ["GB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraByte
        InformationUnits.TryAdd("TeraByte", new Unit(
            SingularName: "TeraByte",
            PluralName: "TeraBytes",
            Abbreviations: ["TB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaByte
        InformationUnits.TryAdd("PetaByte", new Unit(
            SingularName: "PetaByte",
            PluralName: "PetaBytes",
            Abbreviations: ["PB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExaByte
        InformationUnits.TryAdd("ExaByte", new Unit(
            SingularName: "ExaByte",
            PluralName: "ExaBytes",
            Abbreviations: ["EB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1E+18,
            FromUnitToBase: static val => (val * 8) * 1E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KibiByte
        InformationUnits.TryAdd("KibiByte", new Unit(
            SingularName: "KibiByte",
            PluralName: "KibiBytes",
            Abbreviations: ["KiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1024,
            FromUnitToBase: static val => (val * 8) * 1024,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MebiByte
        InformationUnits.TryAdd("MebiByte", new Unit(
            SingularName: "MebiByte",
            PluralName: "MebiBytes",
            Abbreviations: ["MiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1048576,
            FromUnitToBase: static val => (val * 8) * 1048576,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GibiByte
        InformationUnits.TryAdd("GibiByte", new Unit(
            SingularName: "GibiByte",
            PluralName: "GibiBytes",
            Abbreviations: ["GiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1073741824,
            FromUnitToBase: static val => (val * 8) * 1073741824,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TebiByte
        InformationUnits.TryAdd("TebiByte", new Unit(
            SingularName: "TebiByte",
            PluralName: "TebiBytes",
            Abbreviations: ["TiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1099511627776,
            FromUnitToBase: static val => (val * 8) * 1099511627776,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PebiByte
        InformationUnits.TryAdd("PebiByte", new Unit(
            SingularName: "PebiByte",
            PluralName: "PebiBytes",
            Abbreviations: ["PiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1125899906842624,
            FromUnitToBase: static val => (val * 8) * 1125899906842624,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExbiByte
        InformationUnits.TryAdd("ExbiByte", new Unit(
            SingularName: "ExbiByte",
            PluralName: "ExbiBytes",
            Abbreviations: ["EiB"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1.152921504606847E+18,
            FromUnitToBase: static val => (val * 8) * 1.152921504606847E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Octet
        InformationUnits.TryAdd("Octet", new Unit(
            SingularName: "Octet",
            PluralName: "Octets",
            Abbreviations: ["o"],
            Factor: 8,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloOctet
        InformationUnits.TryAdd("KiloOctet", new Unit(
            SingularName: "KiloOctet",
            PluralName: "KiloOctets",
            Abbreviations: ["ko"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000,
            FromUnitToBase: static val => (val * 8) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaOctet
        InformationUnits.TryAdd("MegaOctet", new Unit(
            SingularName: "MegaOctet",
            PluralName: "MegaOctets",
            Abbreviations: ["Mo"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000,
            FromUnitToBase: static val => (val * 8) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaOctet
        InformationUnits.TryAdd("GigaOctet", new Unit(
            SingularName: "GigaOctet",
            PluralName: "GigaOctets",
            Abbreviations: ["Go"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraOctet
        InformationUnits.TryAdd("TeraOctet", new Unit(
            SingularName: "TeraOctet",
            PluralName: "TeraOctets",
            Abbreviations: ["To"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaOctet
        InformationUnits.TryAdd("PetaOctet", new Unit(
            SingularName: "PetaOctet",
            PluralName: "PetaOctets",
            Abbreviations: ["Po"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1000000000000000,
            FromUnitToBase: static val => (val * 8) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExaOctet
        InformationUnits.TryAdd("ExaOctet", new Unit(
            SingularName: "ExaOctet",
            PluralName: "ExaOctets",
            Abbreviations: ["Eo"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1E+18,
            FromUnitToBase: static val => (val * 8) * 1E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KibiOctet
        InformationUnits.TryAdd("KibiOctet", new Unit(
            SingularName: "KibiOctet",
            PluralName: "KibiOctets",
            Abbreviations: ["Kio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1024,
            FromUnitToBase: static val => (val * 8) * 1024,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MebiOctet
        InformationUnits.TryAdd("MebiOctet", new Unit(
            SingularName: "MebiOctet",
            PluralName: "MebiOctets",
            Abbreviations: ["Mio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1048576,
            FromUnitToBase: static val => (val * 8) * 1048576,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GibiOctet
        InformationUnits.TryAdd("GibiOctet", new Unit(
            SingularName: "GibiOctet",
            PluralName: "GibiOctets",
            Abbreviations: ["Gio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1073741824,
            FromUnitToBase: static val => (val * 8) * 1073741824,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TebiOctet
        InformationUnits.TryAdd("TebiOctet", new Unit(
            SingularName: "TebiOctet",
            PluralName: "TebiOctets",
            Abbreviations: ["Tio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1099511627776,
            FromUnitToBase: static val => (val * 8) * 1099511627776,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PebiOctet
        InformationUnits.TryAdd("PebiOctet", new Unit(
            SingularName: "PebiOctet",
            PluralName: "PebiOctets",
            Abbreviations: ["Pio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1125899906842624,
            FromUnitToBase: static val => (val * 8) * 1125899906842624,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExbiOctet
        InformationUnits.TryAdd("ExbiOctet", new Unit(
            SingularName: "ExbiOctet",
            PluralName: "ExbiOctets",
            Abbreviations: ["Eio"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 8) / 1.152921504606847E+18,
            FromUnitToBase: static val => (val * 8) * 1.152921504606847E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Bit
        InformationUnits.TryAdd("Bit", new Unit(
            SingularName: "Bit",
            PluralName: "Bits",
            Abbreviations: ["b"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloBit
        InformationUnits.TryAdd("KiloBit", new Unit(
            SingularName: "KiloBit",
            PluralName: "KiloBits",
            Abbreviations: ["kb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaBit
        InformationUnits.TryAdd("MegaBit", new Unit(
            SingularName: "MegaBit",
            PluralName: "MegaBits",
            Abbreviations: ["Mb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaBit
        InformationUnits.TryAdd("GigaBit", new Unit(
            SingularName: "GigaBit",
            PluralName: "GigaBits",
            Abbreviations: ["Gb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraBit
        InformationUnits.TryAdd("TeraBit", new Unit(
            SingularName: "TeraBit",
            PluralName: "TeraBits",
            Abbreviations: ["Tb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaBit
        InformationUnits.TryAdd("PetaBit", new Unit(
            SingularName: "PetaBit",
            PluralName: "PetaBits",
            Abbreviations: ["Pb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000000,
            FromUnitToBase: static val => (val) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExaBit
        InformationUnits.TryAdd("ExaBit", new Unit(
            SingularName: "ExaBit",
            PluralName: "ExaBits",
            Abbreviations: ["Eb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E+18,
            FromUnitToBase: static val => (val) * 1E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KibiBit
        InformationUnits.TryAdd("KibiBit", new Unit(
            SingularName: "KibiBit",
            PluralName: "KibiBits",
            Abbreviations: ["Kib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1024,
            FromUnitToBase: static val => (val) * 1024,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MebiBit
        InformationUnits.TryAdd("MebiBit", new Unit(
            SingularName: "MebiBit",
            PluralName: "MebiBits",
            Abbreviations: ["Mib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1048576,
            FromUnitToBase: static val => (val) * 1048576,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GibiBit
        InformationUnits.TryAdd("GibiBit", new Unit(
            SingularName: "GibiBit",
            PluralName: "GibiBits",
            Abbreviations: ["Gib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1073741824,
            FromUnitToBase: static val => (val) * 1073741824,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TebiBit
        InformationUnits.TryAdd("TebiBit", new Unit(
            SingularName: "TebiBit",
            PluralName: "TebiBits",
            Abbreviations: ["Tib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1099511627776,
            FromUnitToBase: static val => (val) * 1099511627776,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PebiBit
        InformationUnits.TryAdd("PebiBit", new Unit(
            SingularName: "PebiBit",
            PluralName: "PebiBits",
            Abbreviations: ["Pib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1125899906842624,
            FromUnitToBase: static val => (val) * 1125899906842624,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExbiBit
        InformationUnits.TryAdd("ExbiBit", new Unit(
            SingularName: "ExbiBit",
            PluralName: "ExbiBits",
            Abbreviations: ["Eib"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1.152921504606847E+18,
            FromUnitToBase: static val => (val) * 1.152921504606847E+18,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Information",
            "Bit",
            "In computing and telecommunications, a unit of information is the capacity of some standard data storage system or communication channel, used to measure the capacities of other systems and channels. In information theory, units of information are also used to measure the information contents or entropy of random variables.",
            InformationUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("Information", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
