// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadIrradiance() {
        // Loading Irradiance
        var IrradianceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // WattPerSquareMeter
        IrradianceUnits.TryAdd("WattPerSquareMeter", new Unit(
            SingularName: "WattPerSquareMeter",
            PluralName: "WattsPerSquareMeter",
            Abbreviations: ["W/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoWattPerSquareMeter
        IrradianceUnits.TryAdd("PicoWattPerSquareMeter", new Unit(
            SingularName: "PicoWattPerSquareMeter",
            PluralName: "PicoWattsPerSquareMeter",
            Abbreviations: ["pW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoWattPerSquareMeter
        IrradianceUnits.TryAdd("NanoWattPerSquareMeter", new Unit(
            SingularName: "NanoWattPerSquareMeter",
            PluralName: "NanoWattsPerSquareMeter",
            Abbreviations: ["nW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroWattPerSquareMeter
        IrradianceUnits.TryAdd("MicroWattPerSquareMeter", new Unit(
            SingularName: "MicroWattPerSquareMeter",
            PluralName: "MicroWattsPerSquareMeter",
            Abbreviations: ["µW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliWattPerSquareMeter
        IrradianceUnits.TryAdd("MilliWattPerSquareMeter", new Unit(
            SingularName: "MilliWattPerSquareMeter",
            PluralName: "MilliWattsPerSquareMeter",
            Abbreviations: ["mW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattPerSquareMeter
        IrradianceUnits.TryAdd("KiloWattPerSquareMeter", new Unit(
            SingularName: "KiloWattPerSquareMeter",
            PluralName: "KiloWattsPerSquareMeter",
            Abbreviations: ["kW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattPerSquareMeter
        IrradianceUnits.TryAdd("MegaWattPerSquareMeter", new Unit(
            SingularName: "MegaWattPerSquareMeter",
            PluralName: "MegaWattsPerSquareMeter",
            Abbreviations: ["MW/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattPerSquareCentimeter
        IrradianceUnits.TryAdd("WattPerSquareCentimeter", new Unit(
            SingularName: "WattPerSquareCentimeter",
            PluralName: "WattsPerSquareCentimeter",
            Abbreviations: ["W/cm²"],
            Factor: 10000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoWattPerSquareCentimeter
        IrradianceUnits.TryAdd("PicoWattPerSquareCentimeter", new Unit(
            SingularName: "PicoWattPerSquareCentimeter",
            PluralName: "PicoWattsPerSquareCentimeter",
            Abbreviations: ["pW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 1E-12,
            FromUnitToBase: static val => (val * 10000) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoWattPerSquareCentimeter
        IrradianceUnits.TryAdd("NanoWattPerSquareCentimeter", new Unit(
            SingularName: "NanoWattPerSquareCentimeter",
            PluralName: "NanoWattsPerSquareCentimeter",
            Abbreviations: ["nW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 1E-09,
            FromUnitToBase: static val => (val * 10000) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroWattPerSquareCentimeter
        IrradianceUnits.TryAdd("MicroWattPerSquareCentimeter", new Unit(
            SingularName: "MicroWattPerSquareCentimeter",
            PluralName: "MicroWattsPerSquareCentimeter",
            Abbreviations: ["µW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 1E-06,
            FromUnitToBase: static val => (val * 10000) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliWattPerSquareCentimeter
        IrradianceUnits.TryAdd("MilliWattPerSquareCentimeter", new Unit(
            SingularName: "MilliWattPerSquareCentimeter",
            PluralName: "MilliWattsPerSquareCentimeter",
            Abbreviations: ["mW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 0.001,
            FromUnitToBase: static val => (val * 10000) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattPerSquareCentimeter
        IrradianceUnits.TryAdd("KiloWattPerSquareCentimeter", new Unit(
            SingularName: "KiloWattPerSquareCentimeter",
            PluralName: "KiloWattsPerSquareCentimeter",
            Abbreviations: ["kW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 1000,
            FromUnitToBase: static val => (val * 10000) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattPerSquareCentimeter
        IrradianceUnits.TryAdd("MegaWattPerSquareCentimeter", new Unit(
            SingularName: "MegaWattPerSquareCentimeter",
            PluralName: "MegaWattsPerSquareCentimeter",
            Abbreviations: ["MW/cm²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.0001) / 1000000,
            FromUnitToBase: static val => (val * 10000) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Irradiance",
            "WattPerSquareMeter",
            "Irradiance is the intensity of ultraviolet (UV) or visible light incident on a surface.",
            IrradianceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["T"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("Irradiance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
