// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadJerk() {
        // Loading Jerk
        var JerkUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // MeterPerSecondCubed
        JerkUnits.TryAdd("MeterPerSecondCubed", new Unit(
            SingularName: "MeterPerSecondCubed",
            PluralName: "MetersPerSecondCubed",
            Abbreviations: ["m/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoMeterPerSecondCubed
        JerkUnits.TryAdd("NanoMeterPerSecondCubed", new Unit(
            SingularName: "NanoMeterPerSecondCubed",
            PluralName: "NanoMetersPerSecondCubed",
            Abbreviations: ["nm/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroMeterPerSecondCubed
        JerkUnits.TryAdd("MicroMeterPerSecondCubed", new Unit(
            SingularName: "MicroMeterPerSecondCubed",
            PluralName: "MicroMetersPerSecondCubed",
            Abbreviations: ["µm/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliMeterPerSecondCubed
        JerkUnits.TryAdd("MilliMeterPerSecondCubed", new Unit(
            SingularName: "MilliMeterPerSecondCubed",
            PluralName: "MilliMetersPerSecondCubed",
            Abbreviations: ["mm/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiMeterPerSecondCubed
        JerkUnits.TryAdd("CentiMeterPerSecondCubed", new Unit(
            SingularName: "CentiMeterPerSecondCubed",
            PluralName: "CentiMetersPerSecondCubed",
            Abbreviations: ["cm/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciMeterPerSecondCubed
        JerkUnits.TryAdd("DeciMeterPerSecondCubed", new Unit(
            SingularName: "DeciMeterPerSecondCubed",
            PluralName: "DeciMetersPerSecondCubed",
            Abbreviations: ["dm/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMeterPerSecondCubed
        JerkUnits.TryAdd("KiloMeterPerSecondCubed", new Unit(
            SingularName: "KiloMeterPerSecondCubed",
            PluralName: "KiloMetersPerSecondCubed",
            Abbreviations: ["km/s³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InchPerSecondCubed
        JerkUnits.TryAdd("InchPerSecondCubed", new Unit(
            SingularName: "InchPerSecondCubed",
            PluralName: "InchesPerSecondCubed",
            Abbreviations: ["in/s³"],
            Factor: 0.0254,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // FootPerSecondCubed
        JerkUnits.TryAdd("FootPerSecondCubed", new Unit(
            SingularName: "FootPerSecondCubed",
            PluralName: "FeetPerSecondCubed",
            Abbreviations: ["ft/s³"],
            Factor: 0.3048,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardGravitiesPerSecond
        JerkUnits.TryAdd("StandardGravitiesPerSecond", new Unit(
            SingularName: "StandardGravitiesPerSecond",
            PluralName: "StandardGravitiesPerSecond",
            Abbreviations: ["g/s"],
            Factor: 9.80665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliStandardGravitiesPerSecond
        JerkUnits.TryAdd("MilliStandardGravitiesPerSecond", new Unit(
            SingularName: "MilliStandardGravitiesPerSecond",
            PluralName: "MilliStandardGravitiesPerSecond",
            Abbreviations: ["mg/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 9.80665) / 0.001,
            FromUnitToBase: static val => (val * 9.80665) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Jerk",
            "MeterPerSecondCubed",
            "",
            JerkUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["T"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("Jerk", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
