// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadLeakRate() {
        // Loading LeakRate
        var LeakRateUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // PascalCubicMeterPerSecond
        LeakRateUnits.TryAdd("PascalCubicMeterPerSecond", new Unit(
            SingularName: "PascalCubicMeterPerSecond",
            PluralName: "PascalCubicMetersPerSecond",
            Abbreviations: ["Pa·m³/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillibarLiterPerSecond
        LeakRateUnits.TryAdd("MillibarLiterPerSecond", new Unit(
            SingularName: "MillibarLiterPerSecond",
            PluralName: "MillibarLitersPerSecond",
            Abbreviations: ["mbar·l/s"],
            Factor: 0.1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TorrLiterPerSecond
        LeakRateUnits.TryAdd("TorrLiterPerSecond", new Unit(
            SingularName: "TorrLiterPerSecond",
            PluralName: "TorrLitersPerSecond",
            Abbreviations: ["Torr·l/s"],
            Factor: 0.13333333333333333,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AtmCubicCentimeterPerSecond
        LeakRateUnits.TryAdd("AtmCubicCentimeterPerSecond", new Unit(
            SingularName: "AtmCubicCentimeterPerSecond",
            PluralName: "AtmCubicCentimetersPerSecond",
            Abbreviations: ["atm·cm³/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (1e6 / 101325),
            FromUnitToBase: static val => val / (1e6 / 101325),
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "LeakRate",
            "PascalCubicMeterPerSecond",
            "A leakage rate of QL = 1 Pa-m³/s is given when the pressure in a closed, evacuated container with a volume of 1 m³ rises by 1 Pa per second or when the pressure in the container drops by 1 Pa in the event of overpressure.",
            LeakRateUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["L"] = 2, ["T"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("LeakRate", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
