// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadLuminance() {
        // Loading Luminance
        var LuminanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CandelaPerSquareMeter
        LuminanceUnits.TryAdd("CandelaPerSquareMeter", new Unit(
            SingularName: "CandelaPerSquareMeter",
            PluralName: "CandelasPerSquareMeter",
            Abbreviations: ["Cd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoCandelaPerSquareMeter
        LuminanceUnits.TryAdd("NanoCandelaPerSquareMeter", new Unit(
            SingularName: "NanoCandelaPerSquareMeter",
            PluralName: "NanoCandelasPerSquareMeter",
            Abbreviations: ["nCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroCandelaPerSquareMeter
        LuminanceUnits.TryAdd("MicroCandelaPerSquareMeter", new Unit(
            SingularName: "MicroCandelaPerSquareMeter",
            PluralName: "MicroCandelasPerSquareMeter",
            Abbreviations: ["µCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliCandelaPerSquareMeter
        LuminanceUnits.TryAdd("MilliCandelaPerSquareMeter", new Unit(
            SingularName: "MilliCandelaPerSquareMeter",
            PluralName: "MilliCandelasPerSquareMeter",
            Abbreviations: ["mCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiCandelaPerSquareMeter
        LuminanceUnits.TryAdd("CentiCandelaPerSquareMeter", new Unit(
            SingularName: "CentiCandelaPerSquareMeter",
            PluralName: "CentiCandelasPerSquareMeter",
            Abbreviations: ["cCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciCandelaPerSquareMeter
        LuminanceUnits.TryAdd("DeciCandelaPerSquareMeter", new Unit(
            SingularName: "DeciCandelaPerSquareMeter",
            PluralName: "DeciCandelasPerSquareMeter",
            Abbreviations: ["dCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCandelaPerSquareMeter
        LuminanceUnits.TryAdd("KiloCandelaPerSquareMeter", new Unit(
            SingularName: "KiloCandelaPerSquareMeter",
            PluralName: "KiloCandelasPerSquareMeter",
            Abbreviations: ["kCd/m²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CandelaPerSquareFoot
        LuminanceUnits.TryAdd("CandelaPerSquareFoot", new Unit(
            SingularName: "CandelaPerSquareFoot",
            PluralName: "CandelasPerSquareFoot",
            Abbreviations: ["Cd/ft²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9.290304e-2,
            FromUnitToBase: static val => val / 9.290304e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CandelaPerSquareInch
        LuminanceUnits.TryAdd("CandelaPerSquareInch", new Unit(
            SingularName: "CandelaPerSquareInch",
            PluralName: "CandelasPerSquareInch",
            Abbreviations: ["Cd/in²"],
            Factor: 1550.0031000062002,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Nit
        LuminanceUnits.TryAdd("Nit", new Unit(
            SingularName: "Nit",
            PluralName: "Nits",
            Abbreviations: ["nt"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://www.britannica.com/science/luminosity",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Luminance",
            "CandelaPerSquareMeter",
            "",
            LuminanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["J"] = 1, ["L"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("Luminance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
