// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadLuminousFlux() {
        // Loading LuminousFlux
        var LuminousFluxUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Lumen
        LuminousFluxUnits.TryAdd("Lumen", new Unit(
            SingularName: "Lumen",
            PluralName: "Lumens",
            Abbreviations: ["lm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "LuminousFlux",
            "Lumen",
            "In photometry, luminous flux or luminous power is the measure of the perceived power of light.",
            LuminousFluxUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["J"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("LuminousFlux", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
