// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMagnetization() {
        // Loading Magnetization
        var MagnetizationUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // AmperePerMeter
        MagnetizationUnits.TryAdd("AmperePerMeter", new Unit(
            SingularName: "AmperePerMeter",
            PluralName: "AmperesPerMeter",
            Abbreviations: ["A/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Magnetization",
            "AmperePerMeter",
            "In classical electromagnetism, magnetization is the vector field that expresses the density of permanent or induced magnetic dipole moments in a magnetic material.",
            MagnetizationUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("Magnetization", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
