// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMagneticFlux() {
        // Loading MagneticFlux
        var MagneticFluxUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Weber
        MagneticFluxUnits.TryAdd("Weber", new Unit(
            SingularName: "Weber",
            PluralName: "Webers",
            Abbreviations: ["Wb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "MagneticFlux",
            "Weber",
            "In physics, specifically electromagnetism, the magnetic flux through a surface is the surface integral of the normal component of the magnetic field B passing through that surface.",
            MagneticFluxUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -2, ["I"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("MagneticFlux", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
