// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMassConcentration() {
        // Loading MassConcentration
        var MassConcentrationUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // GramPerCubicMillimeter
        MassConcentrationUnits.TryAdd("GramPerCubicMillimeter", new Unit(
            SingularName: "GramPerCubicMillimeter",
            PluralName: "GramsPerCubicMillimeter",
            Abbreviations: ["g/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-6,
            FromUnitToBase: static val => val / 1e-6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloGramPerCubicMillimeter
        MassConcentrationUnits.TryAdd("KiloGramPerCubicMillimeter", new Unit(
            SingularName: "KiloGramPerCubicMillimeter",
            PluralName: "KiloGramsPerCubicMillimeter",
            Abbreviations: ["kg/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 1000,
            FromUnitToBase: static val => (val / 1e-6) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerCubicCentimeter
        MassConcentrationUnits.TryAdd("GramPerCubicCentimeter", new Unit(
            SingularName: "GramPerCubicCentimeter",
            PluralName: "GramsPerCubicCentimeter",
            Abbreviations: ["g/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-3,
            FromUnitToBase: static val => val / 1e-3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloGramPerCubicCentimeter
        MassConcentrationUnits.TryAdd("KiloGramPerCubicCentimeter", new Unit(
            SingularName: "KiloGramPerCubicCentimeter",
            PluralName: "KiloGramsPerCubicCentimeter",
            Abbreviations: ["kg/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1000,
            FromUnitToBase: static val => (val / 1e-3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerCubicMeter
        MassConcentrationUnits.TryAdd("GramPerCubicMeter", new Unit(
            SingularName: "GramPerCubicMeter",
            PluralName: "GramsPerCubicMeter",
            Abbreviations: ["g/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e3,
            FromUnitToBase: static val => val / 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloGramPerCubicMeter
        MassConcentrationUnits.TryAdd("KiloGramPerCubicMeter", new Unit(
            SingularName: "KiloGramPerCubicMeter",
            PluralName: "KiloGramsPerCubicMeter",
            Abbreviations: ["kg/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 1000,
            FromUnitToBase: static val => (val / 1e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerCubicMeter
        MassConcentrationUnits.TryAdd("MilliGramPerCubicMeter", new Unit(
            SingularName: "MilliGramPerCubicMeter",
            PluralName: "MilliGramsPerCubicMeter",
            Abbreviations: ["mg/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 0.001,
            FromUnitToBase: static val => (val / 1e3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerCubicMeter
        MassConcentrationUnits.TryAdd("MicroGramPerCubicMeter", new Unit(
            SingularName: "MicroGramPerCubicMeter",
            PluralName: "MicroGramsPerCubicMeter",
            Abbreviations: ["µg/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 1E-06,
            FromUnitToBase: static val => (val / 1e3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerMicroliter
        MassConcentrationUnits.TryAdd("GramPerMicroliter", new Unit(
            SingularName: "GramPerMicroliter",
            PluralName: "GramsPerMicroliter",
            Abbreviations: ["g/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-6,
            FromUnitToBase: static val => val / 1e-6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoGramPerMicroliter
        MassConcentrationUnits.TryAdd("PicoGramPerMicroliter", new Unit(
            SingularName: "PicoGramPerMicroliter",
            PluralName: "PicoGramsPerMicroliter",
            Abbreviations: ["pg/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 1E-12,
            FromUnitToBase: static val => (val / 1e-6) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoGramPerMicroliter
        MassConcentrationUnits.TryAdd("NanoGramPerMicroliter", new Unit(
            SingularName: "NanoGramPerMicroliter",
            PluralName: "NanoGramsPerMicroliter",
            Abbreviations: ["ng/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 1E-09,
            FromUnitToBase: static val => (val / 1e-6) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerMicroliter
        MassConcentrationUnits.TryAdd("MicroGramPerMicroliter", new Unit(
            SingularName: "MicroGramPerMicroliter",
            PluralName: "MicroGramsPerMicroliter",
            Abbreviations: ["µg/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 1E-06,
            FromUnitToBase: static val => (val / 1e-6) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerMicroliter
        MassConcentrationUnits.TryAdd("MilliGramPerMicroliter", new Unit(
            SingularName: "MilliGramPerMicroliter",
            PluralName: "MilliGramsPerMicroliter",
            Abbreviations: ["mg/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 0.001,
            FromUnitToBase: static val => (val / 1e-6) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiGramPerMicroliter
        MassConcentrationUnits.TryAdd("CentiGramPerMicroliter", new Unit(
            SingularName: "CentiGramPerMicroliter",
            PluralName: "CentiGramsPerMicroliter",
            Abbreviations: ["cg/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 0.01,
            FromUnitToBase: static val => (val / 1e-6) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciGramPerMicroliter
        MassConcentrationUnits.TryAdd("DeciGramPerMicroliter", new Unit(
            SingularName: "DeciGramPerMicroliter",
            PluralName: "DeciGramsPerMicroliter",
            Abbreviations: ["dg/μl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-6) / 0.1,
            FromUnitToBase: static val => (val / 1e-6) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerMilliliter
        MassConcentrationUnits.TryAdd("GramPerMilliliter", new Unit(
            SingularName: "GramPerMilliliter",
            PluralName: "GramsPerMilliliter",
            Abbreviations: ["g/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-3,
            FromUnitToBase: static val => val / 1e-3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoGramPerMilliliter
        MassConcentrationUnits.TryAdd("PicoGramPerMilliliter", new Unit(
            SingularName: "PicoGramPerMilliliter",
            PluralName: "PicoGramsPerMilliliter",
            Abbreviations: ["pg/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-12,
            FromUnitToBase: static val => (val / 1e-3) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoGramPerMilliliter
        MassConcentrationUnits.TryAdd("NanoGramPerMilliliter", new Unit(
            SingularName: "NanoGramPerMilliliter",
            PluralName: "NanoGramsPerMilliliter",
            Abbreviations: ["ng/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-09,
            FromUnitToBase: static val => (val / 1e-3) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerMilliliter
        MassConcentrationUnits.TryAdd("MicroGramPerMilliliter", new Unit(
            SingularName: "MicroGramPerMilliliter",
            PluralName: "MicroGramsPerMilliliter",
            Abbreviations: ["µg/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-06,
            FromUnitToBase: static val => (val / 1e-3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerMilliliter
        MassConcentrationUnits.TryAdd("MilliGramPerMilliliter", new Unit(
            SingularName: "MilliGramPerMilliliter",
            PluralName: "MilliGramsPerMilliliter",
            Abbreviations: ["mg/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.001,
            FromUnitToBase: static val => (val / 1e-3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiGramPerMilliliter
        MassConcentrationUnits.TryAdd("CentiGramPerMilliliter", new Unit(
            SingularName: "CentiGramPerMilliliter",
            PluralName: "CentiGramsPerMilliliter",
            Abbreviations: ["cg/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.01,
            FromUnitToBase: static val => (val / 1e-3) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciGramPerMilliliter
        MassConcentrationUnits.TryAdd("DeciGramPerMilliliter", new Unit(
            SingularName: "DeciGramPerMilliliter",
            PluralName: "DeciGramsPerMilliliter",
            Abbreviations: ["dg/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.1,
            FromUnitToBase: static val => (val / 1e-3) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerDeciliter
        MassConcentrationUnits.TryAdd("GramPerDeciliter", new Unit(
            SingularName: "GramPerDeciliter",
            PluralName: "GramsPerDeciliter",
            Abbreviations: ["g/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-1,
            FromUnitToBase: static val => val / 1e-1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoGramPerDeciliter
        MassConcentrationUnits.TryAdd("PicoGramPerDeciliter", new Unit(
            SingularName: "PicoGramPerDeciliter",
            PluralName: "PicoGramsPerDeciliter",
            Abbreviations: ["pg/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 1E-12,
            FromUnitToBase: static val => (val / 1e-1) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoGramPerDeciliter
        MassConcentrationUnits.TryAdd("NanoGramPerDeciliter", new Unit(
            SingularName: "NanoGramPerDeciliter",
            PluralName: "NanoGramsPerDeciliter",
            Abbreviations: ["ng/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 1E-09,
            FromUnitToBase: static val => (val / 1e-1) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerDeciliter
        MassConcentrationUnits.TryAdd("MicroGramPerDeciliter", new Unit(
            SingularName: "MicroGramPerDeciliter",
            PluralName: "MicroGramsPerDeciliter",
            Abbreviations: ["µg/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 1E-06,
            FromUnitToBase: static val => (val / 1e-1) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerDeciliter
        MassConcentrationUnits.TryAdd("MilliGramPerDeciliter", new Unit(
            SingularName: "MilliGramPerDeciliter",
            PluralName: "MilliGramsPerDeciliter",
            Abbreviations: ["mg/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 0.001,
            FromUnitToBase: static val => (val / 1e-1) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiGramPerDeciliter
        MassConcentrationUnits.TryAdd("CentiGramPerDeciliter", new Unit(
            SingularName: "CentiGramPerDeciliter",
            PluralName: "CentiGramsPerDeciliter",
            Abbreviations: ["cg/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 0.01,
            FromUnitToBase: static val => (val / 1e-1) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciGramPerDeciliter
        MassConcentrationUnits.TryAdd("DeciGramPerDeciliter", new Unit(
            SingularName: "DeciGramPerDeciliter",
            PluralName: "DeciGramsPerDeciliter",
            Abbreviations: ["dg/dl"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-1) / 0.1,
            FromUnitToBase: static val => (val / 1e-1) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GramPerLiter
        MassConcentrationUnits.TryAdd("GramPerLiter", new Unit(
            SingularName: "GramPerLiter",
            PluralName: "GramsPerLiter",
            Abbreviations: ["g/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoGramPerLiter
        MassConcentrationUnits.TryAdd("PicoGramPerLiter", new Unit(
            SingularName: "PicoGramPerLiter",
            PluralName: "PicoGramsPerLiter",
            Abbreviations: ["pg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoGramPerLiter
        MassConcentrationUnits.TryAdd("NanoGramPerLiter", new Unit(
            SingularName: "NanoGramPerLiter",
            PluralName: "NanoGramsPerLiter",
            Abbreviations: ["ng/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerLiter
        MassConcentrationUnits.TryAdd("MicroGramPerLiter", new Unit(
            SingularName: "MicroGramPerLiter",
            PluralName: "MicroGramsPerLiter",
            Abbreviations: ["µg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerLiter
        MassConcentrationUnits.TryAdd("MilliGramPerLiter", new Unit(
            SingularName: "MilliGramPerLiter",
            PluralName: "MilliGramsPerLiter",
            Abbreviations: ["mg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiGramPerLiter
        MassConcentrationUnits.TryAdd("CentiGramPerLiter", new Unit(
            SingularName: "CentiGramPerLiter",
            PluralName: "CentiGramsPerLiter",
            Abbreviations: ["cg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciGramPerLiter
        MassConcentrationUnits.TryAdd("DeciGramPerLiter", new Unit(
            SingularName: "DeciGramPerLiter",
            PluralName: "DeciGramsPerLiter",
            Abbreviations: ["dg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloGramPerLiter
        MassConcentrationUnits.TryAdd("KiloGramPerLiter", new Unit(
            SingularName: "KiloGramPerLiter",
            PluralName: "KiloGramsPerLiter",
            Abbreviations: ["kg/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonnePerCubicMillimeter
        MassConcentrationUnits.TryAdd("TonnePerCubicMillimeter", new Unit(
            SingularName: "TonnePerCubicMillimeter",
            PluralName: "TonnesPerCubicMillimeter",
            Abbreviations: ["t/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-12,
            FromUnitToBase: static val => val / 1e-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonnePerCubicCentimeter
        MassConcentrationUnits.TryAdd("TonnePerCubicCentimeter", new Unit(
            SingularName: "TonnePerCubicCentimeter",
            PluralName: "TonnesPerCubicCentimeter",
            Abbreviations: ["t/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-9,
            FromUnitToBase: static val => val / 1e-9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonnePerCubicMeter
        MassConcentrationUnits.TryAdd("TonnePerCubicMeter", new Unit(
            SingularName: "TonnePerCubicMeter",
            PluralName: "TonnesPerCubicMeter",
            Abbreviations: ["t/m³"],
            Factor: 1000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerCubicInch
        MassConcentrationUnits.TryAdd("PoundPerCubicInch", new Unit(
            SingularName: "PoundPerCubicInch",
            PluralName: "PoundsPerCubicInch",
            Abbreviations: ["lb/in³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1.6387064e-5 / 0.45359237,
            FromUnitToBase: static val => val * 0.45359237 / 1.6387064e-5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundPerCubicInch
        MassConcentrationUnits.TryAdd("KiloPoundPerCubicInch", new Unit(
            SingularName: "KiloPoundPerCubicInch",
            PluralName: "KiloPoundsPerCubicInch",
            Abbreviations: ["kip/in³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1.6387064e-5 / 0.45359237) / 1000,
            FromUnitToBase: static val => (val * 0.45359237 / 1.6387064e-5) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerCubicFoot
        MassConcentrationUnits.TryAdd("PoundPerCubicFoot", new Unit(
            SingularName: "PoundPerCubicFoot",
            PluralName: "PoundsPerCubicFoot",
            Abbreviations: ["lb/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.028316846592 / 0.45359237,
            FromUnitToBase: static val => val * 0.45359237 / 0.028316846592,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundPerCubicFoot
        MassConcentrationUnits.TryAdd("KiloPoundPerCubicFoot", new Unit(
            SingularName: "KiloPoundPerCubicFoot",
            PluralName: "KiloPoundsPerCubicFoot",
            Abbreviations: ["kip/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.028316846592 / 0.45359237) / 1000,
            FromUnitToBase: static val => (val * 0.45359237 / 0.028316846592) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SlugPerCubicFoot
        MassConcentrationUnits.TryAdd("SlugPerCubicFoot", new Unit(
            SingularName: "SlugPerCubicFoot",
            PluralName: "SlugsPerCubicFoot",
            Abbreviations: ["slug/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (0.3048 * 0.028316846592) / (0.45359237 * 9.80665),
            FromUnitToBase: static val => val * (0.45359237 * 9.80665) / (0.3048 * 0.028316846592),
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerUSGallon
        MassConcentrationUnits.TryAdd("PoundPerUSGallon", new Unit(
            SingularName: "PoundPerUSGallon",
            PluralName: "PoundsPerUSGallon",
            Abbreviations: ["ppg (U.S.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.003785411784 / 0.45359237,
            FromUnitToBase: static val => val * 0.45359237 / 0.003785411784,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OuncePerUSGallon
        MassConcentrationUnits.TryAdd("OuncePerUSGallon", new Unit(
            SingularName: "OuncePerUSGallon",
            PluralName: "OuncesPerUSGallon",
            Abbreviations: ["oz/gal (U.S.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.003785411784 / 0.028349523125,
            FromUnitToBase: static val => val * 0.028349523125 / 0.003785411784,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OuncePerImperialGallon
        MassConcentrationUnits.TryAdd("OuncePerImperialGallon", new Unit(
            SingularName: "OuncePerImperialGallon",
            PluralName: "OuncesPerImperialGallon",
            Abbreviations: ["oz/gal (imp.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.00454609 / 0.028349523125,
            FromUnitToBase: static val => val * 0.028349523125 / 0.00454609,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerImperialGallon
        MassConcentrationUnits.TryAdd("PoundPerImperialGallon", new Unit(
            SingularName: "PoundPerImperialGallon",
            PluralName: "PoundsPerImperialGallon",
            Abbreviations: ["ppg (imp.)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.00454609 / 0.45359237,
            FromUnitToBase: static val => val * 0.45359237 / 0.00454609,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "MassConcentration",
            "KilogramPerCubicMeter",
            "In chemistry, the mass concentration ρi (or γi) is defined as the mass of a constituent mi divided by the volume of the mixture V",
            MassConcentrationUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["L"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("MassConcentration", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
