// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMolarEnergy() {
        // Loading MolarEnergy
        var MolarEnergyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // JoulePerMole
        MolarEnergyUnits.TryAdd("JoulePerMole", new Unit(
            SingularName: "JoulePerMole",
            PluralName: "JoulesPerMole",
            Abbreviations: ["J/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerMole
        MolarEnergyUnits.TryAdd("KiloJoulePerMole", new Unit(
            SingularName: "KiloJoulePerMole",
            PluralName: "KiloJoulesPerMole",
            Abbreviations: ["kJ/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerMole
        MolarEnergyUnits.TryAdd("MegaJoulePerMole", new Unit(
            SingularName: "MegaJoulePerMole",
            PluralName: "MegaJoulesPerMole",
            Abbreviations: ["MJ/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "MolarEnergy",
            "JoulePerMole",
            "Molar energy is the amount of energy stored in 1 mole of a substance.",
            MolarEnergyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -2, ["N"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("MolarEnergy", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
