// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMolarFlow() {
        // Loading MolarFlow
        var MolarFlowUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // MolePerSecond
        MolarFlowUnits.TryAdd("MolePerSecond", new Unit(
            SingularName: "MolePerSecond",
            PluralName: "MolesPerSecond",
            Abbreviations: ["mol/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMolePerSecond
        MolarFlowUnits.TryAdd("KiloMolePerSecond", new Unit(
            SingularName: "KiloMolePerSecond",
            PluralName: "KiloMolesPerSecond",
            Abbreviations: ["kmol/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MolePerMinute
        MolarFlowUnits.TryAdd("MolePerMinute", new Unit(
            SingularName: "MolePerMinute",
            PluralName: "MolesPerMinute",
            Abbreviations: ["mol/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMolePerMinute
        MolarFlowUnits.TryAdd("KiloMolePerMinute", new Unit(
            SingularName: "KiloMolePerMinute",
            PluralName: "KiloMolesPerMinute",
            Abbreviations: ["kmol/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60) / 1000,
            FromUnitToBase: static val => (val / 60) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MolePerHour
        MolarFlowUnits.TryAdd("MolePerHour", new Unit(
            SingularName: "MolePerHour",
            PluralName: "MolesPerHour",
            Abbreviations: ["kmol/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMolePerHour
        MolarFlowUnits.TryAdd("KiloMolePerHour", new Unit(
            SingularName: "KiloMolePerHour",
            PluralName: "KiloMolesPerHour",
            Abbreviations: ["kkmol/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600) / 1000,
            FromUnitToBase: static val => (val / 3600) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundMolePerSecond
        MolarFlowUnits.TryAdd("PoundMolePerSecond", new Unit(
            SingularName: "PoundMolePerSecond",
            PluralName: "PoundMolesPerSecond",
            Abbreviations: ["lbmol/s"],
            Factor: 453.59237,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundMolePerMinute
        MolarFlowUnits.TryAdd("PoundMolePerMinute", new Unit(
            SingularName: "PoundMolePerMinute",
            PluralName: "PoundMolesPerMinute",
            Abbreviations: ["lbmol/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) * 60,
            FromUnitToBase: static val => (val * 453.59237) / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundMolePerHour
        MolarFlowUnits.TryAdd("PoundMolePerHour", new Unit(
            SingularName: "PoundMolePerHour",
            PluralName: "PoundMolesPerHour",
            Abbreviations: ["lbmol/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 453.59237) * 3600,
            FromUnitToBase: static val => (val * 453.59237) / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "MolarFlow",
            "MolePerSecond",
            "Molar flow is the ratio of the amount of substance change to the time during which the change occurred (value of amount of substance changes per unit time).",
            MolarFlowUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["N"] = 1, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("MolarFlow", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
