// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMolarMass() {
        // Loading MolarMass
        var MolarMassUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // GramPerMole
        MolarMassUnits.TryAdd("GramPerMole", new Unit(
            SingularName: "GramPerMole",
            PluralName: "GramsPerMole",
            Abbreviations: ["g/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e3,
            FromUnitToBase: static val => val / 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoGramPerMole
        MolarMassUnits.TryAdd("NanoGramPerMole", new Unit(
            SingularName: "NanoGramPerMole",
            PluralName: "NanoGramsPerMole",
            Abbreviations: ["ng/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 1E-09,
            FromUnitToBase: static val => (val / 1e3) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroGramPerMole
        MolarMassUnits.TryAdd("MicroGramPerMole", new Unit(
            SingularName: "MicroGramPerMole",
            PluralName: "MicroGramsPerMole",
            Abbreviations: ["µg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 1E-06,
            FromUnitToBase: static val => (val / 1e3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliGramPerMole
        MolarMassUnits.TryAdd("MilliGramPerMole", new Unit(
            SingularName: "MilliGramPerMole",
            PluralName: "MilliGramsPerMole",
            Abbreviations: ["mg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 0.001,
            FromUnitToBase: static val => (val / 1e3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiGramPerMole
        MolarMassUnits.TryAdd("CentiGramPerMole", new Unit(
            SingularName: "CentiGramPerMole",
            PluralName: "CentiGramsPerMole",
            Abbreviations: ["cg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 0.01,
            FromUnitToBase: static val => (val / 1e3) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciGramPerMole
        MolarMassUnits.TryAdd("DeciGramPerMole", new Unit(
            SingularName: "DeciGramPerMole",
            PluralName: "DeciGramsPerMole",
            Abbreviations: ["dg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 0.1,
            FromUnitToBase: static val => (val / 1e3) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaGramPerMole
        MolarMassUnits.TryAdd("DecaGramPerMole", new Unit(
            SingularName: "DecaGramPerMole",
            PluralName: "DecaGramsPerMole",
            Abbreviations: ["dag/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 10,
            FromUnitToBase: static val => (val / 1e3) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoGramPerMole
        MolarMassUnits.TryAdd("HectoGramPerMole", new Unit(
            SingularName: "HectoGramPerMole",
            PluralName: "HectoGramsPerMole",
            Abbreviations: ["hg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 100,
            FromUnitToBase: static val => (val / 1e3) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloGramPerMole
        MolarMassUnits.TryAdd("KiloGramPerMole", new Unit(
            SingularName: "KiloGramPerMole",
            PluralName: "KiloGramsPerMole",
            Abbreviations: ["kg/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e3) / 1000,
            FromUnitToBase: static val => (val / 1e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramPerKilomole
        MolarMassUnits.TryAdd("KilogramPerKilomole", new Unit(
            SingularName: "KilogramPerKilomole",
            PluralName: "KilogramsPerKilomole",
            Abbreviations: ["kg/kmol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e3,
            FromUnitToBase: static val => val / 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundPerMole
        MolarMassUnits.TryAdd("PoundPerMole", new Unit(
            SingularName: "PoundPerMole",
            PluralName: "PoundsPerMole",
            Abbreviations: ["lb/mol"],
            Factor: 0.45359237,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundPerMole
        MolarMassUnits.TryAdd("KiloPoundPerMole", new Unit(
            SingularName: "KiloPoundPerMole",
            PluralName: "KiloPoundsPerMole",
            Abbreviations: ["klb/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 0.45359237) / 1000,
            FromUnitToBase: static val => (val * 0.45359237) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPoundPerMole
        MolarMassUnits.TryAdd("MegaPoundPerMole", new Unit(
            SingularName: "MegaPoundPerMole",
            PluralName: "MegaPoundsPerMole",
            Abbreviations: ["Mlb/mol"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 0.45359237) / 1000000,
            FromUnitToBase: static val => (val * 0.45359237) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "MolarMass",
            "KilogramPerMole",
            "In chemistry, the molar mass M is a physical property defined as the mass of a given substance (chemical element or chemical compound) divided by the amount of substance.",
            MolarMassUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["N"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("MolarMass", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
