// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadMolarity() {
        // Loading Molarity
        var MolarityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // MolePerCubicMeter
        MolarityUnits.TryAdd("MolePerCubicMeter", new Unit(
            SingularName: "MolePerCubicMeter",
            PluralName: "MolesPerCubicMeter",
            Abbreviations: ["mol/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloMolePerCubicMeter
        MolarityUnits.TryAdd("KiloMolePerCubicMeter", new Unit(
            SingularName: "KiloMolePerCubicMeter",
            PluralName: "KiloMolesPerCubicMeter",
            Abbreviations: ["kmol/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MolePerLiter
        MolarityUnits.TryAdd("MolePerLiter", new Unit(
            SingularName: "MolePerLiter",
            PluralName: "MolesPerLiter",
            Abbreviations: ["mol/l", "M"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-3,
            FromUnitToBase: static val => val / 1e-3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // FemtoMolePerLiter
        MolarityUnits.TryAdd("FemtoMolePerLiter", new Unit(
            SingularName: "FemtoMolePerLiter",
            PluralName: "FemtoMolesPerLiter",
            Abbreviations: ["fmol/l", "fM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-15,
            FromUnitToBase: static val => (val / 1e-3) * 1E-15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoMolePerLiter
        MolarityUnits.TryAdd("PicoMolePerLiter", new Unit(
            SingularName: "PicoMolePerLiter",
            PluralName: "PicoMolesPerLiter",
            Abbreviations: ["pmol/l", "pM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-12,
            FromUnitToBase: static val => (val / 1e-3) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoMolePerLiter
        MolarityUnits.TryAdd("NanoMolePerLiter", new Unit(
            SingularName: "NanoMolePerLiter",
            PluralName: "NanoMolesPerLiter",
            Abbreviations: ["nmol/l", "nM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-09,
            FromUnitToBase: static val => (val / 1e-3) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroMolePerLiter
        MolarityUnits.TryAdd("MicroMolePerLiter", new Unit(
            SingularName: "MicroMolePerLiter",
            PluralName: "MicroMolesPerLiter",
            Abbreviations: ["µmol/l", "µM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-06,
            FromUnitToBase: static val => (val / 1e-3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliMolePerLiter
        MolarityUnits.TryAdd("MilliMolePerLiter", new Unit(
            SingularName: "MilliMolePerLiter",
            PluralName: "MilliMolesPerLiter",
            Abbreviations: ["mmol/l", "mM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.001,
            FromUnitToBase: static val => (val / 1e-3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiMolePerLiter
        MolarityUnits.TryAdd("CentiMolePerLiter", new Unit(
            SingularName: "CentiMolePerLiter",
            PluralName: "CentiMolesPerLiter",
            Abbreviations: ["cmol/l", "cM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.01,
            FromUnitToBase: static val => (val / 1e-3) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciMolePerLiter
        MolarityUnits.TryAdd("DeciMolePerLiter", new Unit(
            SingularName: "DeciMolePerLiter",
            PluralName: "DeciMolesPerLiter",
            Abbreviations: ["dmol/l", "dM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.1,
            FromUnitToBase: static val => (val / 1e-3) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundMolePerCubicFoot
        MolarityUnits.TryAdd("PoundMolePerCubicFoot", new Unit(
            SingularName: "PoundMolePerCubicFoot",
            PluralName: "PoundMolesPerCubicFoot",
            Abbreviations: ["lbmol/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1000 * 0.45359237 / 0.028316846592),
            FromUnitToBase: static val => val * 1000 * 0.45359237 / 0.028316846592,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Molarity",
            "MolePerCubicMeter",
            "Molar concentration, also called molarity, amount concentration or substance concentration, is a measure of the concentration of a solute in a solution, or of any chemical species, in terms of amount of substance in a given volume.",
            MolarityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -3, ["N"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("Molarity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
