// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPermittivity() {
        // Loading Permittivity
        var PermittivityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // FaradPerMeter
        PermittivityUnits.TryAdd("FaradPerMeter", new Unit(
            SingularName: "FaradPerMeter",
            PluralName: "FaradsPerMeter",
            Abbreviations: ["F/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Permittivity",
            "FaradPerMeter",
            "In electromagnetism, permittivity is the measure of resistance that is encountered when forming an electric field in a particular medium.",
            PermittivityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -3, ["M"] = -1, ["T"] = 4, ["I"] = 2 },
            "",
            false,
            1
        );
        _quantities.Add("Permittivity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
