// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPermeability() {
        // Loading Permeability
        var PermeabilityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // HenryPerMeter
        PermeabilityUnits.TryAdd("HenryPerMeter", new Unit(
            SingularName: "HenryPerMeter",
            PluralName: "HenriesPerMeter",
            Abbreviations: ["H/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Permeability",
            "HenryPerMeter",
            "In electromagnetism, permeability is the measure of the ability of a material to support the formation of a magnetic field within itself.",
            PermeabilityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = 1, ["T"] = -2, ["I"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("Permeability", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
