// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPower() {
        // Loading Power
        var PowerUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Watt
        PowerUnits.TryAdd("Watt", new Unit(
            SingularName: "Watt",
            PluralName: "Watts",
            Abbreviations: ["W"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // FemtoWatt
        PowerUnits.TryAdd("FemtoWatt", new Unit(
            SingularName: "FemtoWatt",
            PluralName: "FemtoWatts",
            Abbreviations: ["fW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-15,
            FromUnitToBase: static val => (val) * 1E-15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoWatt
        PowerUnits.TryAdd("PicoWatt", new Unit(
            SingularName: "PicoWatt",
            PluralName: "PicoWatts",
            Abbreviations: ["pW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoWatt
        PowerUnits.TryAdd("NanoWatt", new Unit(
            SingularName: "NanoWatt",
            PluralName: "NanoWatts",
            Abbreviations: ["nW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroWatt
        PowerUnits.TryAdd("MicroWatt", new Unit(
            SingularName: "MicroWatt",
            PluralName: "MicroWatts",
            Abbreviations: ["µW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliWatt
        PowerUnits.TryAdd("MilliWatt", new Unit(
            SingularName: "MilliWatt",
            PluralName: "MilliWatts",
            Abbreviations: ["mW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciWatt
        PowerUnits.TryAdd("DeciWatt", new Unit(
            SingularName: "DeciWatt",
            PluralName: "DeciWatts",
            Abbreviations: ["dW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaWatt
        PowerUnits.TryAdd("DecaWatt", new Unit(
            SingularName: "DecaWatt",
            PluralName: "DecaWatts",
            Abbreviations: ["daW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 10,
            FromUnitToBase: static val => (val) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWatt
        PowerUnits.TryAdd("KiloWatt", new Unit(
            SingularName: "KiloWatt",
            PluralName: "KiloWatts",
            Abbreviations: ["kW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWatt
        PowerUnits.TryAdd("MegaWatt", new Unit(
            SingularName: "MegaWatt",
            PluralName: "MegaWatts",
            Abbreviations: ["MW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWatt
        PowerUnits.TryAdd("GigaWatt", new Unit(
            SingularName: "GigaWatt",
            PluralName: "GigaWatts",
            Abbreviations: ["GW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWatt
        PowerUnits.TryAdd("TeraWatt", new Unit(
            SingularName: "TeraWatt",
            PluralName: "TeraWatts",
            Abbreviations: ["TW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaWatt
        PowerUnits.TryAdd("PetaWatt", new Unit(
            SingularName: "PetaWatt",
            PluralName: "PetaWatts",
            Abbreviations: ["PW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000000,
            FromUnitToBase: static val => (val) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MechanicalHorsepower
        PowerUnits.TryAdd("MechanicalHorsepower", new Unit(
            SingularName: "MechanicalHorsepower",
            PluralName: "MechanicalHorsepower",
            Abbreviations: ["hp(I)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (76.0402249 * 9.80665),
            FromUnitToBase: static val => val * 76.0402249 * 9.80665,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower#Imperial_horsepower",
            ObsoleteText: ""
        ));
        // MetricHorsepower
        PowerUnits.TryAdd("MetricHorsepower", new Unit(
            SingularName: "MetricHorsepower",
            PluralName: "MetricHorsepower",
            Abbreviations: ["hp(M)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (75 * 9.80665),
            FromUnitToBase: static val => val * 75 * 9.80665,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower#Metric_horsepower_(PS,_KM,_cv,_hk,_pk,_k,_ks,_ch)",
            ObsoleteText: ""
        ));
        // ElectricalHorsepower
        PowerUnits.TryAdd("ElectricalHorsepower", new Unit(
            SingularName: "ElectricalHorsepower",
            PluralName: "ElectricalHorsepower",
            Abbreviations: ["hp(E)"],
            Factor: 746,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower#Electrical_horsepower",
            ObsoleteText: ""
        ));
        // BoilerHorsepower
        PowerUnits.TryAdd("BoilerHorsepower", new Unit(
            SingularName: "BoilerHorsepower",
            PluralName: "BoilerHorsepower",
            Abbreviations: ["hp(S)"],
            Factor: 9812.5,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower#Boiler_horsepower",
            ObsoleteText: ""
        ));
        // HydraulicHorsepower
        PowerUnits.TryAdd("HydraulicHorsepower", new Unit(
            SingularName: "HydraulicHorsepower",
            PluralName: "HydraulicHorsepower",
            Abbreviations: ["hp(H)"],
            Factor: 745.6998715822702,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Horsepower#Hydraulic_horsepower",
            ObsoleteText: ""
        ));
        // BritishThermalUnitPerHour
        PowerUnits.TryAdd("BritishThermalUnitPerHour", new Unit(
            SingularName: "BritishThermalUnitPerHour",
            PluralName: "BritishThermalUnitsPerHour",
            Abbreviations: ["Btu/h", "Btu/hr"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 3600 / 1055.05585262,
            FromUnitToBase: static val => val * 1055.05585262 / 3600,
            Remarks: "Based on the International Table (IT) definition of the British thermal unit (BTU), where 1 BTU is defined as exactly 1055.05585262 joules (≈1.05506 kJ). See https://en.wikipedia.org/wiki/British_thermal_unit for details.",
            ObsoleteText: ""
        ));
        // KiloBritishThermalUnitPerHour
        PowerUnits.TryAdd("KiloBritishThermalUnitPerHour", new Unit(
            SingularName: "KiloBritishThermalUnitPerHour",
            PluralName: "KiloBritishThermalUnitsPerHour",
            Abbreviations: ["kBtu/h", "kBtu/hr"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600 / 1055.05585262) / 1000,
            FromUnitToBase: static val => (val * 1055.05585262 / 3600) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaBritishThermalUnitPerHour
        PowerUnits.TryAdd("MegaBritishThermalUnitPerHour", new Unit(
            SingularName: "MegaBritishThermalUnitPerHour",
            PluralName: "MegaBritishThermalUnitsPerHour",
            Abbreviations: ["MBtu/h", "MBtu/hr"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600 / 1055.05585262) / 1000000,
            FromUnitToBase: static val => (val * 1055.05585262 / 3600) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // JoulePerHour
        PowerUnits.TryAdd("JoulePerHour", new Unit(
            SingularName: "JoulePerHour",
            PluralName: "JoulesPerHour",
            Abbreviations: ["J/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliJoulePerHour
        PowerUnits.TryAdd("MilliJoulePerHour", new Unit(
            SingularName: "MilliJoulePerHour",
            PluralName: "MilliJoulesPerHour",
            Abbreviations: ["mJ/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600) / 0.001,
            FromUnitToBase: static val => (val / 3600) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerHour
        PowerUnits.TryAdd("KiloJoulePerHour", new Unit(
            SingularName: "KiloJoulePerHour",
            PluralName: "KiloJoulesPerHour",
            Abbreviations: ["kJ/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600) / 1000,
            FromUnitToBase: static val => (val / 3600) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerHour
        PowerUnits.TryAdd("MegaJoulePerHour", new Unit(
            SingularName: "MegaJoulePerHour",
            PluralName: "MegaJoulesPerHour",
            Abbreviations: ["MJ/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600) / 1000000,
            FromUnitToBase: static val => (val / 3600) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaJoulePerHour
        PowerUnits.TryAdd("GigaJoulePerHour", new Unit(
            SingularName: "GigaJoulePerHour",
            PluralName: "GigaJoulesPerHour",
            Abbreviations: ["GJ/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 3600) / 1000000000,
            FromUnitToBase: static val => (val / 3600) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonOfRefrigeration
        PowerUnits.TryAdd("TonOfRefrigeration", new Unit(
            SingularName: "TonOfRefrigeration",
            PluralName: "TonsOfRefrigeration",
            Abbreviations: ["TR"],
            Factor: 3516.853,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Power",
            "Watt",
            "In physics, power is the rate of doing work. It is equivalent to an amount of energy consumed per unit time.",
            PowerUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("Power", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
