// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPowerRatio() {
        // Loading PowerRatio
        var PowerRatioUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // DecibelWatt
        PowerRatioUnits.TryAdd("DecibelWatt", new Unit(
            SingularName: "DecibelWatt",
            PluralName: "DecibelWatts",
            Abbreviations: ["dBW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecibelMilliwatt
        PowerRatioUnits.TryAdd("DecibelMilliwatt", new Unit(
            SingularName: "DecibelMilliwatt",
            PluralName: "DecibelMilliwatts",
            Abbreviations: ["dBmW", "dBm"],
            Factor: 1,
            Offset: -30,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "PowerRatio",
            "DecibelWatt",
            "The strength of a signal expressed in decibels (dB) relative to one watt.",
            PowerRatioUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            true,
            1
        );
        _quantities.Add("PowerRatio", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
