// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPressureA() {
        // Loading PressureA
        var PressureAUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // BarA
        PressureAUnits.TryAdd("BarA", new Unit(
            SingularName: "BarA",
            PluralName: "BarsA",
            Abbreviations: ["bara"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5,
            FromUnitToBase: static val => val * 1e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerSquareInchA
        PressureAUnits.TryAdd("PoundForcePerSquareInchA", new Unit(
            SingularName: "PoundForcePerSquareInchA",
            PluralName: "PoundsForcePerSquareInchA",
            Abbreviations: ["psia"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6.894757293168361e3,
            FromUnitToBase: static val => val * 6.894757293168361e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerSquareCentimeterA
        PressureAUnits.TryAdd("KilogramForcePerSquareCentimeterA", new Unit(
            SingularName: "KilogramForcePerSquareCentimeterA",
            PluralName: "KilogramsForcePerSquareCentimeterA",
            Abbreviations: ["kgcm²a"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e4,
            FromUnitToBase: static val => val * 9.80665e4,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "PressureA",
            "Pascal",
            "",
            PressureAUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -1, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("PressureA", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
