// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPressureChangeRate() {
        // Loading PressureChangeRate
        var PressureChangeRateUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // PascalPerSecond
        PressureChangeRateUnits.TryAdd("PascalPerSecond", new Unit(
            SingularName: "PascalPerSecond",
            PluralName: "PascalsPerSecond",
            Abbreviations: ["Pa/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPascalPerSecond
        PressureChangeRateUnits.TryAdd("KiloPascalPerSecond", new Unit(
            SingularName: "KiloPascalPerSecond",
            PluralName: "KiloPascalsPerSecond",
            Abbreviations: ["kPa/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPascalPerSecond
        PressureChangeRateUnits.TryAdd("MegaPascalPerSecond", new Unit(
            SingularName: "MegaPascalPerSecond",
            PluralName: "MegaPascalsPerSecond",
            Abbreviations: ["MPa/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PascalPerMinute
        PressureChangeRateUnits.TryAdd("PascalPerMinute", new Unit(
            SingularName: "PascalPerMinute",
            PluralName: "PascalsPerMinute",
            Abbreviations: ["Pa/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPascalPerMinute
        PressureChangeRateUnits.TryAdd("KiloPascalPerMinute", new Unit(
            SingularName: "KiloPascalPerMinute",
            PluralName: "KiloPascalsPerMinute",
            Abbreviations: ["kPa/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60) / 1000,
            FromUnitToBase: static val => (val / 60) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPascalPerMinute
        PressureChangeRateUnits.TryAdd("MegaPascalPerMinute", new Unit(
            SingularName: "MegaPascalPerMinute",
            PluralName: "MegaPascalsPerMinute",
            Abbreviations: ["MPa/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60) / 1000000,
            FromUnitToBase: static val => (val / 60) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillimeterOfMercuryPerSecond
        PressureChangeRateUnits.TryAdd("MillimeterOfMercuryPerSecond", new Unit(
            SingularName: "MillimeterOfMercuryPerSecond",
            PluralName: "MillimetersOfMercuryPerSecond",
            Abbreviations: ["mmHg/s"],
            Factor: 133.322387415,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AtmospherePerSecond
        PressureChangeRateUnits.TryAdd("AtmospherePerSecond", new Unit(
            SingularName: "AtmospherePerSecond",
            PluralName: "AtmospheresPerSecond",
            Abbreviations: ["atm/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1.01325 * 1e5),
            FromUnitToBase: static val => val * 1.01325 * 1e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerSquareInchPerSecond
        PressureChangeRateUnits.TryAdd("PoundForcePerSquareInchPerSecond", new Unit(
            SingularName: "PoundForcePerSquareInchPerSecond",
            PluralName: "PoundsForcePerSquareInchPerSecond",
            Abbreviations: ["psi/s", "lb/in²/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.00064516 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 0.00064516,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForcePerSquareInchPerSecond
        PressureChangeRateUnits.TryAdd("KiloPoundForcePerSquareInchPerSecond", new Unit(
            SingularName: "KiloPoundForcePerSquareInchPerSecond",
            PluralName: "KiloPoundsForcePerSquareInchPerSecond",
            Abbreviations: ["ksi/s", "kipf/in²/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.00064516 / 4.4482216152605) / 1000,
            FromUnitToBase: static val => (val * 4.4482216152605 / 0.00064516) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPoundForcePerSquareInchPerSecond
        PressureChangeRateUnits.TryAdd("MegaPoundForcePerSquareInchPerSecond", new Unit(
            SingularName: "MegaPoundForcePerSquareInchPerSecond",
            PluralName: "MegaPoundsForcePerSquareInchPerSecond",
            Abbreviations: ["Mpsi/s", "Mlb/in²/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.00064516 / 4.4482216152605) / 1000000,
            FromUnitToBase: static val => (val * 4.4482216152605 / 0.00064516) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerSquareInchPerMinute
        PressureChangeRateUnits.TryAdd("PoundForcePerSquareInchPerMinute", new Unit(
            SingularName: "PoundForcePerSquareInchPerMinute",
            PluralName: "PoundsForcePerSquareInchPerMinute",
            Abbreviations: ["psi/min", "lb/in²/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 60 / (4.4482216152605 / 0.00064516),
            FromUnitToBase: static val => val * (4.4482216152605 / 0.00064516) / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForcePerSquareInchPerMinute
        PressureChangeRateUnits.TryAdd("KiloPoundForcePerSquareInchPerMinute", new Unit(
            SingularName: "KiloPoundForcePerSquareInchPerMinute",
            PluralName: "KiloPoundsForcePerSquareInchPerMinute",
            Abbreviations: ["ksi/min", "kipf/in²/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60 / (4.4482216152605 / 0.00064516)) / 1000,
            FromUnitToBase: static val => (val * (4.4482216152605 / 0.00064516) / 60) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPoundForcePerSquareInchPerMinute
        PressureChangeRateUnits.TryAdd("MegaPoundForcePerSquareInchPerMinute", new Unit(
            SingularName: "MegaPoundForcePerSquareInchPerMinute",
            PluralName: "MegaPoundsForcePerSquareInchPerMinute",
            Abbreviations: ["Mpsi/min", "Mlb/in²/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 60 / (4.4482216152605 / 0.00064516)) / 1000000,
            FromUnitToBase: static val => (val * (4.4482216152605 / 0.00064516) / 60) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BarPerSecond
        PressureChangeRateUnits.TryAdd("BarPerSecond", new Unit(
            SingularName: "BarPerSecond",
            PluralName: "BarsPerSecond",
            Abbreviations: ["bar/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5,
            FromUnitToBase: static val => val * 1e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliBarPerSecond
        PressureChangeRateUnits.TryAdd("MilliBarPerSecond", new Unit(
            SingularName: "MilliBarPerSecond",
            PluralName: "MilliBarsPerSecond",
            Abbreviations: ["mbar/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e5) / 0.001,
            FromUnitToBase: static val => (val * 1e5) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BarPerMinute
        PressureChangeRateUnits.TryAdd("BarPerMinute", new Unit(
            SingularName: "BarPerMinute",
            PluralName: "BarsPerMinute",
            Abbreviations: ["bar/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5 * 60,
            FromUnitToBase: static val => val * 1e5 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliBarPerMinute
        PressureChangeRateUnits.TryAdd("MilliBarPerMinute", new Unit(
            SingularName: "MilliBarPerMinute",
            PluralName: "MilliBarsPerMinute",
            Abbreviations: ["mbar/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e5 * 60) / 0.001,
            FromUnitToBase: static val => (val * 1e5 / 60) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "PressureChangeRate",
            "PascalPerSecond",
            "Pressure change rate is the ratio of the pressure change to the time during which the change occurred (value of pressure changes per unit time).",
            PressureChangeRateUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -1, ["M"] = 1, ["T"] = -3 },
            "",
            false,
            1
        );
        _quantities.Add("PressureChangeRate", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
