// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadPressureG() {
        // Loading PressureG
        var PressureGUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // BarG
        PressureGUnits.TryAdd("BarG", new Unit(
            SingularName: "BarG",
            PluralName: "BarsG",
            Abbreviations: ["barg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e5,
            FromUnitToBase: static val => val * 1e5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerSquareInchG
        PressureGUnits.TryAdd("PoundForcePerSquareInchG", new Unit(
            SingularName: "PoundForcePerSquareInchG",
            PluralName: "PoundsForcePerSquareInchG",
            Abbreviations: ["psig"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 6.894757293168361e3,
            FromUnitToBase: static val => val * 6.894757293168361e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerSquareCentimeterG
        PressureGUnits.TryAdd("KilogramForcePerSquareCentimeterG", new Unit(
            SingularName: "KilogramForcePerSquareCentimeterG",
            PluralName: "KilogramsForcePerSquareCentimeterG",
            Abbreviations: ["kgcm²g"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e4,
            FromUnitToBase: static val => val * 9.80665e4,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "PressureG",
            "Pascal",
            "",
            PressureGUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -1, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("PressureG", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
