// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadRadiationExposure() {
        // Loading RadiationExposure
        var RadiationExposureUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CoulombPerKilogram
        RadiationExposureUnits.TryAdd("CoulombPerKilogram", new Unit(
            SingularName: "CoulombPerKilogram",
            PluralName: "CoulombsPerKilogram",
            Abbreviations: ["C/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoCoulombPerKilogram
        RadiationExposureUnits.TryAdd("PicoCoulombPerKilogram", new Unit(
            SingularName: "PicoCoulombPerKilogram",
            PluralName: "PicoCoulombsPerKilogram",
            Abbreviations: ["pC/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoCoulombPerKilogram
        RadiationExposureUnits.TryAdd("NanoCoulombPerKilogram", new Unit(
            SingularName: "NanoCoulombPerKilogram",
            PluralName: "NanoCoulombsPerKilogram",
            Abbreviations: ["nC/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroCoulombPerKilogram
        RadiationExposureUnits.TryAdd("MicroCoulombPerKilogram", new Unit(
            SingularName: "MicroCoulombPerKilogram",
            PluralName: "MicroCoulombsPerKilogram",
            Abbreviations: ["µC/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliCoulombPerKilogram
        RadiationExposureUnits.TryAdd("MilliCoulombPerKilogram", new Unit(
            SingularName: "MilliCoulombPerKilogram",
            PluralName: "MilliCoulombsPerKilogram",
            Abbreviations: ["mC/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Roentgen
        RadiationExposureUnits.TryAdd("Roentgen", new Unit(
            SingularName: "Roentgen",
            PluralName: "Roentgens",
            Abbreviations: ["R"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 2.58e-4,
            FromUnitToBase: static val => val * 2.58e-4,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroRoentgen
        RadiationExposureUnits.TryAdd("MicroRoentgen", new Unit(
            SingularName: "MicroRoentgen",
            PluralName: "MicroRoentgens",
            Abbreviations: ["µR"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 2.58e-4) / 1E-06,
            FromUnitToBase: static val => (val * 2.58e-4) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliRoentgen
        RadiationExposureUnits.TryAdd("MilliRoentgen", new Unit(
            SingularName: "MilliRoentgen",
            PluralName: "MilliRoentgens",
            Abbreviations: ["mR"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 2.58e-4) / 0.001,
            FromUnitToBase: static val => (val * 2.58e-4) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "RadiationExposure",
            "CoulombPerKilogram",
            "Radiation exposure is a measure of the ionization of air due to ionizing radiation from photons.",
            RadiationExposureUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = -1, ["T"] = 1, ["I"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("RadiationExposure", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
