// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadRadioactivity() {
        // Loading Radioactivity
        var RadioactivityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Becquerel
        RadioactivityUnits.TryAdd("Becquerel", new Unit(
            SingularName: "Becquerel",
            PluralName: "Becquerels",
            Abbreviations: ["Bq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoBecquerel
        RadioactivityUnits.TryAdd("PicoBecquerel", new Unit(
            SingularName: "PicoBecquerel",
            PluralName: "PicoBecquerels",
            Abbreviations: ["pBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoBecquerel
        RadioactivityUnits.TryAdd("NanoBecquerel", new Unit(
            SingularName: "NanoBecquerel",
            PluralName: "NanoBecquerels",
            Abbreviations: ["nBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroBecquerel
        RadioactivityUnits.TryAdd("MicroBecquerel", new Unit(
            SingularName: "MicroBecquerel",
            PluralName: "MicroBecquerels",
            Abbreviations: ["µBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliBecquerel
        RadioactivityUnits.TryAdd("MilliBecquerel", new Unit(
            SingularName: "MilliBecquerel",
            PluralName: "MilliBecquerels",
            Abbreviations: ["mBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloBecquerel
        RadioactivityUnits.TryAdd("KiloBecquerel", new Unit(
            SingularName: "KiloBecquerel",
            PluralName: "KiloBecquerels",
            Abbreviations: ["kBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaBecquerel
        RadioactivityUnits.TryAdd("MegaBecquerel", new Unit(
            SingularName: "MegaBecquerel",
            PluralName: "MegaBecquerels",
            Abbreviations: ["MBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaBecquerel
        RadioactivityUnits.TryAdd("GigaBecquerel", new Unit(
            SingularName: "GigaBecquerel",
            PluralName: "GigaBecquerels",
            Abbreviations: ["GBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000,
            FromUnitToBase: static val => (val) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraBecquerel
        RadioactivityUnits.TryAdd("TeraBecquerel", new Unit(
            SingularName: "TeraBecquerel",
            PluralName: "TeraBecquerels",
            Abbreviations: ["TBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000,
            FromUnitToBase: static val => (val) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PetaBecquerel
        RadioactivityUnits.TryAdd("PetaBecquerel", new Unit(
            SingularName: "PetaBecquerel",
            PluralName: "PetaBecquerels",
            Abbreviations: ["PBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000000000000,
            FromUnitToBase: static val => (val) * 1000000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // ExaBecquerel
        RadioactivityUnits.TryAdd("ExaBecquerel", new Unit(
            SingularName: "ExaBecquerel",
            PluralName: "ExaBecquerels",
            Abbreviations: ["EBq"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E+18,
            FromUnitToBase: static val => (val) * 1E+18,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Curie
        RadioactivityUnits.TryAdd("Curie", new Unit(
            SingularName: "Curie",
            PluralName: "Curies",
            Abbreviations: ["Ci"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 3.7e10,
            FromUnitToBase: static val => val * 3.7e10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoCurie
        RadioactivityUnits.TryAdd("PicoCurie", new Unit(
            SingularName: "PicoCurie",
            PluralName: "PicoCuries",
            Abbreviations: ["pCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1E-12,
            FromUnitToBase: static val => (val * 3.7e10) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoCurie
        RadioactivityUnits.TryAdd("NanoCurie", new Unit(
            SingularName: "NanoCurie",
            PluralName: "NanoCuries",
            Abbreviations: ["nCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1E-09,
            FromUnitToBase: static val => (val * 3.7e10) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroCurie
        RadioactivityUnits.TryAdd("MicroCurie", new Unit(
            SingularName: "MicroCurie",
            PluralName: "MicroCuries",
            Abbreviations: ["µCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1E-06,
            FromUnitToBase: static val => (val * 3.7e10) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliCurie
        RadioactivityUnits.TryAdd("MilliCurie", new Unit(
            SingularName: "MilliCurie",
            PluralName: "MilliCuries",
            Abbreviations: ["mCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 0.001,
            FromUnitToBase: static val => (val * 3.7e10) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCurie
        RadioactivityUnits.TryAdd("KiloCurie", new Unit(
            SingularName: "KiloCurie",
            PluralName: "KiloCuries",
            Abbreviations: ["kCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1000,
            FromUnitToBase: static val => (val * 3.7e10) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaCurie
        RadioactivityUnits.TryAdd("MegaCurie", new Unit(
            SingularName: "MegaCurie",
            PluralName: "MegaCuries",
            Abbreviations: ["MCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1000000,
            FromUnitToBase: static val => (val * 3.7e10) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaCurie
        RadioactivityUnits.TryAdd("GigaCurie", new Unit(
            SingularName: "GigaCurie",
            PluralName: "GigaCuries",
            Abbreviations: ["GCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1000000000,
            FromUnitToBase: static val => (val * 3.7e10) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraCurie
        RadioactivityUnits.TryAdd("TeraCurie", new Unit(
            SingularName: "TeraCurie",
            PluralName: "TeraCuries",
            Abbreviations: ["TCi"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.7e10) / 1000000000000,
            FromUnitToBase: static val => (val * 3.7e10) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Rutherford
        RadioactivityUnits.TryAdd("Rutherford", new Unit(
            SingularName: "Rutherford",
            PluralName: "Rutherfords",
            Abbreviations: ["Rd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e6,
            FromUnitToBase: static val => val * 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoRutherford
        RadioactivityUnits.TryAdd("PicoRutherford", new Unit(
            SingularName: "PicoRutherford",
            PluralName: "PicoRutherfords",
            Abbreviations: ["pRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1E-12,
            FromUnitToBase: static val => (val * 1e6) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoRutherford
        RadioactivityUnits.TryAdd("NanoRutherford", new Unit(
            SingularName: "NanoRutherford",
            PluralName: "NanoRutherfords",
            Abbreviations: ["nRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1E-09,
            FromUnitToBase: static val => (val * 1e6) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroRutherford
        RadioactivityUnits.TryAdd("MicroRutherford", new Unit(
            SingularName: "MicroRutherford",
            PluralName: "MicroRutherfords",
            Abbreviations: ["µRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1E-06,
            FromUnitToBase: static val => (val * 1e6) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliRutherford
        RadioactivityUnits.TryAdd("MilliRutherford", new Unit(
            SingularName: "MilliRutherford",
            PluralName: "MilliRutherfords",
            Abbreviations: ["mRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 0.001,
            FromUnitToBase: static val => (val * 1e6) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloRutherford
        RadioactivityUnits.TryAdd("KiloRutherford", new Unit(
            SingularName: "KiloRutherford",
            PluralName: "KiloRutherfords",
            Abbreviations: ["kRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1000,
            FromUnitToBase: static val => (val * 1e6) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaRutherford
        RadioactivityUnits.TryAdd("MegaRutherford", new Unit(
            SingularName: "MegaRutherford",
            PluralName: "MegaRutherfords",
            Abbreviations: ["MRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1000000,
            FromUnitToBase: static val => (val * 1e6) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaRutherford
        RadioactivityUnits.TryAdd("GigaRutherford", new Unit(
            SingularName: "GigaRutherford",
            PluralName: "GigaRutherfords",
            Abbreviations: ["GRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1000000000,
            FromUnitToBase: static val => (val * 1e6) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraRutherford
        RadioactivityUnits.TryAdd("TeraRutherford", new Unit(
            SingularName: "TeraRutherford",
            PluralName: "TeraRutherfords",
            Abbreviations: ["TRd"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 1e6) / 1000000000000,
            FromUnitToBase: static val => (val * 1e6) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Radioactivity",
            "Becquerel",
            "Amount of ionizing radiation released when an element spontaneously emits energy as a result of the radioactive decay of an unstable atom per unit time.",
            RadioactivityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("Radioactivity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
