// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadRadiationEquivalentDose() {
        // Loading RadiationEquivalentDose
        var RadiationEquivalentDoseUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Sievert
        RadiationEquivalentDoseUnits.TryAdd("Sievert", new Unit(
            SingularName: "Sievert",
            PluralName: "Sieverts",
            Abbreviations: ["Sv"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "https://en.wikipedia.org/wiki/Sievert",
            ObsoleteText: ""
        ));
        // NanoSievert
        RadiationEquivalentDoseUnits.TryAdd("NanoSievert", new Unit(
            SingularName: "NanoSievert",
            PluralName: "NanoSieverts",
            Abbreviations: ["nSv"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroSievert
        RadiationEquivalentDoseUnits.TryAdd("MicroSievert", new Unit(
            SingularName: "MicroSievert",
            PluralName: "MicroSieverts",
            Abbreviations: ["µSv"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliSievert
        RadiationEquivalentDoseUnits.TryAdd("MilliSievert", new Unit(
            SingularName: "MilliSievert",
            PluralName: "MilliSieverts",
            Abbreviations: ["mSv"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // RoentgenEquivalentMan
        RadiationEquivalentDoseUnits.TryAdd("RoentgenEquivalentMan", new Unit(
            SingularName: "RoentgenEquivalentMan",
            PluralName: "RoentgensEquivalentMan",
            Abbreviations: ["rem"],
            Factor: 0.01,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliRoentgenEquivalentMan
        RadiationEquivalentDoseUnits.TryAdd("MilliRoentgenEquivalentMan", new Unit(
            SingularName: "MilliRoentgenEquivalentMan",
            PluralName: "MilliRoentgensEquivalentMan",
            Abbreviations: ["mrem"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 100) / 0.001,
            FromUnitToBase: static val => (val / 100) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "RadiationEquivalentDose",
            "Sievert",
            "Equivalent dose is a dose quantity representing the stochastic health effects of low levels of ionizing radiation on the human body which represents the probability of radiation-induced cancer and genetic damage.",
            RadiationEquivalentDoseUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("RadiationEquivalentDose", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
