// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadRatioChangeRate() {
        // Loading RatioChangeRate
        var RatioChangeRateUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // PercentPerSecond
        RatioChangeRateUnits.TryAdd("PercentPerSecond", new Unit(
            SingularName: "PercentPerSecond",
            PluralName: "PercentsPerSecond",
            Abbreviations: ["%/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e2,
            FromUnitToBase: static val => val / 1e2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecimalFractionPerSecond
        RatioChangeRateUnits.TryAdd("DecimalFractionPerSecond", new Unit(
            SingularName: "DecimalFractionPerSecond",
            PluralName: "DecimalFractionsPerSecond",
            Abbreviations: ["/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "RatioChangeRate",
            "DecimalFractionPerSecond",
            "The change in ratio per unit of time.",
            RatioChangeRateUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("RatioChangeRate", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
