// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadReactiveEnergy() {
        // Loading ReactiveEnergy
        var ReactiveEnergyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // VoltampereReactiveHour
        ReactiveEnergyUnits.TryAdd("VoltampereReactiveHour", new Unit(
            SingularName: "VoltampereReactiveHour",
            PluralName: "VoltampereReactiveHours",
            Abbreviations: ["varh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloVoltampereReactiveHour
        ReactiveEnergyUnits.TryAdd("KiloVoltampereReactiveHour", new Unit(
            SingularName: "KiloVoltampereReactiveHour",
            PluralName: "KiloVoltampereReactiveHours",
            Abbreviations: ["kvarh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaVoltampereReactiveHour
        ReactiveEnergyUnits.TryAdd("MegaVoltampereReactiveHour", new Unit(
            SingularName: "MegaVoltampereReactiveHour",
            PluralName: "MegaVoltampereReactiveHours",
            Abbreviations: ["Mvarh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ReactiveEnergy",
            "VoltampereReactiveHour",
            "The Volt-ampere reactive hour (expressed as varh) is the reactive power of one Volt-ampere reactive produced in one hour.",
            ReactiveEnergyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["M"] = 1, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("ReactiveEnergy", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
