// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadReciprocalLength() {
        // Loading ReciprocalLength
        var ReciprocalLengthUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // InverseMeter
        ReciprocalLengthUnits.TryAdd("InverseMeter", new Unit(
            SingularName: "InverseMeter",
            PluralName: "InverseMeters",
            Abbreviations: ["m⁻¹", "1/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseCentimeter
        ReciprocalLengthUnits.TryAdd("InverseCentimeter", new Unit(
            SingularName: "InverseCentimeter",
            PluralName: "InverseCentimeters",
            Abbreviations: ["cm⁻¹", "1/cm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e2,
            FromUnitToBase: static val => val * 1e2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMillimeter
        ReciprocalLengthUnits.TryAdd("InverseMillimeter", new Unit(
            SingularName: "InverseMillimeter",
            PluralName: "InverseMillimeters",
            Abbreviations: ["mm⁻¹", "1/mm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e3,
            FromUnitToBase: static val => val * 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMile
        ReciprocalLengthUnits.TryAdd("InverseMile", new Unit(
            SingularName: "InverseMile",
            PluralName: "InverseMiles",
            Abbreviations: ["mi⁻¹", "1/mi"],
            Factor: 0.0006213711922373339,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseYard
        ReciprocalLengthUnits.TryAdd("InverseYard", new Unit(
            SingularName: "InverseYard",
            PluralName: "InverseYards",
            Abbreviations: ["yd⁻¹", "1/yd"],
            Factor: 1.0936132983377078,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseFoot
        ReciprocalLengthUnits.TryAdd("InverseFoot", new Unit(
            SingularName: "InverseFoot",
            PluralName: "InverseFeet",
            Abbreviations: ["ft⁻¹", "1/ft"],
            Factor: 3.280839895013123,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseUsSurveyFoot
        ReciprocalLengthUnits.TryAdd("InverseUsSurveyFoot", new Unit(
            SingularName: "InverseUsSurveyFoot",
            PluralName: "InverseUsSurveyFeet",
            Abbreviations: ["ftUS⁻¹", "1/ftUS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1200 / 3937,
            FromUnitToBase: static val => val * 3937 / 1200,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseInch
        ReciprocalLengthUnits.TryAdd("InverseInch", new Unit(
            SingularName: "InverseInch",
            PluralName: "InverseInches",
            Abbreviations: ["in⁻¹", "1/in"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-2,
            FromUnitToBase: static val => val / 2.54e-2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMil
        ReciprocalLengthUnits.TryAdd("InverseMil", new Unit(
            SingularName: "InverseMil",
            PluralName: "InverseMils",
            Abbreviations: ["mil⁻¹", "1/mil"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-5,
            FromUnitToBase: static val => val / 2.54e-5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // InverseMicroinch
        ReciprocalLengthUnits.TryAdd("InverseMicroinch", new Unit(
            SingularName: "InverseMicroinch",
            PluralName: "InverseMicroinches",
            Abbreviations: ["µin⁻¹", "1/µin"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 2.54e-8,
            FromUnitToBase: static val => val / 2.54e-8,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ReciprocalLength",
            "InverseMeter",
            "Reciprocal (Inverse) Length is used in various fields of science and mathematics. It is defined as the inverse value of a length unit.",
            ReciprocalLengthUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("ReciprocalLength", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
