// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadRotationalStiffnessPerLength() {
        // Loading RotationalStiffnessPerLength
        var RotationalStiffnessPerLengthUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // NewtonMeterPerRadianPerMeter
        RotationalStiffnessPerLengthUnits.TryAdd("NewtonMeterPerRadianPerMeter", new Unit(
            SingularName: "NewtonMeterPerRadianPerMeter",
            PluralName: "NewtonMetersPerRadianPerMeter",
            Abbreviations: ["N·m/rad/m", "Nm/rad/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonMeterPerRadianPerMeter
        RotationalStiffnessPerLengthUnits.TryAdd("KiloNewtonMeterPerRadianPerMeter", new Unit(
            SingularName: "KiloNewtonMeterPerRadianPerMeter",
            PluralName: "KiloNewtonMetersPerRadianPerMeter",
            Abbreviations: ["kN·m/rad/m", "kNm/rad/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonMeterPerRadianPerMeter
        RotationalStiffnessPerLengthUnits.TryAdd("MegaNewtonMeterPerRadianPerMeter", new Unit(
            SingularName: "MegaNewtonMeterPerRadianPerMeter",
            PluralName: "MegaNewtonMetersPerRadianPerMeter",
            Abbreviations: ["MN·m/rad/m", "MNm/rad/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForceFootPerDegreesPerFoot
        RotationalStiffnessPerLengthUnits.TryAdd("PoundForceFootPerDegreesPerFoot", new Unit(
            SingularName: "PoundForceFootPerDegreesPerFoot",
            PluralName: "PoundForceFeetPerDegreesPerFeet",
            Abbreviations: ["lbf·ft/deg/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (4.4482216152605 * 180 / Math.PI),
            FromUnitToBase: static val => val * (4.4482216152605 * 180 / Math.PI),
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilopoundForceFootPerDegreesPerFoot
        RotationalStiffnessPerLengthUnits.TryAdd("KilopoundForceFootPerDegreesPerFoot", new Unit(
            SingularName: "KilopoundForceFootPerDegreesPerFoot",
            PluralName: "KilopoundForceFeetPerDegreesPerFeet",
            Abbreviations: ["kipf·ft/°/ft", "kip·ft/°/ft", "k·ft/°/ft", "kipf·ft/deg/ft", "kip·ft/deg/ft", "k·ft/deg/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (4.4482216152605e3 * 180 / Math.PI),
            FromUnitToBase: static val => val * (4.4482216152605e3 * 180 / Math.PI),
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "RotationalStiffnessPerLength",
            "NewtonMeterPerRadianPerMeter",
            "https://en.wikipedia.org/wiki/Stiffness#Rotational_stiffness",
            RotationalStiffnessPerLengthUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("RotationalStiffnessPerLength", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
