// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadScalar() {
        // Loading Scalar
        var ScalarUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Amount
        ScalarUnits.TryAdd("Amount", new Unit(
            SingularName: "Amount",
            PluralName: "Amount",
            Abbreviations: [""],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Scalar",
            "Amount",
            "A way of representing a number of items.",
            ScalarUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("Scalar", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
