// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadSpecificEnergy() {
        // Loading SpecificEnergy
        var SpecificEnergyUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // JoulePerKilogram
        SpecificEnergyUnits.TryAdd("JoulePerKilogram", new Unit(
            SingularName: "JoulePerKilogram",
            PluralName: "JoulesPerKilogram",
            Abbreviations: ["J/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerKilogram
        SpecificEnergyUnits.TryAdd("KiloJoulePerKilogram", new Unit(
            SingularName: "KiloJoulePerKilogram",
            PluralName: "KiloJoulesPerKilogram",
            Abbreviations: ["kJ/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerKilogram
        SpecificEnergyUnits.TryAdd("MegaJoulePerKilogram", new Unit(
            SingularName: "MegaJoulePerKilogram",
            PluralName: "MegaJoulesPerKilogram",
            Abbreviations: ["MJ/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegajoulePerTonne
        SpecificEnergyUnits.TryAdd("MegajoulePerTonne", new Unit(
            SingularName: "MegajoulePerTonne",
            PluralName: "MegajoulesPerTonne",
            Abbreviations: ["MJ/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e3,
            FromUnitToBase: static val => val * 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CaloriePerGram
        SpecificEnergyUnits.TryAdd("CaloriePerGram", new Unit(
            SingularName: "CaloriePerGram",
            PluralName: "CaloriesPerGram",
            Abbreviations: ["cal/g"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 4.184e3,
            FromUnitToBase: static val => val * 4.184e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCaloriePerGram
        SpecificEnergyUnits.TryAdd("KiloCaloriePerGram", new Unit(
            SingularName: "KiloCaloriePerGram",
            PluralName: "KiloCaloriesPerGram",
            Abbreviations: ["kcal/g"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.184e3) / 1000,
            FromUnitToBase: static val => (val * 4.184e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattHourPerKilogram
        SpecificEnergyUnits.TryAdd("WattHourPerKilogram", new Unit(
            SingularName: "WattHourPerKilogram",
            PluralName: "WattHoursPerKilogram",
            Abbreviations: ["Wh/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 3.6e3,
            FromUnitToBase: static val => val * 3.6e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattHourPerKilogram
        SpecificEnergyUnits.TryAdd("KiloWattHourPerKilogram", new Unit(
            SingularName: "KiloWattHourPerKilogram",
            PluralName: "KiloWattHoursPerKilogram",
            Abbreviations: ["kWh/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e3) / 1000,
            FromUnitToBase: static val => (val * 3.6e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattHourPerKilogram
        SpecificEnergyUnits.TryAdd("MegaWattHourPerKilogram", new Unit(
            SingularName: "MegaWattHourPerKilogram",
            PluralName: "MegaWattHoursPerKilogram",
            Abbreviations: ["MWh/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e3) / 1000000,
            FromUnitToBase: static val => (val * 3.6e3) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattHourPerKilogram
        SpecificEnergyUnits.TryAdd("GigaWattHourPerKilogram", new Unit(
            SingularName: "GigaWattHourPerKilogram",
            PluralName: "GigaWattHoursPerKilogram",
            Abbreviations: ["GWh/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 3.6e3) / 1000000000,
            FromUnitToBase: static val => (val * 3.6e3) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattDayPerKilogram
        SpecificEnergyUnits.TryAdd("WattDayPerKilogram", new Unit(
            SingularName: "WattDayPerKilogram",
            PluralName: "WattDaysPerKilogram",
            Abbreviations: ["Wd/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (24 * 3.6e3),
            FromUnitToBase: static val => val * (24 * 3.6e3),
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattDayPerKilogram
        SpecificEnergyUnits.TryAdd("KiloWattDayPerKilogram", new Unit(
            SingularName: "KiloWattDayPerKilogram",
            PluralName: "KiloWattDaysPerKilogram",
            Abbreviations: ["kWd/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3.6e3)) / 1000,
            FromUnitToBase: static val => (val * (24 * 3.6e3)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattDayPerKilogram
        SpecificEnergyUnits.TryAdd("MegaWattDayPerKilogram", new Unit(
            SingularName: "MegaWattDayPerKilogram",
            PluralName: "MegaWattDaysPerKilogram",
            Abbreviations: ["MWd/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3.6e3)) / 1000000,
            FromUnitToBase: static val => (val * (24 * 3.6e3)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattDayPerKilogram
        SpecificEnergyUnits.TryAdd("GigaWattDayPerKilogram", new Unit(
            SingularName: "GigaWattDayPerKilogram",
            PluralName: "GigaWattDaysPerKilogram",
            Abbreviations: ["GWd/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3.6e3)) / 1000000000,
            FromUnitToBase: static val => (val * (24 * 3.6e3)) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattDayPerKilogram
        SpecificEnergyUnits.TryAdd("TeraWattDayPerKilogram", new Unit(
            SingularName: "TeraWattDayPerKilogram",
            PluralName: "TeraWattDaysPerKilogram",
            Abbreviations: ["TWd/kg"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (24 * 3.6e3)) / 1000000000000,
            FromUnitToBase: static val => (val * (24 * 3.6e3)) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattDayPerTonne
        SpecificEnergyUnits.TryAdd("WattDayPerTonne", new Unit(
            SingularName: "WattDayPerTonne",
            PluralName: "WattDaysPerTonne",
            Abbreviations: ["Wd/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / ((24 * 3.6e3) / 1e3),
            FromUnitToBase: static val => val * ((24 * 3.6e3) / 1e3),
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattDayPerTonne
        SpecificEnergyUnits.TryAdd("KiloWattDayPerTonne", new Unit(
            SingularName: "KiloWattDayPerTonne",
            PluralName: "KiloWattDaysPerTonne",
            Abbreviations: ["kWd/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 1e3)) / 1000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 1e3)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattDayPerTonne
        SpecificEnergyUnits.TryAdd("MegaWattDayPerTonne", new Unit(
            SingularName: "MegaWattDayPerTonne",
            PluralName: "MegaWattDaysPerTonne",
            Abbreviations: ["MWd/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 1e3)) / 1000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 1e3)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattDayPerTonne
        SpecificEnergyUnits.TryAdd("GigaWattDayPerTonne", new Unit(
            SingularName: "GigaWattDayPerTonne",
            PluralName: "GigaWattDaysPerTonne",
            Abbreviations: ["GWd/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 1e3)) / 1000000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 1e3)) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattDayPerTonne
        SpecificEnergyUnits.TryAdd("TeraWattDayPerTonne", new Unit(
            SingularName: "TeraWattDayPerTonne",
            PluralName: "TeraWattDaysPerTonne",
            Abbreviations: ["TWd/t"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 1e3)) / 1000000000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 1e3)) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattDayPerShortTon
        SpecificEnergyUnits.TryAdd("WattDayPerShortTon", new Unit(
            SingularName: "WattDayPerShortTon",
            PluralName: "WattDaysPerShortTon",
            Abbreviations: ["Wd/ST"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / ((24 * 3.6e3) / 9.0718474e2),
            FromUnitToBase: static val => val * ((24 * 3.6e3) / 9.0718474e2),
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattDayPerShortTon
        SpecificEnergyUnits.TryAdd("KiloWattDayPerShortTon", new Unit(
            SingularName: "KiloWattDayPerShortTon",
            PluralName: "KiloWattDaysPerShortTon",
            Abbreviations: ["kWd/ST"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 9.0718474e2)) / 1000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 9.0718474e2)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattDayPerShortTon
        SpecificEnergyUnits.TryAdd("MegaWattDayPerShortTon", new Unit(
            SingularName: "MegaWattDayPerShortTon",
            PluralName: "MegaWattDaysPerShortTon",
            Abbreviations: ["MWd/ST"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 9.0718474e2)) / 1000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 9.0718474e2)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattDayPerShortTon
        SpecificEnergyUnits.TryAdd("GigaWattDayPerShortTon", new Unit(
            SingularName: "GigaWattDayPerShortTon",
            PluralName: "GigaWattDaysPerShortTon",
            Abbreviations: ["GWd/ST"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 9.0718474e2)) / 1000000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 9.0718474e2)) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TeraWattDayPerShortTon
        SpecificEnergyUnits.TryAdd("TeraWattDayPerShortTon", new Unit(
            SingularName: "TeraWattDayPerShortTon",
            PluralName: "TeraWattDaysPerShortTon",
            Abbreviations: ["TWd/ST"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / ((24 * 3.6e3) / 9.0718474e2)) / 1000000000000,
            FromUnitToBase: static val => (val * ((24 * 3.6e3) / 9.0718474e2)) * 1000000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // WattHourPerPound
        SpecificEnergyUnits.TryAdd("WattHourPerPound", new Unit(
            SingularName: "WattHourPerPound",
            PluralName: "WattHoursPerPound",
            Abbreviations: ["Wh/lbs"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 7.93664e3,
            FromUnitToBase: static val => val * 7.93664e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloWattHourPerPound
        SpecificEnergyUnits.TryAdd("KiloWattHourPerPound", new Unit(
            SingularName: "KiloWattHourPerPound",
            PluralName: "KiloWattHoursPerPound",
            Abbreviations: ["kWh/lbs"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 7.93664e3) / 1000,
            FromUnitToBase: static val => (val * 7.93664e3) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaWattHourPerPound
        SpecificEnergyUnits.TryAdd("MegaWattHourPerPound", new Unit(
            SingularName: "MegaWattHourPerPound",
            PluralName: "MegaWattHoursPerPound",
            Abbreviations: ["MWh/lbs"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 7.93664e3) / 1000000,
            FromUnitToBase: static val => (val * 7.93664e3) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // GigaWattHourPerPound
        SpecificEnergyUnits.TryAdd("GigaWattHourPerPound", new Unit(
            SingularName: "GigaWattHourPerPound",
            PluralName: "GigaWattHoursPerPound",
            Abbreviations: ["GWh/lbs"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 7.93664e3) / 1000000000,
            FromUnitToBase: static val => (val * 7.93664e3) * 1000000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BtuPerPound
        SpecificEnergyUnits.TryAdd("BtuPerPound", new Unit(
            SingularName: "BtuPerPound",
            PluralName: "BtuPerPound",
            Abbreviations: ["btu/lb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.45359237 / 1055.05585262,
            FromUnitToBase: static val => val * 1055.05585262 / 0.45359237,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "SpecificEnergy",
            "JoulePerKilogram",
            "The SpecificEnergy",
            SpecificEnergyUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 2, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("SpecificEnergy", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
