// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadSpecificWeight() {
        // Loading SpecificWeight
        var SpecificWeightUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // NewtonPerCubicMillimeter
        SpecificWeightUnits.TryAdd("NewtonPerCubicMillimeter", new Unit(
            SingularName: "NewtonPerCubicMillimeter",
            PluralName: "NewtonsPerCubicMillimeter",
            Abbreviations: ["N/mm³"],
            Factor: 1000000000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerCubicMillimeter
        SpecificWeightUnits.TryAdd("KiloNewtonPerCubicMillimeter", new Unit(
            SingularName: "KiloNewtonPerCubicMillimeter",
            PluralName: "KiloNewtonsPerCubicMillimeter",
            Abbreviations: ["kN/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.000000001) / 1000,
            FromUnitToBase: static val => (val * 1000000000) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonPerCubicCentimeter
        SpecificWeightUnits.TryAdd("NewtonPerCubicCentimeter", new Unit(
            SingularName: "NewtonPerCubicCentimeter",
            PluralName: "NewtonsPerCubicCentimeter",
            Abbreviations: ["N/cm³"],
            Factor: 1000000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerCubicCentimeter
        SpecificWeightUnits.TryAdd("KiloNewtonPerCubicCentimeter", new Unit(
            SingularName: "KiloNewtonPerCubicCentimeter",
            PluralName: "KiloNewtonsPerCubicCentimeter",
            Abbreviations: ["kN/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.000001) / 1000,
            FromUnitToBase: static val => (val * 1000000) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonPerCubicMeter
        SpecificWeightUnits.TryAdd("NewtonPerCubicMeter", new Unit(
            SingularName: "NewtonPerCubicMeter",
            PluralName: "NewtonsPerCubicMeter",
            Abbreviations: ["N/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonPerCubicMeter
        SpecificWeightUnits.TryAdd("KiloNewtonPerCubicMeter", new Unit(
            SingularName: "KiloNewtonPerCubicMeter",
            PluralName: "KiloNewtonsPerCubicMeter",
            Abbreviations: ["kN/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonPerCubicMeter
        SpecificWeightUnits.TryAdd("MegaNewtonPerCubicMeter", new Unit(
            SingularName: "MegaNewtonPerCubicMeter",
            PluralName: "MegaNewtonsPerCubicMeter",
            Abbreviations: ["MN/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerCubicMillimeter
        SpecificWeightUnits.TryAdd("KilogramForcePerCubicMillimeter", new Unit(
            SingularName: "KilogramForcePerCubicMillimeter",
            PluralName: "KilogramsForcePerCubicMillimeter",
            Abbreviations: ["kgf/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e9,
            FromUnitToBase: static val => val * 9.80665e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerCubicCentimeter
        SpecificWeightUnits.TryAdd("KilogramForcePerCubicCentimeter", new Unit(
            SingularName: "KilogramForcePerCubicCentimeter",
            PluralName: "KilogramsForcePerCubicCentimeter",
            Abbreviations: ["kgf/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e6,
            FromUnitToBase: static val => val * 9.80665e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForcePerCubicMeter
        SpecificWeightUnits.TryAdd("KilogramForcePerCubicMeter", new Unit(
            SingularName: "KilogramForcePerCubicMeter",
            PluralName: "KilogramsForcePerCubicMeter",
            Abbreviations: ["kgf/m³"],
            Factor: 9.80665,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerCubicInch
        SpecificWeightUnits.TryAdd("PoundForcePerCubicInch", new Unit(
            SingularName: "PoundForcePerCubicInch",
            PluralName: "PoundsForcePerCubicInch",
            Abbreviations: ["lbf/in³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1.6387064e-5 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 1.6387064e-5,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForcePerCubicInch
        SpecificWeightUnits.TryAdd("KiloPoundForcePerCubicInch", new Unit(
            SingularName: "KiloPoundForcePerCubicInch",
            PluralName: "KiloPoundsForcePerCubicInch",
            Abbreviations: ["kipf/in³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1.6387064e-5 / 4.4482216152605) / 1000,
            FromUnitToBase: static val => (val * 4.4482216152605 / 1.6387064e-5) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForcePerCubicFoot
        SpecificWeightUnits.TryAdd("PoundForcePerCubicFoot", new Unit(
            SingularName: "PoundForcePerCubicFoot",
            PluralName: "PoundsForcePerCubicFoot",
            Abbreviations: ["lbf/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 0.028316846592 / 4.4482216152605,
            FromUnitToBase: static val => val * 4.4482216152605 / 0.028316846592,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForcePerCubicFoot
        SpecificWeightUnits.TryAdd("KiloPoundForcePerCubicFoot", new Unit(
            SingularName: "KiloPoundForcePerCubicFoot",
            PluralName: "KiloPoundsForcePerCubicFoot",
            Abbreviations: ["kipf/ft³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 0.028316846592 / 4.4482216152605) / 1000,
            FromUnitToBase: static val => (val * 4.4482216152605 / 0.028316846592) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerCubicMillimeter
        SpecificWeightUnits.TryAdd("TonneForcePerCubicMillimeter", new Unit(
            SingularName: "TonneForcePerCubicMillimeter",
            PluralName: "TonnesForcePerCubicMillimeter",
            Abbreviations: ["tf/mm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e12,
            FromUnitToBase: static val => val * 9.80665e12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerCubicCentimeter
        SpecificWeightUnits.TryAdd("TonneForcePerCubicCentimeter", new Unit(
            SingularName: "TonneForcePerCubicCentimeter",
            PluralName: "TonnesForcePerCubicCentimeter",
            Abbreviations: ["tf/cm³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e9,
            FromUnitToBase: static val => val * 9.80665e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForcePerCubicMeter
        SpecificWeightUnits.TryAdd("TonneForcePerCubicMeter", new Unit(
            SingularName: "TonneForcePerCubicMeter",
            PluralName: "TonnesForcePerCubicMeter",
            Abbreviations: ["tf/m³"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 9.80665e3,
            FromUnitToBase: static val => val * 9.80665e3,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "SpecificWeight",
            "NewtonPerCubicMeter",
            "The SpecificWeight, or more precisely, the volumetric weight density, of a substance is its weight per unit volume.",
            SpecificWeightUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("SpecificWeight", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
