// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadStandardVolumeFlow() {
        // Loading StandardVolumeFlow
        var StandardVolumeFlowUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // StandardCubicMeterPerSecond
        StandardVolumeFlowUnits.TryAdd("StandardCubicMeterPerSecond", new Unit(
            SingularName: "StandardCubicMeterPerSecond",
            PluralName: "StandardCubicMetersPerSecond",
            Abbreviations: ["Sm³/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicMeterPerMinute
        StandardVolumeFlowUnits.TryAdd("StandardCubicMeterPerMinute", new Unit(
            SingularName: "StandardCubicMeterPerMinute",
            PluralName: "StandardCubicMetersPerMinute",
            Abbreviations: ["Sm³/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicMeterPerHour
        StandardVolumeFlowUnits.TryAdd("StandardCubicMeterPerHour", new Unit(
            SingularName: "StandardCubicMeterPerHour",
            PluralName: "StandardCubicMetersPerHour",
            Abbreviations: ["Sm³/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicMeterPerDay
        StandardVolumeFlowUnits.TryAdd("StandardCubicMeterPerDay", new Unit(
            SingularName: "StandardCubicMeterPerDay",
            PluralName: "StandardCubicMetersPerDay",
            Abbreviations: ["Sm³/d"],
            Factor: 1.1574074074074073E-05,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicCentimeterPerMinute
        StandardVolumeFlowUnits.TryAdd("StandardCubicCentimeterPerMinute", new Unit(
            SingularName: "StandardCubicCentimeterPerMinute",
            PluralName: "StandardCubicCentimetersPerMinute",
            Abbreviations: ["sccm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 6e7,
            FromUnitToBase: static val => val / 6e7,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardLiterPerMinute
        StandardVolumeFlowUnits.TryAdd("StandardLiterPerMinute", new Unit(
            SingularName: "StandardLiterPerMinute",
            PluralName: "StandardLitersPerMinute",
            Abbreviations: ["slm"],
            Factor: 1.6666666666666667E-05,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicFootPerSecond
        StandardVolumeFlowUnits.TryAdd("StandardCubicFootPerSecond", new Unit(
            SingularName: "StandardCubicFootPerSecond",
            PluralName: "StandardCubicFeetPerSecond",
            Abbreviations: ["Sft³/s"],
            Factor: 0.028316846592,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicFootPerMinute
        StandardVolumeFlowUnits.TryAdd("StandardCubicFootPerMinute", new Unit(
            SingularName: "StandardCubicFootPerMinute",
            PluralName: "StandardCubicFeetPerMinute",
            Abbreviations: ["scfm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.028316846592 / 60),
            FromUnitToBase: static val => val * 0.028316846592 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // StandardCubicFootPerHour
        StandardVolumeFlowUnits.TryAdd("StandardCubicFootPerHour", new Unit(
            SingularName: "StandardCubicFootPerHour",
            PluralName: "StandardCubicFeetPerHour",
            Abbreviations: ["scfh"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.028316846592 / 3600),
            FromUnitToBase: static val => val * 0.028316846592 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "StandardVolumeFlow",
            "StandardCubicMeterPerSecond",
            "The molar flow rate of a gas corrected to standardized conditions of temperature and pressure thus representing a fixed number of moles of gas regardless of composition and actual flow conditions.",
            StandardVolumeFlowUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("StandardVolumeFlow", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
