// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadTemperatureChangeRate() {
        // Loading TemperatureChangeRate
        var TemperatureChangeRateUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // DegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("DegreeCelsiusPerSecond", new Unit(
            SingularName: "DegreeCelsiusPerSecond",
            PluralName: "DegreesCelsiusPerSecond",
            Abbreviations: ["°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("NanoDegreeCelsiusPerSecond", new Unit(
            SingularName: "NanoDegreeCelsiusPerSecond",
            PluralName: "NanoDegreesCelsiusPerSecond",
            Abbreviations: ["n°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("MicroDegreeCelsiusPerSecond", new Unit(
            SingularName: "MicroDegreeCelsiusPerSecond",
            PluralName: "MicroDegreesCelsiusPerSecond",
            Abbreviations: ["µ°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("MilliDegreeCelsiusPerSecond", new Unit(
            SingularName: "MilliDegreeCelsiusPerSecond",
            PluralName: "MilliDegreesCelsiusPerSecond",
            Abbreviations: ["m°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("CentiDegreeCelsiusPerSecond", new Unit(
            SingularName: "CentiDegreeCelsiusPerSecond",
            PluralName: "CentiDegreesCelsiusPerSecond",
            Abbreviations: ["c°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("DeciDegreeCelsiusPerSecond", new Unit(
            SingularName: "DeciDegreeCelsiusPerSecond",
            PluralName: "DeciDegreesCelsiusPerSecond",
            Abbreviations: ["d°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("DecaDegreeCelsiusPerSecond", new Unit(
            SingularName: "DecaDegreeCelsiusPerSecond",
            PluralName: "DecaDegreesCelsiusPerSecond",
            Abbreviations: ["da°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 10,
            FromUnitToBase: static val => (val) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("HectoDegreeCelsiusPerSecond", new Unit(
            SingularName: "HectoDegreeCelsiusPerSecond",
            PluralName: "HectoDegreesCelsiusPerSecond",
            Abbreviations: ["h°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 100,
            FromUnitToBase: static val => (val) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloDegreeCelsiusPerSecond
        TemperatureChangeRateUnits.TryAdd("KiloDegreeCelsiusPerSecond", new Unit(
            SingularName: "KiloDegreeCelsiusPerSecond",
            PluralName: "KiloDegreesCelsiusPerSecond",
            Abbreviations: ["k°C/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeCelsiusPerMinute
        TemperatureChangeRateUnits.TryAdd("DegreeCelsiusPerMinute", new Unit(
            SingularName: "DegreeCelsiusPerMinute",
            PluralName: "DegreesCelsiusPerMinute",
            Abbreviations: ["°C/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeKelvinPerMinute
        TemperatureChangeRateUnits.TryAdd("DegreeKelvinPerMinute", new Unit(
            SingularName: "DegreeKelvinPerMinute",
            PluralName: "DegreesKelvinPerMinute",
            Abbreviations: ["K/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeFahrenheitPerMinute
        TemperatureChangeRateUnits.TryAdd("DegreeFahrenheitPerMinute", new Unit(
            SingularName: "DegreeFahrenheitPerMinute",
            PluralName: "DegreesFahrenheitPerMinute",
            Abbreviations: ["°F/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9 / 5 * 60,
            FromUnitToBase: static val => val * 5 / 9 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeFahrenheitPerSecond
        TemperatureChangeRateUnits.TryAdd("DegreeFahrenheitPerSecond", new Unit(
            SingularName: "DegreeFahrenheitPerSecond",
            PluralName: "DegreesFahrenheitPerSecond",
            Abbreviations: ["°F/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9 / 5,
            FromUnitToBase: static val => val * 5 / 9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeKelvinPerSecond
        TemperatureChangeRateUnits.TryAdd("DegreeKelvinPerSecond", new Unit(
            SingularName: "DegreeKelvinPerSecond",
            PluralName: "DegreesKelvinPerSecond",
            Abbreviations: ["K/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeCelsiusPerHour
        TemperatureChangeRateUnits.TryAdd("DegreeCelsiusPerHour", new Unit(
            SingularName: "DegreeCelsiusPerHour",
            PluralName: "DegreesCelsiusPerHour",
            Abbreviations: ["°C/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeKelvinPerHour
        TemperatureChangeRateUnits.TryAdd("DegreeKelvinPerHour", new Unit(
            SingularName: "DegreeKelvinPerHour",
            PluralName: "DegreesKelvinPerHour",
            Abbreviations: ["K/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeFahrenheitPerHour
        TemperatureChangeRateUnits.TryAdd("DegreeFahrenheitPerHour", new Unit(
            SingularName: "DegreeFahrenheitPerHour",
            PluralName: "DegreesFahrenheitPerHour",
            Abbreviations: ["°F/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9 / 5 * 3600,
            FromUnitToBase: static val => val * 5 / 9 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "TemperatureChangeRate",
            "DegreeCelsiusPerSecond",
            "Temperature change rate is the ratio of the temperature change to the time during which the change occurred (value of temperature changes per unit time).",
            TemperatureChangeRateUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["T"] = -1, ["Θ"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("TemperatureChangeRate", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
