// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadTemperature() {
        // Loading Temperature
        var TemperatureUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // Kelvin
        TemperatureUnits.TryAdd("Kelvin", new Unit(
            SingularName: "Kelvin",
            PluralName: "Kelvins",
            Abbreviations: ["K"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeCelsius
        TemperatureUnits.TryAdd("DegreeCelsius", new Unit(
            SingularName: "DegreeCelsius",
            PluralName: "DegreesCelsius",
            Abbreviations: ["°C"],
            Factor: 1,
            Offset: 273.15,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillidegreeCelsius
        TemperatureUnits.TryAdd("MillidegreeCelsius", new Unit(
            SingularName: "MillidegreeCelsius",
            PluralName: "MillidegreesCelsius",
            Abbreviations: ["m°C"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - 273.15) * 1000,
            FromUnitToBase: static val => val / 1000 + 273.15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeDelisle
        TemperatureUnits.TryAdd("DegreeDelisle", new Unit(
            SingularName: "DegreeDelisle",
            PluralName: "DegreesDelisle",
            Abbreviations: ["°De"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - 373.15) * -3 / 2,
            FromUnitToBase: static val => val * -2 / 3 + 373.15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeFahrenheit
        TemperatureUnits.TryAdd("DegreeFahrenheit", new Unit(
            SingularName: "DegreeFahrenheit",
            PluralName: "DegreesFahrenheit",
            Abbreviations: ["°F"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - 459.67 * 5 / 9) * 9 / 5,
            FromUnitToBase: static val => val * 5 / 9 + 459.67 * 5 / 9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeNewton
        TemperatureUnits.TryAdd("DegreeNewton", new Unit(
            SingularName: "DegreeNewton",
            PluralName: "DegreesNewton",
            Abbreviations: ["°N"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - 273.15) * 33 / 100,
            FromUnitToBase: static val => val * 100 / 33 + 273.15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeRankine
        TemperatureUnits.TryAdd("DegreeRankine", new Unit(
            SingularName: "DegreeRankine",
            PluralName: "DegreesRankine",
            Abbreviations: ["°R"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9 / 5,
            FromUnitToBase: static val => val * 5 / 9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeReaumur
        TemperatureUnits.TryAdd("DegreeReaumur", new Unit(
            SingularName: "DegreeReaumur",
            PluralName: "DegreesReaumur",
            Abbreviations: ["°Ré"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - 273.15) * 4 / 5,
            FromUnitToBase: static val => val * 5 / 4 + 273.15,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeRoemer
        TemperatureUnits.TryAdd("DegreeRoemer", new Unit(
            SingularName: "DegreeRoemer",
            PluralName: "DegreesRoemer",
            Abbreviations: ["°Rø"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val - (273.15 - 7.5 * 40d / 21)) * 21 / 40,
            FromUnitToBase: static val => val * 40 / 21 + 273.15 - 7.5 * 40d / 21,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SolarTemperature
        TemperatureUnits.TryAdd("SolarTemperature", new Unit(
            SingularName: "SolarTemperature",
            PluralName: "SolarTemperatures",
            Abbreviations: ["T⊙"],
            Factor: 5778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "Temperature",
            "Kelvin",
            "A temperature is a numerical measure of hot or cold. Its measurement is by detection of heat radiation or particle velocity or kinetic energy, or by the bulk behavior of a thermometric material. It may be calibrated in any of various temperature scales, Celsius, Fahrenheit, Kelvin, etc. The fundamental physical definition of temperature is provided by thermodynamics.",
            TemperatureUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["Θ"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("Temperature", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
