// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadThermalConductivity() {
        // Loading ThermalConductivity
        var ThermalConductivityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // WattPerMeterKelvin
        ThermalConductivityUnits.TryAdd("WattPerMeterKelvin", new Unit(
            SingularName: "WattPerMeterKelvin",
            PluralName: "WattsPerMeterKelvin",
            Abbreviations: ["W/(m·K)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BtuPerHourFootFahrenheit
        ThermalConductivityUnits.TryAdd("BtuPerHourFootFahrenheit", new Unit(
            SingularName: "BtuPerHourFootFahrenheit",
            PluralName: "BtusPerHourFootFahrenheit",
            Abbreviations: ["BTU/(h·ft·°F)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / ((1055.05585262 / (0.3048 * 3600)) * 1.8),
            FromUnitToBase: static val => val * ((1055.05585262 / (0.3048 * 3600)) * 1.8),
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ThermalConductivity",
            "WattPerMeterKelvin",
            "Thermal conductivity is the property of a material to conduct heat.",
            ThermalConductivityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = 1, ["T"] = -3, ["Θ"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("ThermalConductivity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
