// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadThermalResistance() {
        // Loading ThermalResistance
        var ThermalResistanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // KelvinPerWatt
        ThermalResistanceUnits.TryAdd("KelvinPerWatt", new Unit(
            SingularName: "KelvinPerWatt",
            PluralName: "KelvinsPerWatt",
            Abbreviations: ["K/W"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DegreeCelsiusPerWatt
        ThermalResistanceUnits.TryAdd("DegreeCelsiusPerWatt", new Unit(
            SingularName: "DegreeCelsiusPerWatt",
            PluralName: "DegreesCelsiusPerWatt",
            Abbreviations: ["°C/W"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ThermalResistance",
            "KelvinPerWatt",
            "Thermal resistance (R) measures the opposition to the heat current in a material or system. It is measured in units of kelvins per watt (K/W) and indicates how much temperature difference (in kelvins) is required to transfer a unit of heat current (in watts) through the material or object. It is essential to optimize the building insulation, evaluate the efficiency of electronic devices, and enhance the performance of heat sinks in various applications.",
            ThermalResistanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = -2, ["M"] = -1, ["T"] = 3, ["Θ"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ThermalResistance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
