// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadThermalInsulance() {
        // Loading ThermalInsulance
        var ThermalInsulanceUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // SquareMeterKelvinPerKilowatt
        ThermalInsulanceUnits.TryAdd("SquareMeterKelvinPerKilowatt", new Unit(
            SingularName: "SquareMeterKelvinPerKilowatt",
            PluralName: "SquareMeterKelvinsPerKilowatt",
            Abbreviations: ["m²K/kW"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMeterKelvinPerWatt
        ThermalInsulanceUnits.TryAdd("SquareMeterKelvinPerWatt", new Unit(
            SingularName: "SquareMeterKelvinPerWatt",
            PluralName: "SquareMeterKelvinsPerWatt",
            Abbreviations: ["m²K/W"],
            Factor: 1000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMeterDegreeCelsiusPerWatt
        ThermalInsulanceUnits.TryAdd("SquareMeterDegreeCelsiusPerWatt", new Unit(
            SingularName: "SquareMeterDegreeCelsiusPerWatt",
            PluralName: "SquareMeterDegreesCelsiusPerWatt",
            Abbreviations: ["m²°C/W"],
            Factor: 1000,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareCentimeterKelvinPerWatt
        ThermalInsulanceUnits.TryAdd("SquareCentimeterKelvinPerWatt", new Unit(
            SingularName: "SquareCentimeterKelvinPerWatt",
            PluralName: "SquareCentimeterKelvinsPerWatt",
            Abbreviations: ["cm²K/W"],
            Factor: 0.1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareMillimeterKelvinPerWatt
        ThermalInsulanceUnits.TryAdd("SquareMillimeterKelvinPerWatt", new Unit(
            SingularName: "SquareMillimeterKelvinPerWatt",
            PluralName: "SquareMillimeterKelvinsPerWatt",
            Abbreviations: ["mm²K/W"],
            Factor: 0.001,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // SquareCentimeterHourDegreeCelsiusPerKilocalorie
        ThermalInsulanceUnits.TryAdd("SquareCentimeterHourDegreeCelsiusPerKilocalorie", new Unit(
            SingularName: "SquareCentimeterHourDegreeCelsiusPerKilocalorie",
            PluralName: "SquareCentimeterHourDegreesCelsiusPerKilocalorie",
            Abbreviations: ["cm²Hr°C/kcal"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 4.184 / (0.0001 * 3600),
            FromUnitToBase: static val => val * (0.0001 * 3600) / 4.184,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HourSquareFeetDegreeFahrenheitPerBtu
        ThermalInsulanceUnits.TryAdd("HourSquareFeetDegreeFahrenheitPerBtu", new Unit(
            SingularName: "HourSquareFeetDegreeFahrenheitPerBtu",
            PluralName: "HourSquareFeetDegreesFahrenheitPerBtu",
            Abbreviations: ["Hrft²°F/Btu"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (1055.05585262 * 1.8) / (1000 * 0.3048 * 0.3048 * 3600),
            FromUnitToBase: static val => val * (1000 * 0.3048 * 0.3048 * 3600) / (1055.05585262 * 1.8),
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "ThermalInsulance",
            "SquareMeterKelvinPerKilowatt",
            "Thermal insulance (R-value) is a measure of a material's resistance to the heat current. It quantifies how effectively a material can resist the transfer of heat through conduction, convection, and radiation. It has the units square metre kelvins per watt (m2⋅K/W) in SI units or square foot degree Fahrenheit–hours per British thermal unit (ft2⋅°F⋅h/Btu) in imperial units. The higher the thermal insulance, the better a material insulates against heat transfer. It is commonly used in construction to assess the insulation properties of materials such as walls, roofs, and insulation products.",
            ThermalInsulanceUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = -1, ["T"] = 3, ["Θ"] = 1 },
            "",
            false,
            1
        );
        _quantities.Add("ThermalInsulance", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
