// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadTorquePerLength() {
        // Loading TorquePerLength
        var TorquePerLengthUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // NewtonMillimeterPerMeter
        TorquePerLengthUnits.TryAdd("NewtonMillimeterPerMeter", new Unit(
            SingularName: "NewtonMillimeterPerMeter",
            PluralName: "NewtonMillimetersPerMeter",
            Abbreviations: ["N·mm/m"],
            Factor: 0.001,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonMillimeterPerMeter
        TorquePerLengthUnits.TryAdd("KiloNewtonMillimeterPerMeter", new Unit(
            SingularName: "KiloNewtonMillimeterPerMeter",
            PluralName: "KiloNewtonMillimetersPerMeter",
            Abbreviations: ["kN·mm/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1000,
            FromUnitToBase: static val => (val * 0.001) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonMillimeterPerMeter
        TorquePerLengthUnits.TryAdd("MegaNewtonMillimeterPerMeter", new Unit(
            SingularName: "MegaNewtonMillimeterPerMeter",
            PluralName: "MegaNewtonMillimetersPerMeter",
            Abbreviations: ["MN·mm/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1000000,
            FromUnitToBase: static val => (val * 0.001) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonCentimeterPerMeter
        TorquePerLengthUnits.TryAdd("NewtonCentimeterPerMeter", new Unit(
            SingularName: "NewtonCentimeterPerMeter",
            PluralName: "NewtonCentimetersPerMeter",
            Abbreviations: ["N·cm/m"],
            Factor: 0.01,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonCentimeterPerMeter
        TorquePerLengthUnits.TryAdd("KiloNewtonCentimeterPerMeter", new Unit(
            SingularName: "KiloNewtonCentimeterPerMeter",
            PluralName: "KiloNewtonCentimetersPerMeter",
            Abbreviations: ["kN·cm/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 100) / 1000,
            FromUnitToBase: static val => (val * 0.01) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonCentimeterPerMeter
        TorquePerLengthUnits.TryAdd("MegaNewtonCentimeterPerMeter", new Unit(
            SingularName: "MegaNewtonCentimeterPerMeter",
            PluralName: "MegaNewtonCentimetersPerMeter",
            Abbreviations: ["MN·cm/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 100) / 1000000,
            FromUnitToBase: static val => (val * 0.01) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NewtonMeterPerMeter
        TorquePerLengthUnits.TryAdd("NewtonMeterPerMeter", new Unit(
            SingularName: "NewtonMeterPerMeter",
            PluralName: "NewtonMetersPerMeter",
            Abbreviations: ["N·m/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloNewtonMeterPerMeter
        TorquePerLengthUnits.TryAdd("KiloNewtonMeterPerMeter", new Unit(
            SingularName: "KiloNewtonMeterPerMeter",
            PluralName: "KiloNewtonMetersPerMeter",
            Abbreviations: ["kN·m/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaNewtonMeterPerMeter
        TorquePerLengthUnits.TryAdd("MegaNewtonMeterPerMeter", new Unit(
            SingularName: "MegaNewtonMeterPerMeter",
            PluralName: "MegaNewtonMetersPerMeter",
            Abbreviations: ["MN·m/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForceInchPerFoot
        TorquePerLengthUnits.TryAdd("PoundForceInchPerFoot", new Unit(
            SingularName: "PoundForceInchPerFoot",
            PluralName: "PoundForceInchesPerFoot",
            Abbreviations: ["lbf·in/ft"],
            Factor: 0.370685147638,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForceInchPerFoot
        TorquePerLengthUnits.TryAdd("KiloPoundForceInchPerFoot", new Unit(
            SingularName: "KiloPoundForceInchPerFoot",
            PluralName: "KiloPoundForceInchesPerFoot",
            Abbreviations: ["kipf·in/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 0.370685147638) / 1000,
            FromUnitToBase: static val => (val * 0.370685147638) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPoundForceInchPerFoot
        TorquePerLengthUnits.TryAdd("MegaPoundForceInchPerFoot", new Unit(
            SingularName: "MegaPoundForceInchPerFoot",
            PluralName: "MegaPoundForceInchesPerFoot",
            Abbreviations: ["Mlbf·in/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 0.370685147638) / 1000000,
            FromUnitToBase: static val => (val * 0.370685147638) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PoundForceFootPerFoot
        TorquePerLengthUnits.TryAdd("PoundForceFootPerFoot", new Unit(
            SingularName: "PoundForceFootPerFoot",
            PluralName: "PoundForceFeetPerFoot",
            Abbreviations: ["lbf·ft/ft"],
            Factor: 4.44822161526,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloPoundForceFootPerFoot
        TorquePerLengthUnits.TryAdd("KiloPoundForceFootPerFoot", new Unit(
            SingularName: "KiloPoundForceFootPerFoot",
            PluralName: "KiloPoundForceFeetPerFoot",
            Abbreviations: ["kipf·ft/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.44822161526) / 1000,
            FromUnitToBase: static val => (val * 4.44822161526) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaPoundForceFootPerFoot
        TorquePerLengthUnits.TryAdd("MegaPoundForceFootPerFoot", new Unit(
            SingularName: "MegaPoundForceFootPerFoot",
            PluralName: "MegaPoundForceFeetPerFoot",
            Abbreviations: ["Mlbf·ft/ft"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.44822161526) / 1000000,
            FromUnitToBase: static val => (val * 4.44822161526) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForceMillimeterPerMeter
        TorquePerLengthUnits.TryAdd("KilogramForceMillimeterPerMeter", new Unit(
            SingularName: "KilogramForceMillimeterPerMeter",
            PluralName: "KilogramForceMillimetersPerMeter",
            Abbreviations: ["kgf·mm/m"],
            Factor: 0.00980665019960652,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForceCentimeterPerMeter
        TorquePerLengthUnits.TryAdd("KilogramForceCentimeterPerMeter", new Unit(
            SingularName: "KilogramForceCentimeterPerMeter",
            PluralName: "KilogramForceCentimetersPerMeter",
            Abbreviations: ["kgf·cm/m"],
            Factor: 0.0980665019960652,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilogramForceMeterPerMeter
        TorquePerLengthUnits.TryAdd("KilogramForceMeterPerMeter", new Unit(
            SingularName: "KilogramForceMeterPerMeter",
            PluralName: "KilogramForceMetersPerMeter",
            Abbreviations: ["kgf·m/m"],
            Factor: 9.80665019960652,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForceMillimeterPerMeter
        TorquePerLengthUnits.TryAdd("TonneForceMillimeterPerMeter", new Unit(
            SingularName: "TonneForceMillimeterPerMeter",
            PluralName: "TonneForceMillimetersPerMeter",
            Abbreviations: ["tf·mm/m"],
            Factor: 9.80665019960652,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForceCentimeterPerMeter
        TorquePerLengthUnits.TryAdd("TonneForceCentimeterPerMeter", new Unit(
            SingularName: "TonneForceCentimeterPerMeter",
            PluralName: "TonneForceCentimetersPerMeter",
            Abbreviations: ["tf·cm/m"],
            Factor: 98.0665019960652,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // TonneForceMeterPerMeter
        TorquePerLengthUnits.TryAdd("TonneForceMeterPerMeter", new Unit(
            SingularName: "TonneForceMeterPerMeter",
            PluralName: "TonneForceMetersPerMeter",
            Abbreviations: ["tf·m/m"],
            Factor: 9806.65019960653,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "TorquePerLength",
            "NewtonMeterPerMeter",
            "The magnitude of torque per unit length.",
            TorquePerLengthUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["M"] = 1, ["T"] = -2 },
            "",
            false,
            1
        );
        _quantities.Add("TorquePerLength", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
