// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadVitaminA() {
        // Loading VitaminA
        var VitaminAUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // InternationalUnit
        VitaminAUnits.TryAdd("InternationalUnit", new Unit(
            SingularName: "InternationalUnit",
            PluralName: "InternationalUnits",
            Abbreviations: ["IU"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "VitaminA",
            "InternationalUnit",
            "Vitamin A: 1 IU is the biological equivalent of 0.3 µg retinol, or of 0.6 µg beta-carotene.",
            VitaminAUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("VitaminA", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
