// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadVolumetricHeatCapacity() {
        // Loading VolumetricHeatCapacity
        var VolumetricHeatCapacityUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // JoulePerCubicMeterKelvin
        VolumetricHeatCapacityUnits.TryAdd("JoulePerCubicMeterKelvin", new Unit(
            SingularName: "JoulePerCubicMeterKelvin",
            PluralName: "JoulesPerCubicMeterKelvin",
            Abbreviations: ["J/(m³·K)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerCubicMeterKelvin
        VolumetricHeatCapacityUnits.TryAdd("KiloJoulePerCubicMeterKelvin", new Unit(
            SingularName: "KiloJoulePerCubicMeterKelvin",
            PluralName: "KiloJoulesPerCubicMeterKelvin",
            Abbreviations: ["kJ/(m³·K)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerCubicMeterKelvin
        VolumetricHeatCapacityUnits.TryAdd("MegaJoulePerCubicMeterKelvin", new Unit(
            SingularName: "MegaJoulePerCubicMeterKelvin",
            PluralName: "MegaJoulesPerCubicMeterKelvin",
            Abbreviations: ["MJ/(m³·K)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // JoulePerCubicMeterDegreeCelsius
        VolumetricHeatCapacityUnits.TryAdd("JoulePerCubicMeterDegreeCelsius", new Unit(
            SingularName: "JoulePerCubicMeterDegreeCelsius",
            PluralName: "JoulesPerCubicMeterDegreeCelsius",
            Abbreviations: ["J/(m³·°C)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloJoulePerCubicMeterDegreeCelsius
        VolumetricHeatCapacityUnits.TryAdd("KiloJoulePerCubicMeterDegreeCelsius", new Unit(
            SingularName: "KiloJoulePerCubicMeterDegreeCelsius",
            PluralName: "KiloJoulesPerCubicMeterDegreeCelsius",
            Abbreviations: ["kJ/(m³·°C)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000,
            FromUnitToBase: static val => (val) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaJoulePerCubicMeterDegreeCelsius
        VolumetricHeatCapacityUnits.TryAdd("MegaJoulePerCubicMeterDegreeCelsius", new Unit(
            SingularName: "MegaJoulePerCubicMeterDegreeCelsius",
            PluralName: "MegaJoulesPerCubicMeterDegreeCelsius",
            Abbreviations: ["MJ/(m³·°C)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1000000,
            FromUnitToBase: static val => (val) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CaloriePerCubicCentimeterDegreeCelsius
        VolumetricHeatCapacityUnits.TryAdd("CaloriePerCubicCentimeterDegreeCelsius", new Unit(
            SingularName: "CaloriePerCubicCentimeterDegreeCelsius",
            PluralName: "CaloriesPerCubicCentimeterDegreeCelsius",
            Abbreviations: ["cal/(cm³·°C)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 4.184e6,
            FromUnitToBase: static val => val * 4.184e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloCaloriePerCubicCentimeterDegreeCelsius
        VolumetricHeatCapacityUnits.TryAdd("KiloCaloriePerCubicCentimeterDegreeCelsius", new Unit(
            SingularName: "KiloCaloriePerCubicCentimeterDegreeCelsius",
            PluralName: "KiloCaloriesPerCubicCentimeterDegreeCelsius",
            Abbreviations: ["kcal/(cm³·°C)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 4.184e6) / 1000,
            FromUnitToBase: static val => (val * 4.184e6) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // BtuPerCubicFootDegreeFahrenheit
        VolumetricHeatCapacityUnits.TryAdd("BtuPerCubicFootDegreeFahrenheit", new Unit(
            SingularName: "BtuPerCubicFootDegreeFahrenheit",
            PluralName: "BtusPerCubicFootDegreeFahrenheit",
            Abbreviations: ["BTU/(ft³·°F)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / ((1055.05585262 / 0.028316846592) * 1.8),
            FromUnitToBase: static val => val * (1055.05585262 / 0.028316846592) * 1.8,
            Remarks: "Based on the International Table (IT) definition of the British thermal unit (BTU), where 1 BTU is defined as exactly 1055.05585262 joules (≈1.05506 kJ). See https://en.wikipedia.org/wiki/British_thermal_unit for details.",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "VolumetricHeatCapacity",
            "JoulePerCubicMeterKelvin",
            "The volumetric heat capacity is the amount of energy that must be added, in the form of heat, to one unit of volume of the material in order to cause an increase of one unit in its temperature.",
            VolumetricHeatCapacityUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["M"] = 1, ["L"] = -1, ["T"] = -2, ["Θ"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("VolumetricHeatCapacity", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
