// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadVolumeFlowPerArea() {
        // Loading VolumeFlowPerArea
        var VolumeFlowPerAreaUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CubicMeterPerSecondPerSquareMeter
        VolumeFlowPerAreaUnits.TryAdd("CubicMeterPerSecondPerSquareMeter", new Unit(
            SingularName: "CubicMeterPerSecondPerSquareMeter",
            PluralName: "CubicMetersPerSecondPerSquareMeter",
            Abbreviations: ["m³/(s·m²)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicFootPerMinutePerSquareFoot
        VolumeFlowPerAreaUnits.TryAdd("CubicFootPerMinutePerSquareFoot", new Unit(
            SingularName: "CubicFootPerMinutePerSquareFoot",
            PluralName: "CubicFeetPerMinutePerSquareFoot",
            Abbreviations: ["CFM/ft²"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 9.290304e-2 / (0.028316846592 / 60),
            FromUnitToBase: static val => val * (0.028316846592 / 60) / 9.290304e-2,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "VolumeFlowPerArea",
            "CubicMeterPerSecondPerSquareMeter",
            "",
            VolumeFlowPerAreaUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 1, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("VolumeFlowPerArea", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
