// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadVolumeConcentration() {
        // Loading VolumeConcentration
        var VolumeConcentrationUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // DecimalFraction
        VolumeConcentrationUnits.TryAdd("DecimalFraction", new Unit(
            SingularName: "DecimalFraction",
            PluralName: "DecimalFractions",
            Abbreviations: [""],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerLiter
        VolumeConcentrationUnits.TryAdd("LiterPerLiter", new Unit(
            SingularName: "LiterPerLiter",
            PluralName: "LitersPerLiter",
            Abbreviations: ["l/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoLiterPerLiter
        VolumeConcentrationUnits.TryAdd("PicoLiterPerLiter", new Unit(
            SingularName: "PicoLiterPerLiter",
            PluralName: "PicoLitersPerLiter",
            Abbreviations: ["pl/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-12,
            FromUnitToBase: static val => (val) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerLiter
        VolumeConcentrationUnits.TryAdd("NanoLiterPerLiter", new Unit(
            SingularName: "NanoLiterPerLiter",
            PluralName: "NanoLitersPerLiter",
            Abbreviations: ["nl/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-09,
            FromUnitToBase: static val => (val) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerLiter
        VolumeConcentrationUnits.TryAdd("MicroLiterPerLiter", new Unit(
            SingularName: "MicroLiterPerLiter",
            PluralName: "MicroLitersPerLiter",
            Abbreviations: ["µl/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 1E-06,
            FromUnitToBase: static val => (val) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerLiter
        VolumeConcentrationUnits.TryAdd("MilliLiterPerLiter", new Unit(
            SingularName: "MilliLiterPerLiter",
            PluralName: "MilliLitersPerLiter",
            Abbreviations: ["ml/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.001,
            FromUnitToBase: static val => (val) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerLiter
        VolumeConcentrationUnits.TryAdd("CentiLiterPerLiter", new Unit(
            SingularName: "CentiLiterPerLiter",
            PluralName: "CentiLitersPerLiter",
            Abbreviations: ["cl/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.01,
            FromUnitToBase: static val => (val) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerLiter
        VolumeConcentrationUnits.TryAdd("DeciLiterPerLiter", new Unit(
            SingularName: "DeciLiterPerLiter",
            PluralName: "DeciLitersPerLiter",
            Abbreviations: ["dl/l"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val) / 0.1,
            FromUnitToBase: static val => (val) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("LiterPerMilliliter", new Unit(
            SingularName: "LiterPerMilliliter",
            PluralName: "LitersPerMilliliter",
            Abbreviations: ["l/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e-3,
            FromUnitToBase: static val => val / 1e-3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PicoLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("PicoLiterPerMilliliter", new Unit(
            SingularName: "PicoLiterPerMilliliter",
            PluralName: "PicoLitersPerMilliliter",
            Abbreviations: ["pl/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-12,
            FromUnitToBase: static val => (val / 1e-3) * 1E-12,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("NanoLiterPerMilliliter", new Unit(
            SingularName: "NanoLiterPerMilliliter",
            PluralName: "NanoLitersPerMilliliter",
            Abbreviations: ["nl/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-09,
            FromUnitToBase: static val => (val / 1e-3) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("MicroLiterPerMilliliter", new Unit(
            SingularName: "MicroLiterPerMilliliter",
            PluralName: "MicroLitersPerMilliliter",
            Abbreviations: ["µl/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 1E-06,
            FromUnitToBase: static val => (val / 1e-3) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("MilliLiterPerMilliliter", new Unit(
            SingularName: "MilliLiterPerMilliliter",
            PluralName: "MilliLitersPerMilliliter",
            Abbreviations: ["ml/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.001,
            FromUnitToBase: static val => (val / 1e-3) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("CentiLiterPerMilliliter", new Unit(
            SingularName: "CentiLiterPerMilliliter",
            PluralName: "CentiLitersPerMilliliter",
            Abbreviations: ["cl/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.01,
            FromUnitToBase: static val => (val / 1e-3) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerMilliliter
        VolumeConcentrationUnits.TryAdd("DeciLiterPerMilliliter", new Unit(
            SingularName: "DeciLiterPerMilliliter",
            PluralName: "DeciLitersPerMilliliter",
            Abbreviations: ["dl/ml"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1e-3) / 0.1,
            FromUnitToBase: static val => (val / 1e-3) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // Percent
        VolumeConcentrationUnits.TryAdd("Percent", new Unit(
            SingularName: "Percent",
            PluralName: "Percent",
            Abbreviations: ["%", "% (v/v)"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e2,
            FromUnitToBase: static val => val / 1e2,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PartPerThousand
        VolumeConcentrationUnits.TryAdd("PartPerThousand", new Unit(
            SingularName: "PartPerThousand",
            PluralName: "PartsPerThousand",
            Abbreviations: ["‰"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e3,
            FromUnitToBase: static val => val / 1e3,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PartPerMillion
        VolumeConcentrationUnits.TryAdd("PartPerMillion", new Unit(
            SingularName: "PartPerMillion",
            PluralName: "PartsPerMillion",
            Abbreviations: ["ppm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e6,
            FromUnitToBase: static val => val / 1e6,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PartPerBillion
        VolumeConcentrationUnits.TryAdd("PartPerBillion", new Unit(
            SingularName: "PartPerBillion",
            PluralName: "PartsPerBillion",
            Abbreviations: ["ppb"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e9,
            FromUnitToBase: static val => val / 1e9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // PartPerTrillion
        VolumeConcentrationUnits.TryAdd("PartPerTrillion", new Unit(
            SingularName: "PartPerTrillion",
            PluralName: "PartsPerTrillion",
            Abbreviations: ["ppt"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * 1e12,
            FromUnitToBase: static val => val / 1e12,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "VolumeConcentration",
            "DecimalFraction",
            "The volume concentration (not to be confused with volume fraction) is defined as the volume of a constituent divided by the total volume of the mixture.",
            VolumeConcentrationUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> {  },
            "",
            false,
            1
        );
        _quantities.Add("VolumeConcentration", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
