// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Collections.Frozen;

namespace UoMConverter;

public static partial class UoMRegistry {
    private static void LoadVolumeFlow() {
        // Loading VolumeFlow
        var VolumeFlowUnits = new Dictionary<string, Unit>(StringComparer.OrdinalIgnoreCase);
        // CubicCentimeterPerHour
        VolumeFlowUnits.TryAdd("CubicCentimeterPerHour", new Unit(
            SingularName: "CubicCentimeterPerHour",
            PluralName: "CubicCentimetersPerHour",
            Abbreviations: ["cm³/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 2.7777777777778e-10,
            FromUnitToBase: static val => val * 2.7777777777778e-10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicInchPerHour
        VolumeFlowUnits.TryAdd("CubicInchPerHour", new Unit(
            SingularName: "CubicInchPerHour",
            PluralName: "CubicInchesPerHour",
            Abbreviations: ["in³/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 4.5519622224454e-9,
            FromUnitToBase: static val => val * 4.5519622224454e-9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMeterPerYear
        VolumeFlowUnits.TryAdd("CubicMeterPerYear", new Unit(
            SingularName: "CubicMeterPerYear",
            PluralName: "CubicMetersPerYear",
            Abbreviations: ["m³/y"],
            Factor: 3.170577045022194E-08,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMeterPerSecond
        VolumeFlowUnits.TryAdd("CubicMeterPerSecond", new Unit(
            SingularName: "CubicMeterPerSecond",
            PluralName: "CubicMetersPerSecond",
            Abbreviations: ["m³/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMeterPerMinute
        VolumeFlowUnits.TryAdd("CubicMeterPerMinute", new Unit(
            SingularName: "CubicMeterPerMinute",
            PluralName: "CubicMetersPerMinute",
            Abbreviations: ["m³/min"],
            Factor: 0.016666666666666666,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMeterPerHour
        VolumeFlowUnits.TryAdd("CubicMeterPerHour", new Unit(
            SingularName: "CubicMeterPerHour",
            PluralName: "CubicMetersPerHour",
            Abbreviations: ["m³/h"],
            Factor: 0.0002777777777777778,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMeterPerDay
        VolumeFlowUnits.TryAdd("CubicMeterPerDay", new Unit(
            SingularName: "CubicMeterPerDay",
            PluralName: "CubicMetersPerDay",
            Abbreviations: ["m³/d"],
            Factor: 1.1574074074074073E-05,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicFootPerSecond
        VolumeFlowUnits.TryAdd("CubicFootPerSecond", new Unit(
            SingularName: "CubicFootPerSecond",
            PluralName: "CubicFeetPerSecond",
            Abbreviations: ["ft³/s"],
            Factor: 0.028316846592,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicFootPerMinute
        VolumeFlowUnits.TryAdd("CubicFootPerMinute", new Unit(
            SingularName: "CubicFootPerMinute",
            PluralName: "CubicFeetPerMinute",
            Abbreviations: ["ft³/min", "CFM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.028316846592 / 60),
            FromUnitToBase: static val => val * 0.028316846592 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicFootPerHour
        VolumeFlowUnits.TryAdd("CubicFootPerHour", new Unit(
            SingularName: "CubicFootPerHour",
            PluralName: "CubicFeetPerHour",
            Abbreviations: ["ft³/h", "cf/hr"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.028316846592 / 3600),
            FromUnitToBase: static val => val * 0.028316846592 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicYardPerSecond
        VolumeFlowUnits.TryAdd("CubicYardPerSecond", new Unit(
            SingularName: "CubicYardPerSecond",
            PluralName: "CubicYardsPerSecond",
            Abbreviations: ["yd³/s"],
            Factor: 0.764554857984,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicYardPerMinute
        VolumeFlowUnits.TryAdd("CubicYardPerMinute", new Unit(
            SingularName: "CubicYardPerMinute",
            PluralName: "CubicYardsPerMinute",
            Abbreviations: ["yd³/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.764554857984 / 60),
            FromUnitToBase: static val => val * 0.764554857984 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicYardPerHour
        VolumeFlowUnits.TryAdd("CubicYardPerHour", new Unit(
            SingularName: "CubicYardPerHour",
            PluralName: "CubicYardsPerHour",
            Abbreviations: ["yd³/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.764554857984 / 3600),
            FromUnitToBase: static val => val * 0.764554857984 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicYardPerDay
        VolumeFlowUnits.TryAdd("CubicYardPerDay", new Unit(
            SingularName: "CubicYardPerDay",
            PluralName: "CubicYardsPerDay",
            Abbreviations: ["cy/day"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.764554857984 / 86400),
            FromUnitToBase: static val => val * 0.764554857984 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MillionUsGallonPerDay
        VolumeFlowUnits.TryAdd("MillionUsGallonPerDay", new Unit(
            SingularName: "MillionUsGallonPerDay",
            PluralName: "MillionUsGallonsPerDay",
            Abbreviations: ["MGD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1e6 * 0.003785411784 / 86400),
            FromUnitToBase: static val => val * 1e6 * 0.003785411784 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UsGallonPerDay
        VolumeFlowUnits.TryAdd("UsGallonPerDay", new Unit(
            SingularName: "UsGallonPerDay",
            PluralName: "UsGallonsPerDay",
            Abbreviations: ["gpd", "gal/d"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.003785411784 / 86400),
            FromUnitToBase: static val => val * 0.003785411784 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaUsGallonPerDay
        VolumeFlowUnits.TryAdd("MegaUsGallonPerDay", new Unit(
            SingularName: "MegaUsGallonPerDay",
            PluralName: "MegaUsGallonsPerDay",
            Abbreviations: ["Mgpd", "Mgal/d"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (0.003785411784 / 86400)) / 1000000,
            FromUnitToBase: static val => (val * 0.003785411784 / 86400) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerSecond
        VolumeFlowUnits.TryAdd("LiterPerSecond", new Unit(
            SingularName: "LiterPerSecond",
            PluralName: "LitersPerSecond",
            Abbreviations: ["l/s", "LPS"],
            Factor: 0.001,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerSecond
        VolumeFlowUnits.TryAdd("NanoLiterPerSecond", new Unit(
            SingularName: "NanoLiterPerSecond",
            PluralName: "NanoLitersPerSecond",
            Abbreviations: ["nl/s", "nLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1E-09,
            FromUnitToBase: static val => (val / 1000) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerSecond
        VolumeFlowUnits.TryAdd("MicroLiterPerSecond", new Unit(
            SingularName: "MicroLiterPerSecond",
            PluralName: "MicroLitersPerSecond",
            Abbreviations: ["µl/s", "µLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1E-06,
            FromUnitToBase: static val => (val / 1000) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerSecond
        VolumeFlowUnits.TryAdd("MilliLiterPerSecond", new Unit(
            SingularName: "MilliLiterPerSecond",
            PluralName: "MilliLitersPerSecond",
            Abbreviations: ["ml/s", "mLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 0.001,
            FromUnitToBase: static val => (val / 1000) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerSecond
        VolumeFlowUnits.TryAdd("CentiLiterPerSecond", new Unit(
            SingularName: "CentiLiterPerSecond",
            PluralName: "CentiLitersPerSecond",
            Abbreviations: ["cl/s", "cLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 0.01,
            FromUnitToBase: static val => (val / 1000) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerSecond
        VolumeFlowUnits.TryAdd("DeciLiterPerSecond", new Unit(
            SingularName: "DeciLiterPerSecond",
            PluralName: "DeciLitersPerSecond",
            Abbreviations: ["dl/s", "dLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 0.1,
            FromUnitToBase: static val => (val / 1000) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaLiterPerSecond
        VolumeFlowUnits.TryAdd("DecaLiterPerSecond", new Unit(
            SingularName: "DecaLiterPerSecond",
            PluralName: "DecaLitersPerSecond",
            Abbreviations: ["dal/s", "daLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 10,
            FromUnitToBase: static val => (val / 1000) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoLiterPerSecond
        VolumeFlowUnits.TryAdd("HectoLiterPerSecond", new Unit(
            SingularName: "HectoLiterPerSecond",
            PluralName: "HectoLitersPerSecond",
            Abbreviations: ["hl/s", "hLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 100,
            FromUnitToBase: static val => (val / 1000) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloLiterPerSecond
        VolumeFlowUnits.TryAdd("KiloLiterPerSecond", new Unit(
            SingularName: "KiloLiterPerSecond",
            PluralName: "KiloLitersPerSecond",
            Abbreviations: ["kl/s", "kLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1000,
            FromUnitToBase: static val => (val / 1000) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaLiterPerSecond
        VolumeFlowUnits.TryAdd("MegaLiterPerSecond", new Unit(
            SingularName: "MegaLiterPerSecond",
            PluralName: "MegaLitersPerSecond",
            Abbreviations: ["Ml/s", "MLPS"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * 1000) / 1000000,
            FromUnitToBase: static val => (val / 1000) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerMinute
        VolumeFlowUnits.TryAdd("LiterPerMinute", new Unit(
            SingularName: "LiterPerMinute",
            PluralName: "LitersPerMinute",
            Abbreviations: ["l/min", "LPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (1000 * 60),
            FromUnitToBase: static val => val / (1000 * 60),
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerMinute
        VolumeFlowUnits.TryAdd("NanoLiterPerMinute", new Unit(
            SingularName: "NanoLiterPerMinute",
            PluralName: "NanoLitersPerMinute",
            Abbreviations: ["nl/min", "nLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 1E-09,
            FromUnitToBase: static val => (val / (1000 * 60)) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerMinute
        VolumeFlowUnits.TryAdd("MicroLiterPerMinute", new Unit(
            SingularName: "MicroLiterPerMinute",
            PluralName: "MicroLitersPerMinute",
            Abbreviations: ["µl/min", "µLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 1E-06,
            FromUnitToBase: static val => (val / (1000 * 60)) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerMinute
        VolumeFlowUnits.TryAdd("MilliLiterPerMinute", new Unit(
            SingularName: "MilliLiterPerMinute",
            PluralName: "MilliLitersPerMinute",
            Abbreviations: ["ml/min", "mLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 0.001,
            FromUnitToBase: static val => (val / (1000 * 60)) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerMinute
        VolumeFlowUnits.TryAdd("CentiLiterPerMinute", new Unit(
            SingularName: "CentiLiterPerMinute",
            PluralName: "CentiLitersPerMinute",
            Abbreviations: ["cl/min", "cLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 0.01,
            FromUnitToBase: static val => (val / (1000 * 60)) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerMinute
        VolumeFlowUnits.TryAdd("DeciLiterPerMinute", new Unit(
            SingularName: "DeciLiterPerMinute",
            PluralName: "DeciLitersPerMinute",
            Abbreviations: ["dl/min", "dLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 0.1,
            FromUnitToBase: static val => (val / (1000 * 60)) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaLiterPerMinute
        VolumeFlowUnits.TryAdd("DecaLiterPerMinute", new Unit(
            SingularName: "DecaLiterPerMinute",
            PluralName: "DecaLitersPerMinute",
            Abbreviations: ["dal/min", "daLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 10,
            FromUnitToBase: static val => (val / (1000 * 60)) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoLiterPerMinute
        VolumeFlowUnits.TryAdd("HectoLiterPerMinute", new Unit(
            SingularName: "HectoLiterPerMinute",
            PluralName: "HectoLitersPerMinute",
            Abbreviations: ["hl/min", "hLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 100,
            FromUnitToBase: static val => (val / (1000 * 60)) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloLiterPerMinute
        VolumeFlowUnits.TryAdd("KiloLiterPerMinute", new Unit(
            SingularName: "KiloLiterPerMinute",
            PluralName: "KiloLitersPerMinute",
            Abbreviations: ["kl/min", "kLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 1000,
            FromUnitToBase: static val => (val / (1000 * 60)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaLiterPerMinute
        VolumeFlowUnits.TryAdd("MegaLiterPerMinute", new Unit(
            SingularName: "MegaLiterPerMinute",
            PluralName: "MegaLitersPerMinute",
            Abbreviations: ["Ml/min", "MLPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 60)) / 1000000,
            FromUnitToBase: static val => (val / (1000 * 60)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerHour
        VolumeFlowUnits.TryAdd("LiterPerHour", new Unit(
            SingularName: "LiterPerHour",
            PluralName: "LitersPerHour",
            Abbreviations: ["l/h", "LPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (1000 * 3600),
            FromUnitToBase: static val => val / (1000 * 3600),
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerHour
        VolumeFlowUnits.TryAdd("NanoLiterPerHour", new Unit(
            SingularName: "NanoLiterPerHour",
            PluralName: "NanoLitersPerHour",
            Abbreviations: ["nl/h", "nLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 1E-09,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerHour
        VolumeFlowUnits.TryAdd("MicroLiterPerHour", new Unit(
            SingularName: "MicroLiterPerHour",
            PluralName: "MicroLitersPerHour",
            Abbreviations: ["µl/h", "µLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 1E-06,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerHour
        VolumeFlowUnits.TryAdd("MilliLiterPerHour", new Unit(
            SingularName: "MilliLiterPerHour",
            PluralName: "MilliLitersPerHour",
            Abbreviations: ["ml/h", "mLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 0.001,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerHour
        VolumeFlowUnits.TryAdd("CentiLiterPerHour", new Unit(
            SingularName: "CentiLiterPerHour",
            PluralName: "CentiLitersPerHour",
            Abbreviations: ["cl/h", "cLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 0.01,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerHour
        VolumeFlowUnits.TryAdd("DeciLiterPerHour", new Unit(
            SingularName: "DeciLiterPerHour",
            PluralName: "DeciLitersPerHour",
            Abbreviations: ["dl/h", "dLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 0.1,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaLiterPerHour
        VolumeFlowUnits.TryAdd("DecaLiterPerHour", new Unit(
            SingularName: "DecaLiterPerHour",
            PluralName: "DecaLitersPerHour",
            Abbreviations: ["dal/h", "daLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 10,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoLiterPerHour
        VolumeFlowUnits.TryAdd("HectoLiterPerHour", new Unit(
            SingularName: "HectoLiterPerHour",
            PluralName: "HectoLitersPerHour",
            Abbreviations: ["hl/h", "hLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 100,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloLiterPerHour
        VolumeFlowUnits.TryAdd("KiloLiterPerHour", new Unit(
            SingularName: "KiloLiterPerHour",
            PluralName: "KiloLitersPerHour",
            Abbreviations: ["kl/h", "kLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 1000,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaLiterPerHour
        VolumeFlowUnits.TryAdd("MegaLiterPerHour", new Unit(
            SingularName: "MegaLiterPerHour",
            PluralName: "MegaLitersPerHour",
            Abbreviations: ["Ml/h", "MLPH"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 3600)) / 1000000,
            FromUnitToBase: static val => (val / (1000 * 3600)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // LiterPerDay
        VolumeFlowUnits.TryAdd("LiterPerDay", new Unit(
            SingularName: "LiterPerDay",
            PluralName: "LitersPerDay",
            Abbreviations: ["l/day", "l/d", "LPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val * (1000 * 86400),
            FromUnitToBase: static val => val / (1000 * 86400),
            Remarks: "",
            ObsoleteText: ""
        ));
        // NanoLiterPerDay
        VolumeFlowUnits.TryAdd("NanoLiterPerDay", new Unit(
            SingularName: "NanoLiterPerDay",
            PluralName: "NanoLitersPerDay",
            Abbreviations: ["nl/day", "nl/d", "nLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 1E-09,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 1E-09,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MicroLiterPerDay
        VolumeFlowUnits.TryAdd("MicroLiterPerDay", new Unit(
            SingularName: "MicroLiterPerDay",
            PluralName: "MicroLitersPerDay",
            Abbreviations: ["µl/day", "µl/d", "µLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 1E-06,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 1E-06,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MilliLiterPerDay
        VolumeFlowUnits.TryAdd("MilliLiterPerDay", new Unit(
            SingularName: "MilliLiterPerDay",
            PluralName: "MilliLitersPerDay",
            Abbreviations: ["ml/day", "ml/d", "mLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 0.001,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 0.001,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CentiLiterPerDay
        VolumeFlowUnits.TryAdd("CentiLiterPerDay", new Unit(
            SingularName: "CentiLiterPerDay",
            PluralName: "CentiLitersPerDay",
            Abbreviations: ["cl/day", "cl/d", "cLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 0.01,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 0.01,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DeciLiterPerDay
        VolumeFlowUnits.TryAdd("DeciLiterPerDay", new Unit(
            SingularName: "DeciLiterPerDay",
            PluralName: "DeciLitersPerDay",
            Abbreviations: ["dl/day", "dl/d", "dLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 0.1,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 0.1,
            Remarks: "",
            ObsoleteText: ""
        ));
        // DecaLiterPerDay
        VolumeFlowUnits.TryAdd("DecaLiterPerDay", new Unit(
            SingularName: "DecaLiterPerDay",
            PluralName: "DecaLitersPerDay",
            Abbreviations: ["dal/day", "dal/d", "daLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 10,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 10,
            Remarks: "",
            ObsoleteText: ""
        ));
        // HectoLiterPerDay
        VolumeFlowUnits.TryAdd("HectoLiterPerDay", new Unit(
            SingularName: "HectoLiterPerDay",
            PluralName: "HectoLitersPerDay",
            Abbreviations: ["hl/day", "hl/d", "hLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 100,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 100,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KiloLiterPerDay
        VolumeFlowUnits.TryAdd("KiloLiterPerDay", new Unit(
            SingularName: "KiloLiterPerDay",
            PluralName: "KiloLitersPerDay",
            Abbreviations: ["kl/day", "kl/d", "kLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 1000,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 1000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaLiterPerDay
        VolumeFlowUnits.TryAdd("MegaLiterPerDay", new Unit(
            SingularName: "MegaLiterPerDay",
            PluralName: "MegaLitersPerDay",
            Abbreviations: ["Ml/day", "Ml/d", "MLPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val * (1000 * 86400)) / 1000000,
            FromUnitToBase: static val => (val / (1000 * 86400)) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UsGallonPerSecond
        VolumeFlowUnits.TryAdd("UsGallonPerSecond", new Unit(
            SingularName: "UsGallonPerSecond",
            PluralName: "UsGallonsPerSecond",
            Abbreviations: ["gal (U.S.)/s"],
            Factor: 0.003785411784,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UsGallonPerMinute
        VolumeFlowUnits.TryAdd("UsGallonPerMinute", new Unit(
            SingularName: "UsGallonPerMinute",
            PluralName: "UsGallonsPerMinute",
            Abbreviations: ["gal (U.S.)/min", "GPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.003785411784 / 60),
            FromUnitToBase: static val => val * 0.003785411784 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UkGallonPerDay
        VolumeFlowUnits.TryAdd("UkGallonPerDay", new Unit(
            SingularName: "UkGallonPerDay",
            PluralName: "UkGallonsPerDay",
            Abbreviations: ["gal (U. K.)/d"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.00454609 / 86400),
            FromUnitToBase: static val => val * 0.00454609 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaUkGallonPerDay
        VolumeFlowUnits.TryAdd("MegaUkGallonPerDay", new Unit(
            SingularName: "MegaUkGallonPerDay",
            PluralName: "MegaUkGallonsPerDay",
            Abbreviations: ["Mgal (U. K.)/d"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / (0.00454609 / 86400)) / 1000000,
            FromUnitToBase: static val => (val * 0.00454609 / 86400) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UkGallonPerHour
        VolumeFlowUnits.TryAdd("UkGallonPerHour", new Unit(
            SingularName: "UkGallonPerHour",
            PluralName: "UkGallonsPerHour",
            Abbreviations: ["gal (imp.)/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.00454609 / 3600),
            FromUnitToBase: static val => val * 0.00454609 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UkGallonPerMinute
        VolumeFlowUnits.TryAdd("UkGallonPerMinute", new Unit(
            SingularName: "UkGallonPerMinute",
            PluralName: "UkGallonsPerMinute",
            Abbreviations: ["gal (imp.)/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.00454609 / 60),
            FromUnitToBase: static val => val * 0.00454609 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UkGallonPerSecond
        VolumeFlowUnits.TryAdd("UkGallonPerSecond", new Unit(
            SingularName: "UkGallonPerSecond",
            PluralName: "UkGallonsPerSecond",
            Abbreviations: ["gal (imp.)/s"],
            Factor: 0.00454609,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // MegaUkGallonPerSecond
        VolumeFlowUnits.TryAdd("MegaUkGallonPerSecond", new Unit(
            SingularName: "MegaUkGallonPerSecond",
            PluralName: "MegaUkGallonsPerSecond",
            Abbreviations: ["Mgal (imp.)/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => (val / 0.00454609) / 1000000,
            FromUnitToBase: static val => (val * 0.00454609) * 1000000,
            Remarks: "",
            ObsoleteText: ""
        ));
        // KilousGallonPerMinute
        VolumeFlowUnits.TryAdd("KilousGallonPerMinute", new Unit(
            SingularName: "KilousGallonPerMinute",
            PluralName: "KilousGallonsPerMinute",
            Abbreviations: ["kgal (U.S.)/min", "KGPM"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1000 * 0.003785411784 / 60),
            FromUnitToBase: static val => val * 1000 * 0.003785411784 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // UsGallonPerHour
        VolumeFlowUnits.TryAdd("UsGallonPerHour", new Unit(
            SingularName: "UsGallonPerHour",
            PluralName: "UsGallonsPerHour",
            Abbreviations: ["gal (U.S.)/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.003785411784 / 3600),
            FromUnitToBase: static val => val * 0.003785411784 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicDecimeterPerMinute
        VolumeFlowUnits.TryAdd("CubicDecimeterPerMinute", new Unit(
            SingularName: "CubicDecimeterPerMinute",
            PluralName: "CubicDecimetersPerMinute",
            Abbreviations: ["dm³/min"],
            Factor: 1.6666666666666667E-05,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OilBarrelPerDay
        VolumeFlowUnits.TryAdd("OilBarrelPerDay", new Unit(
            SingularName: "OilBarrelPerDay",
            PluralName: "OilBarrelsPerDay",
            Abbreviations: ["bbl/d", "BOPD"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.158987294928 / 86400),
            FromUnitToBase: static val => val * 0.158987294928 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OilBarrelPerMinute
        VolumeFlowUnits.TryAdd("OilBarrelPerMinute", new Unit(
            SingularName: "OilBarrelPerMinute",
            PluralName: "OilBarrelsPerMinute",
            Abbreviations: ["bbl/min", "bpm"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.158987294928 / 60),
            FromUnitToBase: static val => val * 0.158987294928 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OilBarrelPerHour
        VolumeFlowUnits.TryAdd("OilBarrelPerHour", new Unit(
            SingularName: "OilBarrelPerHour",
            PluralName: "OilBarrelsPerHour",
            Abbreviations: ["bbl/hr", "bph"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (0.158987294928 / 3600),
            FromUnitToBase: static val => val * 0.158987294928 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // OilBarrelPerSecond
        VolumeFlowUnits.TryAdd("OilBarrelPerSecond", new Unit(
            SingularName: "OilBarrelPerSecond",
            PluralName: "OilBarrelsPerSecond",
            Abbreviations: ["bbl/s"],
            Factor: 0.158987294928,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicMillimeterPerSecond
        VolumeFlowUnits.TryAdd("CubicMillimeterPerSecond", new Unit(
            SingularName: "CubicMillimeterPerSecond",
            PluralName: "CubicMillimetersPerSecond",
            Abbreviations: ["mm³/s"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / 1e-9,
            FromUnitToBase: static val => val * 1e-9,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AcreFootPerSecond
        VolumeFlowUnits.TryAdd("AcreFootPerSecond", new Unit(
            SingularName: "AcreFootPerSecond",
            PluralName: "AcreFeetPerSecond",
            Abbreviations: ["af/s"],
            Factor: 1233.48183754752,
            Offset: 0,
            FromBaseToUnit: null,
            FromUnitToBase: null,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AcreFootPerMinute
        VolumeFlowUnits.TryAdd("AcreFootPerMinute", new Unit(
            SingularName: "AcreFootPerMinute",
            PluralName: "AcreFeetPerMinute",
            Abbreviations: ["af/m"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1233.48183754752 / 60),
            FromUnitToBase: static val => val * 1233.48183754752 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AcreFootPerHour
        VolumeFlowUnits.TryAdd("AcreFootPerHour", new Unit(
            SingularName: "AcreFootPerHour",
            PluralName: "AcreFeetPerHour",
            Abbreviations: ["af/h"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1233.48183754752 / 3600),
            FromUnitToBase: static val => val * 1233.48183754752 / 3600,
            Remarks: "",
            ObsoleteText: ""
        ));
        // AcreFootPerDay
        VolumeFlowUnits.TryAdd("AcreFootPerDay", new Unit(
            SingularName: "AcreFootPerDay",
            PluralName: "AcreFeetPerDay",
            Abbreviations: ["af/d"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1233.48183754752 / 86400),
            FromUnitToBase: static val => val * 1233.48183754752 / 86400,
            Remarks: "",
            ObsoleteText: ""
        ));
        // CubicCentimeterPerMinute
        VolumeFlowUnits.TryAdd("CubicCentimeterPerMinute", new Unit(
            SingularName: "CubicCentimeterPerMinute",
            PluralName: "CubicCentimetersPerMinute",
            Abbreviations: ["cm³/min"],
            Factor: 1,
            Offset: 0,
            FromBaseToUnit: static val => val / (1e-6 / 60),
            FromUnitToBase: static val => val * 1e-6 / 60,
            Remarks: "",
            ObsoleteText: ""
        ));

        var q = new Quantity(
            "VolumeFlow",
            "CubicMeterPerSecond",
            "In physics and engineering, in particular fluid dynamics and hydrometry, the volumetric flow rate, (also known as volume flow rate, rate of fluid flow or volume velocity) is the volume of fluid which passes through a given surface per unit time. The SI unit is m³/s (cubic meters per second). In US Customary Units and British Imperial Units, volumetric flow rate is often expressed as ft³/s (cubic feet per second). It is usually represented by the symbol Q.",
            VolumeFlowUnits.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase),
            new Dictionary<string, int> { ["L"] = 3, ["T"] = -1 },
            "",
            false,
            1
        );
        _quantities.Add("VolumeFlow", q);
        foreach (var u in q.Units.Values) RegisterUnit(q, u);
    }
}
