name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish WASM
        run: dotnet publish UoMConverter.Wasm/UoMConverter.Wasm.csproj -c Release -o release --nologo

      # Copy index.html to 404.html to support client-side routing
      - name: Fix Routing
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # Add .nojekyll to ensure _framework files are served
      - name: Add .nojekyll
        run: touch release/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'release/wwwroot'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

